### ISSUE TITLE
Wonderful App

### ISSUE THREAD

**Issue by Humorist2601** [jameskokoska/Cashew#1]
Hello

Just want to start off by saying boy what a wonderful app you have built. Not just for budgets but overall. When I first saw the app, I thought it was going to be a closed source app (not many opensource apps are this beautiful). Was plesently surprised. Good work dev, hope you continue this in good health

~Now onto the request, the only thing mising from my pov is different currencies support, that is all. Thank you from creating this wonderful app.~

Well now I feel stupid, it already had this feature in the bank account page. Dude you're a wizard. 10/5 app.

I don't normally pay for apps but you deserve my donation. Kindly point me to the direction where I can donate you

**Comment by TheHawaiianKoala** [comment]
Cannot purchase Pro version as I do not have Google Playstore so I am thankful that you are releasing the app on Github. Might I suggest looking into [F-droid](https://f-droid.org/) to introduce your app to more FOSS enthusiast
