### ISSUE TITLE
Currency Rates for Transactions

### ISSUE THREAD

**Issue by nivisi** [jameskokoska/Cashew#10]
I think this is one of the features that I lack the most. I'm getting paid in one currency, but spending most of my money in a different one. The rates vary quite a lot these days, and I don't think that I'm getting the full picture of how much I spend (I do only in local currency).

Would be cool if we could get the rates and display it and the amount in the selected currency on a transaction (e.g. having a `≈ 150 YY` label)

Not entirely sure about the implementation and what rates provider can be used, but this definitely would have been a great feature... At least for me 😄 This would require proper feature designing. Let me know your opinion though.

**Comment by jameskokoska** [comment]
Hi there! The app supports exchange rates and displays the totals in both the main currency and selected transaction currency. This is done through multiple accounts with different currencies. Is this the feature you are looking for?


![Screenshot_20231030_104451.png](https://github.com/jameskokoska/Cashew/assets/50821962/32fee182-52ba-45b1-8f88-7a753ca124d4)

**Comment by jameskokoska** [comment]
Can be reopened if needed. Already implemented.
