### ISSUE TITLE
Enhancement of Budget Management Features to Accommodate Fiscal Year Planning

### ISSUE THREAD

**Issue by yihong1120** [jameskokoska/Cashew#101]
Dear Maintainers,

I trust this message finds you well. I am writing to propose an enhancement to the budget management capabilities of the Cashew application, which I believe could significantly benefit users who require fiscal year planning functionality.

**Current Limitation:**
At present, the application offers commendable flexibility in setting up personalised budgets with various time periods, such as monthly, weekly, and daily. However, it appears that there is a lacuna when it comes to planning and tracking budgets according to fiscal years, which are paramount for individuals and organisations that align their financial planning with tax years or corporate financial years.

**Proposed Enhancement:**
I suggest the introduction of a feature that allows users to define their fiscal year start and end dates. This would enable the application to automatically adjust the budget periods and reporting to reflect the fiscal year, thus providing a more tailored experience for those who adhere to such schedules.

**Potential Benefits:**
- **Alignment with Financial Regulations:** Users can ensure their budgeting is in sync with tax obligations and financial reporting requirements.
- **Improved Financial Planning:** By tracking budgets over fiscal years, users can better plan for annual financial goals and obligations.
- **Enhanced Reporting:** Fiscal year reporting would allow for a more accurate reflection of financial performance over the relevant period.

**Implementation Considerations:**
- The user interface could include an option within the settings to define the fiscal year.
- Budget creation workflows would need to incorporate the fiscal year as a potential budget period.
- Reporting and analytics features would need to be adapted to aggregate data based on the fiscal year.

I am aware that such an enhancement would require careful consideration, particularly with regard to the existing architecture and user experience. Nonetheless, I am convinced that the inclusion of this feature would be a substantial value addition to the Cashew application.

I am keen to discuss this proposal further and would be delighted to provide any additional information or clarification that might be required.

Thank you for your time and consideration.

Best regards,
yihong1120

**Comment by jameskokoska** [comment]
There are no plans to support fiscal years, in the sense you described. Fiscal years vary depending on the country/location as well.

If you want to track fiscal spending, you can just create a budget set as a yearly starting in the day the fiscal year starts. If you want to track fiscal quarters, since a year consists of 12 months / 4 quarters, just repeat it every 3 months.

Therefore, the app already supports this type of time range tracking.
