### ISSUE TITLE
[Feature Request] Show account balance in the Select Account Bottom Sheet

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#102]
**Is your feature request related to a problem? Please describe.**
When making Transfer Balance, a "Select Account" Bottom Sheet will appear, currently it only show a list of accounts excluding account balances.

![Screenshot_20231231-104605_Trebuchet](https://github.com/jameskokoska/Cashew/assets/125894401/b72be7e6-e5f1-47bf-a7a8-9d062f027d67)

**Describe the solution you'd like**
As can be seen, the right side of each account's name has a lot of extra space; able to add number of account balance display to make it more intuitive and convenient during the Transfer Balance process.

**Comment by jameskokoska** [comment]
Keep in mind that the title of accounts varies, some users may have long account names and therefore won't have space.

**Comment by jameskokoska** [comment]
Added here: https://github.com/jameskokoska/Cashew/commit/4cf9239a4e80a72aa0c423a793e5d7261149fab6#diff-310a4c8663e74b9c0cf6d380bf1201f12a9dbdd033347e0fe969c89880be7ec7R491-R510
