### ISSUE TITLE
[Feature Request] Let me select transaction grouping time range

### ISSUE THREAD

**Issue by bagarwa** [jameskokoska/Cashew#104]
**Is your feature request related to a problem? Please describe.**
On the transaction tab, I was trying to see the yearly income-outgo of an account; so that I can compare this year's gross balance with last year's gross balance. But the transaction page has only "month" grouping. There's no way I can see all transactions grouped by year. 

**Describe the solution you'd like**
Please add a "grouping" option icon at the top right of the transaction page, next to existing filter and search icons. Tapping that grouping icon will open a floating context menu, where users can select 

- GROUP BY WEEK
- GROUP BY MONTH
- GROUP BY QUARTER
- GROUP BY YEAR 

Very rough attempt at showing it - 
![Group](https://github.com/jameskokoska/Cashew/assets/4424058/f14ccfa7-5db8-472d-b440-746d77f4b720)

Tapping any of the options will change the grouping accordingly. For example, 
when user taps "Month", the tabs will remain as they are now - January | February | March etc. 
when user taps "Quarter", the tabs will change to - Jan-Mar | Apr-Jun | Jul-Sep | Oct-Dec etc. 
when user taps "Year", the tabs will change to - 2021| 2022 | 2023 etc. 

**Describe alternatives you've considered**
I tried the "search" option. I can select a date range from 1st Jan to 31se Dec there to show one year of transactions. But then to see previous years data, I will again have to change the date range. 

**Additional context**
For reference, you can check how MoneyLover app does it.

**Comment by jameskokoska** [comment]
The all spending page is able to breakdown spending periods and show the associated statistics as well. The transactions page only supports monthly lists of transactions
