### ISSUE TITLE
[Feature Request] income budget should track income

### ISSUE THREAD

**Issue by gabinci** [jameskokoska/Cashew#108]
I recieve multiple forms of income, my full time job (that pays me every 15 days), stocks (that pay on diferent days every month), extra work (may or may not happen), tips (may or may not happen) and more.

I would like to have a budget that tracks how much i earned this month, not a budget that subtracts my expenses from my income. 

That way i can easily see witch month earned me the most money over the estipulated.

Now, if i have more money than the estipulated, it will show a negative percentage. Eg. -105%.

**Comment by jameskokoska** [comment]
Added here: https://github.com/jameskokoska/Cashew/commit/74634b2ece943afb3a7ca198b04cf59caece27f0
