### ISSUE TITLE
Missing currency: maldivian rufiyaa

### ISSUE THREAD

**Issue by Abyvn** [jameskokoska/Cashew#11]
The ISO 4217 code for Maldivian rufiyaa: MVR

### https://en.m.wikipedia.org/wiki/Maldivian_rufiyaa#:~:text=%DE%83%3B%20code%3A%20MVR

**Comment by jameskokoska** [comment]
Added in https://github.com/jameskokoska/Cashew/commit/487a2f0df80cf64405f03d502fb4c5c88cbf4c0a
