### ISSUE TITLE
[Question] White line separates the numeric keypad

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#112]
**Describe your question**
I want to know if the white line - which I've highlighted to make it easier to visualize - separating this numeric keypad is a design intention, right?

![Imgur](https://imgur.com/27mopUP.png)

If correct, I think there is still one horizontal line and two vertical lines missing. If not, please remove it as it's a bit asymmetrical.

**Comment by jameskokoska** [comment]
If you are talking about faint separations between UI elements, it is a Flutter issue.

**Comment by ngocanhtve** [comment]
Can you open a PR to Flutter Project for fix that issue? 😁

**Comment by jameskokoska** [comment]
I think it's a pretty big issue with the way the rendering engine works. Unfortunately I don't have the time to take on a major task like that. 

I have however implemented a work around for Cashew.

**Comment by jameskokoska** [comment]
Fixed here: https://github.com/jameskokoska/Cashew/commit/155d65027ea2eb1fb7905fe6fe69d5d1ac9dd9a3
