### ISSUE TITLE
[Feature Request] Re-arrange the numeric keypad layout

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#113]
**Is your feature request related to a problem? Please describe.**
The current numeric keypad with three zeros is a bit unbalanced.

**Describe the solution you'd like**
![Imgur](https://imgur.com/WCT4pvl.png)

**Additional context**
I notice that the symmetry in the numeric keypad area seems to occupy our eyes more. So I placed three zeros in the middle column to ensure symmetry.

There are 5 characters ÷ × - + and ⌫ in the same column and we don't see too much asymmetry. It is more difficult to notice vertical asymmetry than horizontal.

**Comment by jameskokoska** [comment]
I appreciate the suggestion, however since the extra zeroes button is an add-on feature, I feel it shouldn't shuffle every button around. The location of the current buttons are strategically placed based on usability.

**Comment by ngocanhtve** [comment]
If the suggestion in illustration one is implemented, the three zeros button, if enabled, will only push the single zero button slightly to the right and the delete button will still be in the same row as before. I think the "strategically placed based on usability" hasn't changed much.

**Comment by ngocanhtve** [comment]
So how about like this :D

![](https://i.imgur.com/Y0SNj4P.jpeg)

**Comment by jameskokoska** [comment]
I think the main concern is I want the operations to be aligned with the numbers and I want to avoid off balance in that axis. Not only that but the operation buttons are quite squished when all stacked together.
The back button isn't an operation so it's preferable if it wasn't inline too.

**Comment by ngocanhtve** [comment]
I think arranging by column will be more symmetrical to help attract more eyes. In the context of smartphones today with increasing height, some software has added a row above the number 123 to have more space for calculation function buttons. Do you really want to limit the numeric keypad to 4 rows or is it a technical issue?

**Comment by sevenate** [comment]
Now that @ngocanhtve mentions that it is more difficult to notice vertical asymmetry than horizontal - I can't "unseen" it and it does started to bothering me _now_ while it was "bearable" _before_ ( something _was_ always off about it - I just couldn't figure it out on my own) 😁

**Comment by ngocanhtve** [comment]
@sevenate Haha 😁

**Comment by ngocanhtve** [comment]
> I want to avoid off balance in that axis.

I just think about of another solution which I saw implemented in a banking app in my country.

[![Input zeros number suggestion](https://markdown-videos-api.jorgenkh.no/url?url=https%3A%2F%2Fyoutu.be%2F39GytYlET30)](https://youtu.be/39GytYlET30)

Please remove the three-zero input button, instead add the ability to suggest zeros when entering as the clip. If the suggestion feature is working, the 3-zero input button will no longer be needed. The numeric keypad will return to its beautiful original symmetry :D

**Comment by jameskokoska** [comment]
I think the best solution would be to rearrange the order over the dropdown. I can look into pushing the back button on the right when the extra zero button is enabled

**Comment by jameskokoska** [comment]
Added here: https://github.com/jameskokoska/Cashew/commit/3e0816e6f2555be31ae2b67ed08a9de1f229b4ef
![image](https://github.com/jameskokoska/Cashew/assets/50821962/d38adc26-c392-4a0b-8a09-454a011d97fd)

**Comment by ngocanhtve** [comment]
> Added here: 3e0816e

Great! Thanks!
