### ISSUE TITLE
[Bug] Pie Chart Rendering Order

### ISSUE THREAD

**Issue by ManuelMurmann** [jameskokoska/Cashew#114]
**Describe the bug**
When a section of the pie chart (spending based on categories) is selected where the icon and therefore percentage is on the bottom center of the chart, the percentage overflows and is shown outside of the container. I suppose this is intended but the issue is, that when another widget is below the chart widget, the former widget is rendered above the latter one and therefore the percentage indicator is not visible. Just look at the screenshot

**How to reproduce**
On the homepage add the pie chart and something else below it (in my case Upcoming and Overdue transactions and then click on a category within the pie chart that is symmetrical to the y-axis

**Screenshots/videos**
![IMG_20240110_103953](https://github.com/jameskokoska/Cashew/assets/68563081/26bfbfe5-a89f-4c81-83e5-75ed7bf142b9)

**Details**
 - Device: One Plus 7
 - App Version: v5.1.3+296

**Comment by ManuelMurmann** [comment]
Closed because the issue is fixed in 5.1.7

**Comment by jameskokoska** [comment]
Just for documentation purposes: duplicate of https://github.com/jameskokoska/Cashew/issues/7
