### ISSUE TITLE
[Bug] Hidden issue borrowed funds in long-term loans

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#115]
**Describe the bug**
![](https://i.imgur.com/KcOVJ79.png)

Following the arrow, the Borrowed fund was covered by a huge amount of money.

**Screenshots/videos**
![](https://i.imgur.com/dszVGBX.png)

In Vietnamese, the hidden parts are even larger.

**Details**
 - Sony Xperia 1: 
 - App Version: [e.g. 5.1.7 Google Play]

**Comment by jameskokoska** [comment]
Fixed here: https://github.com/jameskokoska/Cashew/commit/8dc9ed1a1c5808ff0723d1c7d89a30c4c3528e1f

If there isn't any space, it is hidden - since it is just extra non-important information

**Comment by ngocanhtve** [comment]
> since it is just extra non-important information

Yeah. I agree with you!
