### ISSUE TITLE
[Feature Request] Add 12/24 hour setting

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#116]
**Is your feature request related to a problem? Please describe.**
![](https://i.imgur.com/pzQALXU.png)

10:00 and 22:00 are too close together - two circle time pickers are too close. I'm not sure if it's because the library designed it that way or because of Cashew's specific design purpose. Choosing between 10:00 and 22:00 is of course still good, but sometimes it's difficult and touch the wrong number between two, and for those with big fingers, I think it will be even easier to make mistakes.

**Describe the solution you'd like**
Make two circle time pickers farther apart.

**Describe alternatives you've considered**
Or separate it to AM and PM like this.
![](https://i.imgur.com/53u8VAz.png)

[Link for Flutter](https://m2.material.io/components/time-pickers/flutter)

**Comment by jameskokoska** [comment]
Since this uses Material 3 Components part of the Material library within Flutter, you'll have to report the bug over there. Cashew uses the locale of your device to determine the type of date picker. If your locale is 24 hours, it will use the 24 hour time picker.

**Comment by ngocanhtve** [comment]
> Cashew uses the locale of your device to determine the type of date picker. If your locale is 24 hours, it will use the 24 hour time picker.

I set the system time to 12 hours to test before requesting this feature. Cashew does not convert the time picker between 12-hour and 24-hour systems.

**Comment by jameskokoska** [comment]
It's a locale, not the device's 12 hour preference. I don't think there's a way to get the 12 hour preference per device in Flutter.

Again you can submit a bug report to the Flutter repo, especially since you are experiencing a usability issue with a component of the Material library

**Comment by ngocanhtve** [comment]
Cashew doesn't really support the 12-hour system time picker, does it? So is it possible to add support? I led this [12 hour Flutter](https://m2.material.io/components/time-pickers/flutter) support link that I saw on the internet, sorry if you already know that link and in case it didn't help.

**Comment by jameskokoska** [comment]
It does! Again, it's probably better to move this discussion over to the Flutter repo

![Screenshot_20240112_233037.png](https://github.com/jameskokoska/Cashew/assets/50821962/1dee8ecc-c8bf-4246-a496-46fead830a49)

**Comment by ngocanhtve** [comment]
> it's probably better to move this discussion over to the Flutter repo

I will learn it.

Btw, how to get like your screenshot?

**Comment by jameskokoska** [comment]
If your locale default uses 12 hour time format, the selector will be 12 hour time format.

**Comment by ngocanhtve** [comment]
> If your locale default uses 12 hour time format, the selector will be 12 hour time format.

Got it, thank you.

**Comment by ngocanhtve** [comment]
> If your locale default uses 12 hour time format, the selector will be 12 hour time format.

Update.

The situation is that only when selecting Cashew to English, there is a 12-hour times picker. When choosing Vietnamese language, the times picker will automatically change to 24 hours even though I have chosen the Android system to display 12 hours.

I think it should be turn into a feature that can be enabled in the settings.

**Comment by jameskokoska** [comment]
Since it's based on locale and you think it's an error with your locale, you'll need to bring it up with Flutter SDK.

**Comment by ngocanhtve** [comment]
> Since it's based on locale and you think it's an error with your locale, you'll need to bring it up with Flutter SDK.
> 
> Edit: Don't forget the main issue at hand here is that the numbers for the 24 hour picker are too close together. If you think this is an issue with the Material 3 design guidelines and the Flutter component, you should submit an issue ticket over there

Thanks for your suggestion. I will try to report these 2 issues to Flutter.

Btw, I see a habit tracking app that is also written in Flutter and has a "Date display format" feature to optionally display time stuff including "Use 12-hour format".

![](https://i.imgur.com/lnjqbqv.png)

It would be great if Cashew could also control how the time is displayed instead of waiting for an update from Flutter. In case Flutter takes a long time to update their source 😁

**Comment by jameskokoska** [comment]
Currently there are no plans to support different formatting from different locales - apart from the format of currencies/money.

Many users complain about the complex and overwhelming settings of apps, and Cashew already has so many options and customizations. For a streamlined user experience, it should follow that of the system/locale - and Flutter handles this. There should be no need to set this on a per app basis.

**Comment by jameskokoska** [comment]
I'm going to reopen this and consider adding a 12/24 hour format selector to Cashew.

However, the format of the 24 hour time picker having numbers too close together would be related to the Material library within Flutter

**Comment by ngocanhtve** [comment]
> I'm going to reopen this and consider adding a 12/24 hour format selector to Cashew.

Wonderful!

**Comment by jameskokoska** [comment]
Added here: https://github.com/jameskokoska/Cashew/commit/8dc9ed1a1c5808ff0723d1c7d89a30c4c3528e1f

**Comment by ngocanhtve** [comment]
![](https://i.imgur.com/g656tRm.png)

Working perfectly! Thank you.

**Comment by ngocanhtve** [comment]
> However, the format of the 24 hour time picker having numbers too close together would be related to the Material library within Flutter

https://github.com/flutter/flutter/issues/141501#issuecomment-1891576507

Help me! Please!
