### ISSUE TITLE
[Question] Should transactions added on mobile automatically sync up to the cloud?

### ISSUE THREAD

**Issue by hoooknew** [jameskokoska/Cashew#118]
I'm trying to test out the mobile app syncing using the iphone app and the pwa on desktop. Both are signed into the same google account. My desire is to have the app installed on two different phones with data syncing between them often enough.

Transactions added on my desktop appear on mobile on their own, but mobile changes only seem to sync when I pull down on the transactions list to force a sync. Should changes on the mobile app sync up without me doing anything extra or is the pull down on the list required to sync them? Thanks.

**Comment by jameskokoska** [comment]
All changes require either an app restart or a pull down to sync. There is no way of detecting automatic changes without constantly pinging Google services, which is not best practice when it comes to API usage.
