### ISSUE TITLE
Cohesion of Elements on the Web

### ISSUE THREAD

**Issue by EliasOS** [jameskokoska/Cashew#119]
**Describe the bug**
In the [web version of the platform](https://budget-track.web.app), exactly in the start menu the "Instalment payments" items collide with the view of all expenses and income. This can be seen more clearly in the screenshot I have attached.

**How to reproduce**
You just open the website

**Screenshots/videos**
![image](https://github.com/jameskokoska/Cashew/assets/61661800/1dc44107-b612-4b58-8ffb-2903970adc8e)

**Details**
 - Device: Google Chrome
 - App Version: 120.0.6099.217

**Comment by jameskokoska** [comment]
You can edit the homepage and move the long term loan section to display in the top center to avoid cut off. You can edit the homepage by clicking the three dot menu in the top right corner of the homepage, or in settings

![image](https://github.com/jameskokoska/Cashew/assets/50821962/af3884a5-91c1-416e-9710-d47945642f96)
