### ISSUE TITLE
[Bug] Hour and Minute Title is white in Manual mode Time Picker

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#120]
**Describe the bug**

When choosing the time in manual input mode, the **Hour** and **Minute** title is white, when you select the app theme Material You you will see white almost sunk into the background.

**How to reproduce**

When adding a transaction, edit time, tap the input mode toggle icon in the lower left corner of the time picker popup.

**Screenshots/videos**
![](https://i.imgur.com/p4ffjb4.png)

**Details**
 - Device: Sony Xperia 1
 - App Version: [e.g. 5.1.8+305]

**Additional notes**

Although I don't often edit time in manually mode, this is a minor issue. But in the spirit of contribution, I want to report this issue anyway.

**Comment by jameskokoska** [comment]
Fixed here: https://github.com/jameskokoska/Cashew/commit/0b113d20ef5fe1eded7e5aa9b7c7b42184954eac
