### ISSUE TITLE
Option to Transparency of widgets

### ISSUE THREAD

**Issue by Darchiver** [jameskokoska/Cashew#121]
**Is your feature request related to a problem? Please describe.**
I use a samsung phone which does not uses colour palette icons. Hence when I use widgets of cashew in home page it looks odd as it is in colour palette of the app theme.
![Screenshot_20240115_180138_One UI Home.jpg](https://github.com/jameskokoska/Cashew/assets/121549490/6e315a38-0f22-47eb-9647-c3a627c21523)

**Describe the solution you'd like**
i would like a option in widget to adjust transparency of widget upto 0% like they give for samsung default app widgets
![Screenshot_20240115_180255_Clock.jpg](https://github.com/jameskokoska/Cashew/assets/121549490/2cebe9a7-7b34-4cae-a733-a9acf66f23b9)

**Comment by Darchiver** [comment]
Adding to it
I don't know why you kept the number of transaction to be seen in widget, because I didn't find any use in it till now..

**Comment by jameskokoska** [comment]
Added here: https://github.com/jameskokoska/Cashew/commit/0b113d20ef5fe1eded7e5aa9b7c7b42184954eac
