### ISSUE TITLE
[Feature Request] Select account when collecting lent money

### ISSUE THREAD

**Issue by ManuelMurmann** [jameskokoska/Cashew#123]
**Is your feature request related to a problem? Please describe.**
Quite regularly when I create a loan because I paid for someone else, I pay by card but receive the money on PayPal or cash. The problem is that I can't select which account to return the money to when I collect the money in the app

**Describe the solution you'd like**
The option to select a different account when you receive the money on a loan. Exactly like when you select partially pay

**Describe alternatives you've considered**
I can click partially collect and select a different account but then the app creates a long term loan (which I don't like because then I have like 15 different long term loans

**Comment by ManuelMurmann** [comment]
Nvm haha, a duplicate once again. Sorry!
I've seen the other issue about this topic now, but what I wondered is whether you can hide long term loans? Because when I add a new transaction even the loans that are only valid for a day are shown. It gets really messy when you have a lot of long term loans

**Comment by ngocanhtve** [comment]
> but what I wondered is whether you can hide long term loans?

You can! Do you see the pencil to the right of the long-term loan button? There you will see an eye button to hide those loans.

**Comment by ManuelMurmann** [comment]
Oh yeah, you're right! Although this only hides long term loans in the loan overview, they are still shown when I add a transaction. Even when they are hidden, already completed and not even valid anymore

**Comment by ngocanhtve** [comment]
> they are still shown when I add a transaction. Even when they are hidden, already completed and not even valid anymore

I think you should reopen the issue and rename it to a feature request about "hide long-term loans from select list when adding new transactions". I think that's important. 

Even I think we should go further and combine the one-time loan feature with the long-term loan feature. Because in reality we rarely only lend money in cash and also collect it back in cash. Even if you borrow and pay the full amount in one-time in cash for example. The one-time loan feature also does not enough because it cannot record a settle transaction, the date of that transaction to know how long the loan period is. 

So I think it's a good idea to merge those two types of loans.

**Comment by jameskokoska** [comment]
I agree, however it was an unfortunate decision of the initial implementation. Long term loans solve the issue, and if something changes from the current implementation - current users will not understand why a current system has changed

See this comment for more insights. It's on my list, but not something of major importance
https://github.com/jameskokoska/Cashew/issues/106#issuecomment-1874831611

When long term loans are hidden (or anything else for that matter), they are still in the list but ALWAYS set to the end of the list.

**Comment by ManuelMurmann** [comment]
It's good that they are at the end of the list but at least I'd prefer it to hide them all together. It doesn't feel right not being able to see them in the loans overview but then stumbling across them when adding a new transaction. But it's really just personal preference, I don't like it cluttered but rather clean and without unnecessary information

**Comment by Michael152843** [comment]
The only inconvenience left in the app for me is the distinction between One-Time Loans and Long-Term Loans. I also believe these should be merged into a single category called Loans, as the current separation is confusing.

For example, if I lend money and collect it all at once, but three months later, is that a One-Time Loan or a Long-Term Loan? Similarly, if I collect the money next week but in multiple transactions, I would have to use a Long-Term Loan — but "next week" hardly feels like "long-term."

A combined Loans category should function like Long-Term Loans do now, including the ability to select an account. Meanwhile, what is currently called One-Time Loans could be reworked as Refunds, which is a very common type of transaction and which would be much clearer for most users than distinguishing between two types of loans.

Refunds could then be linked to specific transactions, allowing users to adjust the amount and display it differently in statistics while still preserving the original values.
