### ISSUE TITLE
[Feature Request] Credit Cards Feature 

### ISSUE THREAD

**Issue by sbriones97** [jameskokoska/Cashew#124]
Be able to select type of account between Debit and **Credit card**.
Having an account for credit card will let you configure **statement closing dates** and **payment due date** or days before payment due date for every month. An option to show the balance to pay after the statement closing date will be shown and the option to have it on the home page... as well for the information about days left before the due date and aggresive **notification** options for payment task before due date. Have a detail **report of transactions per statement cycle** of the account would be great plus for this
If want to keep it simple... adding the dates for every month and as well for the report per cycle of the account would be enough

**Comment by jameskokoska** [comment]
If you want to track credit spending, you can create a separate account and set the time range for reports in the All Spending page for that account. You can also view past spending ranges in the All Spending page. Proper credit card feature support is in the works, but I'm working at it on my own pace and don't have a release time and also don't want to keep any promises. Closing issue for now.

**Comment by webpixeldesign** [comment]
> If you want to track credit spending, you can create a separate account and set the time range for reports in the All Spending page for that account. You can also view past spending ranges in the All Spending page. Proper credit card feature support is in the works, but I'm working at it on my own pace and don't have a release time and also don't want to keep any promises. Closing issue for now.

Can we set different Time Range for reports for different section? I have 6 Credit Cards and all have different statement generation date.

**Comment by theinhumaneme** [comment]
Is there any possibilty of having a dedicated credit cards section anytime soon?

**Comment by Anu6is** [comment]
> Proper credit card feature support is in the works, but I'm working at it on my own pace and don't have a release time and also don't want to keep any promises.

@jameskokoska is the credit card feature still being considered/developed or has it been dropped?

**Comment by jameskokoska** [comment]
The development progress I have locally is quite out of date and isn't a priority currently. 
I have been using this workflow myself for credit cards and it's working for me
https://cashewapp.web.app/faq.html#track-credit-spending

**Comment by Anu6is** [comment]
@jameskokoska Thanks.. I am aware of the solution provided in the FAQ which does work relatively ok. The only issue I have is that cycles appear to apply to all accounts globally and individual accounts can't maintain a separate cycle. This means when I adjust for a particular card, I then need to adjust again for any additional cards. Finally it needs to be reset to the standard monthly cycle so that normal accounts are reported correctly. 

Unless I'm missing something, can 2 credit card accounts maintain individual cycles at the same time or am I correct in that I need to make these adjustments each time I wish view any reports for the CC account.

**Comment by Shadorain** [comment]
Maybe I'm simple minded but I struggle to understand how to properly use the workflow in the FAQ for a credit card account.
I don't really want to add "income" transactions to an account and then do anything hacky to knock it back down to 0 with my "checking" acount.
I was thinking maybe the Credit account would be my credit card limit and id do expenses on that and then the checking account would refill the account back to the limit...

Is there something I am missing in the FAQ that would help?

**Comment by Anu6is** [comment]
> I was thinking maybe the Credit account would be my credit card limit and id do expenses on that and then the checking account would refill the account back to the limit

That's my current setup. 
- The credit card account starts with the current available balance 
  * This would be the limit if the card is paid off
- Expenses/Purchases made using the card are added to the card account as regular expense transactions
  * This reduces the available balance so you can see how much you have left on the card 
  * Totaling the expenses would show how much you've spent
- Payments towards the card are done as transfers from whatever account was used to pay off your credit balance

**Comment by Shadorain** [comment]
I think this is probably the best way to do it yeah. I wish I could see how much total was spent instead of what is left on the limit but that I can do with other views! Thank you for the breakdown here this really helped.

I was wondering too with this way if there is any way to "top off" the Credit card account with my checking account (via a transfer). So if I spent 100 bucks in credit, to have checking take from itself and refill that 100?

**Comment by jameskokoska** [comment]
To track the total spent, I recommend using the budgets - the main feature of this app :‎) You can filter transactions to include in a budget based on your credit account for specific periods of your credit card

**Comment by Shadorain** [comment]
Oh good to know! I will set this up then and test it all out! Thank you so much!
 
 Side note, is there a community for Cashew like a Discord? I think that would go a long way to building a bigger stronger user base too!

**Comment by jameskokoska** [comment]
See https://github.com/jameskokoska/Cashew/issues/154

**Comment by Anu6is** [comment]
> To track the total spent, I recommend using the budgets - the main feature of this app :‎) You can filter transactions to include in a budget based on your credit account for specific periods of your credit card

You could probably include that idea in the FAQ.

**Comment by jameskokoska** [comment]
In the beta, cycles are applied per account. Beta/official release date is yet to be determined.

**Comment by santigarcor** [comment]
Great thanks. Weird I'm changing between accounts and if I set a cycle for one account and then move to another and set all time, it modifes the cycle for all of them

**Comment by jameskokoska** [comment]
As I mentioned, the feature is not released and is TBD.

**Comment by RichardSouzza** [comment]
Creating separate accounts for credit cards is currently a great approach for monitoring credit card expenses expenses, especially with the [setup](https://github.com/jameskokoska/Cashew/issues/124#issuecomment-2331708774) suggested by @Anu6is. However, this can quickly become cluttered when multiple credit cards coexist alongside bank accounts.

In that scenario, having sub-accounts representing credit cards linked to bank accounts could greatly improve organization and clarity. It would also be convenient to have an easy way to exclude the balance of these credit card sub-accounts from the total net worth calculation.
