### ISSUE TITLE
[Bug] "Duplicate transaction" Portuguese mistranslation

### ISSUE THREAD

**Issue by jrom99** [jameskokoska/Cashew#126]
**Describe the bug**
Portuguese version has a mistranslation of the "duplicate transaction" action label

**How to reproduce**
- Press down to select a transaction
- Tap the three dots on the top
- Duplicate transaction shows as "duplicado" (a better translation would be "duplicar", which is a verb, while "duplicado" is an adjective)

**Screenshots/videos**
![Screenshot_2024-01-20-14-59-55-444-edit_com.budget.tracker_app.jpg](https://github.com/jameskokoska/Cashew/assets/47498278/1ce29dc7-b75e-438e-8734-9aa762d6ded7)

**Details**
 - Device: Redmi Note 9 (MI Global 13.0.2, Android 12)
 - App Version: 5.1.9+308, db v46

NOTE TO THE SUBMITTER
Reporting bugs is important for maintaining the app. Thank you for helping make the app a better experience for all!

**Comment by ngocanhtve** [comment]
There is a Google sheet for editing translations, which will be updated into the app with each new release. Perhaps you should ask to participate in editing that sheet for your language.

**Comment by jrom99** [comment]
Thanks! I fixed it in the spreadsheet.

**Comment by jameskokoska** [comment]
Thank you! Updates to the translations have been pushed to the repo and will eventually make it into the next release!
