### ISSUE TITLE
[Bug] 0% of outgoing

### ISSUE THREAD

**Issue by ManuelMurmann** [jameskokoska/Cashew#128]
**Describe the bug**
Whenever a breakdown of income or outgoing transactions is shown (down to categories), the categories with really little money compared to the overall total have the subtitle "0% of [...]". Even if their total is not 0.

**How to reproduce**
Have an outgoing or incoming amount greater than 100 times the amount of a certain category in that timeframe. Then look at the category breakdown on the all spending page

**Screenshots/videos**
![Screenshot_2024-01-22-08-37-02-25_e6824bb696bab290a098ced1b814527d](https://github.com/jameskokoska/Cashew/assets/68563081/fe6e1347-3c65-4992-9822-9d05a761021c)

**Details**
 - Device: OnePlus 7
 - App Version: v5.1.9+308

**Additional notes**
It's not entirely a bug, just a bit confusing. It should be shown as "<1%" instead

**Comment by ngocanhtve** [comment]
Yeah you are right! Same that bug for me.

![](https://i.imgur.com/atknAYy.png)

From more than 1.7 million to 3.6 million are calculated as 1%. A little less than 1.5 million will be counted as 0%. It should be a number 0% ≤ it ≤ 1%. Moreover, we should calculate more accurately, it is impossible that 3.6 million is only the same percent to 1.7 million.

**Comment by jameskokoska** [comment]
Added here https://github.com/jameskokoska/Cashew/commit/7eb081b2a22c32f67fd2d422224bb9c67fbf86e3#diff-eca24bde063a5702d757d5ef8580067d1d81124bf8f972df348cd3a1e97c787bR37-R64

**Comment by jameskokoska** [comment]
The decimal precision can be tweaked with a setting. Added in https://github.com/jameskokoska/Cashew/commit/bd6fc142ba3eaee2390ae83e44f23d2ab85100d4

**Comment by ngocanhtve** [comment]
Works perfectly now! Thank you very much!
