### ISSUE TITLE
[Feature Request] "Contains" instead of "equal" for associated titles

### ISSUE THREAD

**Issue by ManuelMurmann** [jameskokoska/Cashew#129]
**Is your feature request related to a problem? Please describe.**
At some point when you have a bunch of categories you can't add a title for every single type of transaction but would rather have certain keywords, at least that's the case for me. For example if I have a category Lunch with the an associated title "Lunch" I might have transaction like "With friends at lunch" or "Dinner + Lunch" or something. The issue is that I can't use associated titles unless I have hundreds of different titles for every occasion which gets really messy

**Describe the solution you'd like**
A simple solution would be to check if the title you enter contains any of the associated titles instead of comparing them directly. Because then I could add a title "Lunch" to my category "Lunch" and then every transaction with the word "Lunch" in its name gets correctly associated to that category

**Describe alternatives you've considered**
Using a lot of titles

**Comment by ngocanhtve** [comment]
I also feel like sometimes the title suggestions are not very complete or accurate.

**Comment by ManuelMurmann** [comment]
Okay I see. Wouldn't it be possible to use "IN" though? You could use a select statement like 
`SELECT category FROM TITLES WHERE title IN ("Lunch", "+", "Dinner")` by splitting the words into an array. Not sure if that's a effective method though

**Comment by jameskokoska** [comment]
Added here: https://github.com/jameskokoska/Cashew/commit/100e22ca8f6dc018a50c26f5aade1e6206b386ca
