### ISSUE TITLE
Multi account transaction 

### ISSUE THREAD

**Issue by KhaiCo** [jameskokoska/Cashew#13]
Many platform these days allow for combining sources of fund, an example is Google Play that allow combining balance and other methods (bad example but a valid one) . I think that to better represent these type of transactions, transactions can be made with 2 source of funds if needed to better represent these type of transactions

**Comment by jameskokoska** [comment]
Hey thank you for the idea! The way calculations work for conversions of funds between currencies and the database tables, multi account transactions will not be planned. In addition, it may cause some confusion to users.

**Comment by KhaiCo** [comment]
I see, it's quite a shame as it closes many possible scenarios where multi account transaction is incredibly useful like price reduction from a point system that is present in many platforms. But thanks for responding!

**Comment by jameskokoska** [comment]
If you need to transfer funds between accounts, you can do so in the account details page. Tap the three dot menu in the top right corner
![image](https://github.com/jameskokoska/Cashew/assets/50821962/6bc7aefa-6f71-493b-9283-0b3ecb9a05e0)
