### ISSUE TITLE
[Question] Can i add Loan without a transaction?

### ISSUE THREAD

**Issue by Grabstertv** [jameskokoska/Cashew#135]
**Describe your question**
Sometimes i want to add a loan entry for an item i have purchased but did not yet pay for. I dont want to add a transaction for it as no money was yet exchanged. 

How do i add a loan entry without a transaction for such situations? I want to see the amount as a reminder and to pay it out later. but i dont want my amount in accounts changed.

**Comment by ngocanhtve** [comment]
I usually create 2 transactions

**Comment by ngocanhtve** [comment]
I usually create 2 transactions

**Comment by ngocanhtve** [comment]
> > I usually create 2 transactions
> 
> Can you elaborate? What does your process look like

I created a loan transaction, then created a transaction that used that amount to pay.

**Comment by Grabstertv** [comment]
Thats a good workaround but it will reflect in the overall stats. Which can get confusing.

**Comment by ngocanhtve** [comment]
> Thats a good workaround but it will reflect in the overall stats. Which can get confusing.

I feel fine about that. After all, I had to pay to get the item, after all, I was in debt, 2 transactions really helped me shape the situation better.

**Comment by Grabstertv** [comment]
I'll give this a try. Appreciate it!

I do also wish loans were handled similar to Waller by budget bakers. They let you create sort of like a seperate account for them that sit in its own menu. Then overtime if there are transactions related to that account you can add them and see them all in one place. I'm bummed out Cashew doesnt let you group multiple loan transactions.
