### ISSUE TITLE
[Feature Request] Stocks and ETF investments tracking

### ISSUE THREAD

**Issue by saamdotexe** [jameskokoska/Cashew#140]
**Is your feature request related to a problem? Please describe.**
At the moment there is no way of automatically tracking investments, like stocks and ETF shares.

**Describe the solution you'd like**
It would be extremely helpful to be able to add how many shares you own of a specific asset and keep track of how much the portfolio is valued at in total.
As a basic feature it should just be able to keep track of the value at present time.
On the long run it might even evolve into a more advanced feature that keeps track of the fluctuation in the price, giving you the history of the portfolio value, but just be able to at least having the current value automated would be a game changer.
A closed source competitor of Cashew already does this.

**Describe alternatives you've considered**
I've considered creating a new Account as an "Investments" account and updating it daily, but it becomes ugly and inconvenient real quick.

**Comment by jameskokoska** [comment]
No plans as this is out of the scope of this application. There are many other applications that have a focus on investments which are better suited. This application focuses on spending habits, not investments.

**Comment by danmigdev** [comment]
Would it be possible to add Google finance (or similar) as source for rates for other assets than currencies? The idea is to have a "Stocks" account where I can add transactions and the value is automatically reflected into net worth section. We can currently do exactly this with BTC because the app can read forex exchange rates.

**Comment by pflajszer** [comment]
+1 for this feature. I'd start using it if the app provided this!

**Comment by delath** [comment]
> No plans as this is out of the scope of this application. There are many other applications that have a focus on investments which are better suited. This application focuses on spending habits, not investments. You are free to add investments manually and treat them as transactions within Cashew into a separate account if you wish.

By treating them as transactions we would not be able to know the true value of our assets.
I second what @danmigdev wrote, we already can do that for BTC, i don't see why adding the support for google finance (or anything else) would be an issue 😞
