### ISSUE TITLE
[Bug] Transfer transactions are out of order by default

### ISSUE THREAD

**Issue by Elangovan-09** [jameskokoska/Cashew#144]
**Describe the bug**
Previously, when adding a transfer transaction, the transfer out entry would be added first, followed by the transfer in entry. However, the sequence has now reversed, with the transfer in entry being added first, followed by the transfer out entry.

**How to reproduce**
Add a new transfer transaction.

**Screenshots/videos**
![Screenshot_20240208-154951_Now](https://github.com/jameskokoska/Cashew/assets/159429847/7ab6fba2-7b88-4533-96c7-02a0b0c4fee0)
![Screenshot_20240208-154903_Before](https://github.com/jameskokoska/Cashew/assets/159429847/ab4a3444-91cc-46e3-a21e-d969cc3129bf)

**Details**
 - Device: 
 - App Version: [e.g. 4.9.4+256]

**Additional notes**
[Any additional information can go here]

NOTE TO THE SUBMITTER
Reporting bugs is important for maintaining the app. Thank you for helping make the app a better experience for all!

**Comment by jameskokoska** [comment]
Fixed here: https://github.com/jameskokoska/Cashew/commit/0f0d956ec3fb287ba623105e48a9a9d80e9ad91e

**Comment by Elangovan-09** [comment]
Hi @jameskokoska,

When can I expect this fix to be implemented in the app? I haven't received any updates for the app yet.

Thanks in advance for your response.

Thanks,
Elangovan.

**Comment by jameskokoska** [comment]
Sorry I haven't had much free time lately. Probably within the next few days. I do want to get a couple more changes and fixes into the next update - some users have complained updates are too frequent, so I need to strike a balance.

**Comment by ngocanhtve** [comment]
> some users have complained updates are too frequent, so I need to strike a balance.

Who is like that? Automatic updates are done by Google Play Store, why complain?
