### ISSUE TITLE
[Question] How to reorder goals?

### ISSUE THREAD

**Issue by jrom99** [jameskokoska/Cashew#145]
**Describe your question**

How do I reorder my goals ("Mais"/three dots icon -> "Metas"/piggybank icon)?
Also, I'd like to ask what is a "Savings goal" and how is it expected to work versus an "Expense goal"

## System information

Cashew v5.2.0+321, db-v46
Redmi Note 9 with MIUI Global 13.0.2 (Android 12 SP1A)

**Comment by jameskokoska** [comment]
You can reorder goals by tapping the 'edit' icon in the top right corner. Drag each entry to change the order. (See screenshot) ![Screenshot_20240208_091705.png](https://github.com/jameskokoska/Cashew/assets/50821962/c4f82321-5904-4ca3-96ca-9adb7745701f)

The difference between savings and expense goals are explained in the app when you first add a goal. (See screenshot) ![Screenshot_20240208_091823.png](https://github.com/jameskokoska/Cashew/assets/50821962/759bc571-950d-4a60-b91f-b1123ab441ee)
