### ISSUE TITLE
[Bug] restoring backup causes goal transactions to no longer debit from the account

### ISSUE THREAD

**Issue by hwangeug** [jameskokoska/Cashew#149]
**Describe the bug**
When restoring from a backup which had transactions that were allocated to a goal, prior to restoring the backup, the amount of the transaction was added to the goal, and subtracted from the account.  After restoring the backup, the money allocated to those goals was added back to the account.  e.g.

I have $200 in my account.  I create a transaction for $100 from account -> my goal.  Now, my account has $100 in it, and my goal has $100 in it.
I then create a backup, and restore it.
Upon restarting the app, I now have $200 in my account, and $100 in my goal.

**How to reproduce**
1. Create a goal and allocate money to it from an account.
2. Restore a backup which has these transactions.

**Details**
 - Device: Sony Xperia 1 Mark V, Android 14
 - App Version: 5.2.0+321, db-v46

**Comment by jameskokoska** [comment]
Sorry I'm not sure I understand the issue. If you assign a transaction to a goal, it will still count in your account total. I don't think this has anything related to restoring backups as the entire SQL is overwritten. Please provide more details if necessary, closing for now. Unable to replicate.

**Comment by hwangeug** [comment]
I could be misunderstanding the way you intend it to work, and what actually is going on, but what I actually experienced was thus:

1. I had $164 in my account prior to restoring a backup.
2. I had to restore a backup.
3. Upon restoring a recent backup, I had over $1000 in my account.  When I went back to look at why, after restoring the backup, it looked like historical transactions involving adding income to a goal was now being counted in both the goal and towards the account.  I do not believe this was the case before

I've attached a screencast of the restore process.

[output.webm](https://github.com/jameskokoska/Cashew/assets/11950803/36dcfb7a-e48a-4abd-9c12-3da71311d29f)

**Comment by jameskokoska** [comment]
After restoring a backup Cashew tries to restore syncing. If you don't want your synced devices to be restored you will need to delete them. You can do this by heading to the account page, and tapping [Sync] and deleting the sync backups. This will prevent any changes after a backup is restored.

![Screenshot_20240211_214122.png](https://github.com/jameskokoska/Cashew/assets/50821962/e506d48f-e23d-4559-88cc-819c0bbfc516)
