### ISSUE TITLE
[Bug] Currency conversions aren't saved

### ISSUE THREAD

**Issue by ManuelMurmann** [jameskokoska/Cashew#150]
**Describe the bug**
Whenever you have a loan (or dept) in a certain currency but collect the money in another currency, the conversion isn't saved but rather done every time you open the app. Therefore if I collect 100% it could be 101% the day after when the exchange rate is flexible (for example EUR to CHF)

**How to reproduce**
1. Create a loan transaction in on a CHF account (let's say 20CHF)
2. Partially collect the same amount in EUR to an EUR account (21,09€ at the moment)

This collects 100% of the original amount but once the exchange rate changes it will be more or less than that 

**Screenshots/videos**
![Screenshot_2024-02-15-12-26-37-11_e6824bb696bab290a098ced1b814527d](https://github.com/jameskokoska/Cashew/assets/68563081/0da241c7-9d1e-48a1-b7c0-5b4f2cf97196)
It was 100% when I collected it for the first time, then it changed

**Details**
 - Device: OnePlus 7
 - App Version: v5.2.0+321

**Additional notes**
A use case of this is when you go to another country and buy something for someone in your country. I needed to buy something in Switzerland (CHF) for a family member in Germany (EUR) so they could only give me EUR even though I payed in CHF

**Comment by jameskokoska** [comment]
Not necessarily a bug. Cashew converts currencies using the current currency conversion. Since the amount originally paid is worth less/more it is no longer considered an even settlement. 

To keep track, you would need to convert the currency in place. See #109

Edit: 
This is now fully documented in the FAQ: https://cashewapp.web.app/faq.html#multiple-currencies

**Comment by ManuelMurmann** [comment]
I'm not entirely sure I understand your solution. 

I understand that it does make sense that as the exchange rate changes so does the worth of either the settlement or the initial amount but once it's paid there shouldn't be any changes. Because now it's always either 100% settled or 100% settled but with a one cent difference, which is really confusing if I look at my overall loans

The loan in the screenshot for example used to be 100% settled but a few days later it's suddenly 101% settled as you can see, that's my issue
