### ISSUE TITLE
[Question] Native desktop support?

### ISSUE THREAD

**Issue by leranjun** [jameskokoska/Cashew#151]
**Describe your question**
First of all, thanks a million for this app! I must say the 5-star reviews on Google Play and App Store are well-deserved :)

I understand that Cashew has a PWA for desktop, but due to the Google authentication renewal limitation, sometimes I forget to log in and sync. Since Cashew is built with Flutter, is it possible to build native desktop apps? I'm not a Flutter dev myself, so I'm not sure where the technical complexities will lie.

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating questions. Duplicates will not be addressed again.**
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

(I searched around but don't think this has been mentioned yet.)

**Comment by ngocanhtve** [comment]
What do you think if we install Cashew Android on Windows? 😁

**Comment by leranjun** [comment]
> What do you think if we install Cashew Android on Windows? 😁

Was thinking about something similar, but I have a Mac, and the iOS app hasn't been marked as compatible for Silicon yet. Plus, doesn't WSA require Windows 11 anyway? I just thought it might be easier to have a dedicated app 😄

**Comment by ngocanhtve** [comment]
I think the iOS app will be compatible with macOS soon. :D

**Comment by leranjun** [comment]
Ah ok, that could also work.

**Comment by jameskokoska** [comment]
Thanks for the question! I've thought about developing a Windows version of Cashew. However, given that the user base would be quite small and that certain packages used aren't supported for Windows, it would require some tinkering. Given that Windows can run Android apps and that there is a separate web app, it was decided a Windows version wasn't worth the effort.

**Comment by leranjun** [comment]
Ah ok. Seems like Flutter also has an open issue on running iOS apps on Mac (flutter/flutter#125741), so maybe it still needs to be fixed on their side. I'll try myself when I have time then :)

**Comment by victor-marino** [comment]
> Given that Windows can run Android apps and that there is a separate web app, it was decided a Windows version wasn't worth the effort.

Hey there!

Sorry to bump such an old thread, but can you clarify if the Cashew Android app can be installed on Windows without using emulators, etc.? I know we can install games (they must be on the Play Games section), but I don't think we can officially install regular apps, either through the Play Store or even through individual APKs? Just for my understanding!

**Comment by Sebasss97** [comment]
Bump for this
