### ISSUE TITLE
[Question] Collect rounded loans

### ISSUE THREAD

**Issue by ManuelMurmann** [jameskokoska/Cashew#152]
**Describe your question**
Just a small little question about loans: Imagine I buy something for 4,99€ for another person and create a 4,99€ loan in Cashew for it.
Now the person gives me 5€ because it's easier than giving me 4€ 99 cent in coins.

How would I go about including this in the app? Do I collect the amount and then create a new transaction for the one cent with a category like "Rounding up" or is there an easier way?

**Comment by jameskokoska** [comment]
Hi there, thanks for the question! You're correct, the best way to track that would be to log down the remaining unaccounted for amount as a separate transaction.
