### ISSUE TITLE
[Feature Request] Allow customizing curremcy exchange rate on individual transfer transaction

### ISSUE THREAD

**Issue by botplo** [jameskokoska/Cashew#153]
**Is your feature request related to a problem? Please describe.**
When I'm transferring money from one account to another (that uses different currency), the currency exchange rate can differ every time I do a transaction/transfer. 
The problem is today, I might exchange 107 EUR for 107 USD (with an exchange rate of 1:1.07), but tomorrow, I might exchange 100 EUR and only get 101 USD (with an exchange rate of 1:1.01). Every time I do a transfer, the exchange rate might differ. 
Being able to keep track of this information so that I know how much I exactly spend when converting money between multiple currency would help better manage how much money I still have.

**Describe the solution you'd like**
A. Transfer Balance
When doing a transfer between accounts of different currency, it would be nice have an option to fill up a custom exchange rate. It could be a button beside the amount, when a user clicks on it, it pops up a smal window allowing user to specify either: 1. The exchange rate; OR 2. The exact amount on both the main currency and the target currency.

B. Edit Transaction
When editing transaction, adding an option (can be a button beside the amount - under Enter Amount window), that when a user clicks on it, it provides the same feature as transfer balance, and that is, a small window allowing user to specify either: 1. The exchange rate; OR 2. The exact amount on both the main currency and the target currency.

**Additional context**
![image](https://github.com/jameskokoska/Cashew/assets/160373838/14a93aff-8664-4565-8363-53c06be6ea51)
![image](https://github.com/jameskokoska/Cashew/assets/160373838/3eebc873-7e62-48ee-b191-9ed750f40805)

**Comment by jameskokoska** [comment]
Thank you for the request! Unfortunately the way Cashew handles currencies internally, only the current exchange rate is supported. Each account can only have one currency. You can set a custom exchange rate in the exchange rates page. You can also convert amounts in place (See screenshot) ![Screenshot_20231212_165246.png](https://github.com/jameskokoska/Cashew/assets/50821962/1e5bae6b-50ea-4dd1-a165-cb9f90e2ba25)

**Comment by jameskokoska** [comment]
Since Cashew converts transfers on the moment of, the currency exchange rate already holds the value at time. 
For example if you transfer 100 EUR from a EUR account to USD, with an exchange rate of 1.5
Cashew will create a transfer transaction for 100 EUR out and 150 USD in, preserving the exchange rate at that moment in time 

For simplicity usability purpose, Cashew uses the current exchange rate it pulls daily from the Exchange Rate API. You can customize the exchange rate of each currency in the currency list page within Edit Accounts.
