### ISSUE TITLE
[Question] Community Chat Channel?

### ISSUE THREAD

**Issue by eliasbenb** [jameskokoska/Cashew#154]
**Describe your question**
Is there a community chat channel for Cashew (Discord, Telegram, etc.)? I think it'd be nice to have a community for Cashew to talk about development.

**Comment by jameskokoska** [comment]
There is no community. Unfortunately, I don't have much time to manage one. I can possibly open up GitHub discussions on this repo.

**Comment by ngocanhtve** [comment]
A telegram chat group does not take much time to maintain. You just need to create a group for people to chat with each other, share how to use Cashew or cool tips!

**Comment by eliasbenb** [comment]
@ngocanhtve I think they're more worried about the moderation side of things. Being a moderator and picking out moderators could be time consuming

**Comment by Shadorain** [comment]
Any updates on this. Could we at least open up the Github discussions chat? I think that would be valuable for the community to have some engagement and help each other out.
