### ISSUE TITLE
[Feature Request] Divide expense transactions in need/want

### ISSUE THREAD

**Issue by enrique-lozano** [jameskokoska/Cashew#155]
First of all I would like to thank you for the magnificent work done on this application, I really think it is the best or one of the best in its segment.

I would like to know if it would be possible or very complex to implement a need/want division of transactions. Thanks to this division, it would be possible for me, for example, to track whether I am complying with the 50-30-20 rule (see [here](https://n26.com/en-eu/blog/50-30-20-rule))

The only app I see that has this functionality is Wallet, by BudgetBakers, where each category is assigned a kind of tag that can be "need", "want" or "debt" (I don't see the need to have the latter in our case):

![image](https://github.com/jameskokoska/Cashew/assets/61509169/52c6c058-764c-47f8-bf92-b37742d345fb)

**Comment by enrique-lozano** [comment]
Mmm, maybe I didn't express myself well before, it is far from being a wishlist nor does it have anything to do with future or unpaid transactions.

It is about organizing the expenses you have had according to whether they have been necessary for your life or not. For example, household expenses, food, electricity, water... vs. expenses for leisure, movies, entertainment, restaurants...

Anyway I don't see a bad option to use the notes field for this, so thanks a lot 😊

**Comment by ngocanhtve** [comment]
I think of setting budgets as percentages as you mentioned. Then include specific categories in the corresponding budget.
