### ISSUE TITLE
[Feature Request] Tasker Integration

### ISSUE THREAD

**Issue by Grabstertv** [jameskokoska/Cashew#157]
**Is your feature request related to a problem? Please describe.**
Not a problem but an enhancement. A Tasker integration that will help automate trigger based transaction creations.

**Describe the solution you'd like**
Tasker is a powerful automation app for androids that can do a lot of things. Apps can [integrate with Tasker](https://tasker.joaoapps.com/pluginslibrary.html) to execute actions based on triggers (called profiles in tasker)

Here is a scenario where this will be useful. Imagine you make a payment through your bank. They send you an email containing information about your transaction. You can use tasker to intercept that notification or even the email itself to grab the transaction amount and who it was send or received from. Then that information can be passed to a Cashew action in tasker that creates a transaction with that information filled out automatically. Essentially automating an entire process of creating bank transactions without connecting to the bank itself.

**Describe alternatives you've considered**
Probably with AutoInput plugin for Tasker that can navigate UI by simulating taps. Very complicated solution that i have not tried as it does not sound practical.

**Additional context**
N/a

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating feature requests. Duplicates will not be addressed again.**
Not all feature requests will be considered. This budget app was created with careful thought given to each feature's usability and prevention of feature overload. As you use the app, you will discover possibly related useful features and that may not be obvious right away. 
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by Grabstertv** [comment]
Ah unfortunate. I hope you consider this. I understand it might be a niche feature for the app's target audience but it would really help the small number of users that do use Tasker in their day-to-day lives to automate such tasks.

**Comment by jameskokoska** [comment]
See #127 for updates.
> Added in 5.2.3+328
> Documentation here: https://github.com/jameskokoska/Cashew/tree/main?tab=readme-ov-file#app-links
