### ISSUE TITLE
[Feature Request] Automatic login through the web app with google_sign_in_web

### ISSUE THREAD

**Issue by eliasbenb** [jameskokoska/Cashew#158]
As you're aware the web version of cashew expires sessions after only an hour.

I'm creating this issue to bring some changes to the `google_sign_in_web` package that were recently made to your attention. I'm not a flutter developer, so this information might not be fully accurate, but from what I understand, a new authentication flow specifically designed for flutter web apps was introduced in the latest major version (v0.12).

As described in [google_sign_in_web's documentation](https://pub.dev/packages/google_sign_in_web/versions/0.12.4) a `renderButton()` widget function was introduced which is a web alternative for the native `signInSilently()`.

Please correct me if I'm misunderstanding something here. Again, I've never used flutter but it seems like using the `renderButton()` widget is the newer and endorsed web authentication method while the older `signIn()` method, which is being used by Cashew [here](https://github.com/jameskokoska/Cashew/blob/3946a9b4748921d3a99d0ece47de2eccf9a82030/budget/lib/widgets/accountAndBackup.dart#L149) has been deprecated. Would using this new method allow for persistent web logins?

I love Cashew and it's beautiful UI and use it almost daily, half of the time from a browser, so having persistent web logins would be amazing. Thank you for this project and I hope something comes of this issue!

**Comment by jameskokoska** [comment]
Thanks for bringing this to my attention! By the looks of it, `renderButton()` simply renders a sign in button and does not automatically sign in the user silently, which is what is currently missing from the web implementation. It uses a more web native approach for signing in the user. Possible solutions that have already been explored: call the `signIn()` function every time the user launches Cashew on web if they have previously sign-in, but I have removed this as it brings annoyance. It is definitely something I have thought through, in addition to creating a custom snackbar informing the user about signing in. You can see that here: `SignInWithGoogleFlyIn` however unused (see screenshot)
![image](https://github.com/jameskokoska/Cashew/assets/50821962/9f392ef8-8863-479b-939d-9920185ee06b)

Additionally, the new Google Sign-in requires SDK version `3.2.0` and Cashew currently runs SDK `3.0.0`. There are plans to upgrade the SDK in the future, but not at the current moment as it brings breaking changes.

**Comment by eliasbenb** [comment]
> Thanks for bringing this to my attention! By the looks of it, `renderButton()` simply renders a sign in button and does not automatically sign in the user silently, which is what is currently missing from the web implementation. It uses a more web native approach for signing in the user. Possible solutions that have already been explored: call the `signIn()` function every time the user launches Cashew on web if they have previously sign-in, but I have removed this as it brings annoyance. It is definitely something I have thought through, in addition to creating a custom snackbar informing the user about signing in. You can see that here: `SignInWithGoogleFlyIn` however unused (see screenshot) ![image](https://private-user-images.githubusercontent.com/50821962/307485015-9f392ef8-8863-479b-939d-9920185ee06b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NDgxMzgsIm5iZiI6MTcwODc0NzgzOCwicGF0aCI6Ii81MDgyMTk2Mi8zMDc0ODUwMTUtOWYzOTJlZjgtODg2My00NzliLTkzOWQtOTkyMDE4NWVlMDZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDA0MTAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzODM0YTJkYmQwOWYyMjQ2MmQyMjI3YzRhMmJmYzk3NDkzNjRiOWNjNThlYTliYmRhY2I1MzI2ZDY5MzQ4ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b6yPkYTOws1VJfdOffPnsD_Z6uGeK2OWgaTnABrkrcs)
 
> Additionally, the new Google Sign-in requires SDK version `3.2.0` and Cashew currently runs SDK `3.0.0`. There are plans to upgrade the SDK in the future, but not at the current moment as it brings breaking changes.

After reading more into the google_sign_in_web documentation I linked, I see that you're right about persistent authentication not being currently possible. However, have you seen this part of the documentation?:
>
>Expired / Invalid Authorization Tokens
>
>Since the GIS SDK does not auto-renew authorization tokens anymore, it's now the responsibility of your app to do so.
>
>Apps now need to monitor the status code of their REST API requests for response codes different to 200. For example:
>
>    401: Missing or invalid access token.
>    403: Expired access token.
>
>In either case, your app needs to prompt the end user to requestScopes, to interactively renew the token.
>
>The GIS SDK limits authorization token duration to one hour (3600 seconds).

I feel like this solution + maybe a config option to allow automatic login prompts would be a good middle ground.
Would love to hear your thoughts.

**Comment by jameskokoska** [comment]
Yes I went through all of its documentation. Currently if the token expires/is invalid, Cashew automatically retries its login (through a try catch within requests to scoped API calls). I think that with the last synced being red, automatically prompting the user for login when the sync button is pressed, and the sync button being always present if the user has previously logged in is the best solution that does not obstruct user workflow.
