### ISSUE TITLE
Option to add title to transfers

### ISSUE THREAD

**Issue by subhashay** [jameskokoska/Cashew#16]
Hi dev, 

Firstly, A big Thank for such an awesome app. I'm a big fan of open source budget mangers and have used Ivywallet for a long time now. 

This app is feature packed with literally everything one can imagine.

A small request is basically to add a title to transfers as in when transfer is added (I know,  I can edit the transaction later). Example, if I keep an account just for saving and want to transfers some amount to this account and label it as monthly saving.

Also, along with if there was an ability to ignore such savings accounts from graphs would  be awesome as well.

**Comment by jameskokoska** [comment]
Thanks for the suggestion! Added with this commit https://github.com/jameskokoska/Cashew/commit/b1fd5634133acf7b693524f2dd4e060e4155007b, will be out in the next version
If you want to ignore savings accounts from graphs, consider using a budget and select the budget graph. Currently there is no plan to implement this feature.
