### ISSUE TITLE
[Feature Request] Repetitive transfers

### ISSUE THREAD

**Issue by dxloop** [jameskokoska/Cashew#160]
**Is your feature request related to a problem? Please describe.**
Currently if you want to move money from account A to B each month automatically -> your only option is to add an expense for A and an income from B.
The problem is that it counts towards the expense and income amount, which seems inconvinient for this specific case.

**Describe the solution you'd like**
Solution 1:
> Toggle to exclude certain expenses and incomes to not count towards the amount

Solution 2:
> Add support for repetitive transfers

**Comment by jameskokoska** [comment]
You can already create repetitive transfer transactions. Transactions within the 'Balance Correction' category do not count towards income/expense totals. This is described in the descriptionwhen editing the 'Balance Correction' category.

To create a repetitive transfer, add a one time transfer, edit one of the transaction entries, set its type to repetitive. Update both transaction types to 'repetitive' when prompted after saving changes.

Alternatively, manually add 2 repetitive transactions of type repetitive belonging to the 'Balance Correction' category.

Edit: This has been added to the FAQ
https://cashewapp.web.app/faq.html#repetitive-transfers

**Comment by dxloop** [comment]
> You can already create repetitive transfer transactions. Transactions within the 'Balance Correction' category do not count towards income/expense totals. This is described in the descriptionwhen editing the 'Balance Correction' category.
> 
> To create a repetitive transfer, add a one time transfer, edit one of the transaction entries, set its type to repetitive. Update both transaction types to 'repetitive' when prompted after saving changes.
> 
> Alternatively, manually add 2 repetitive transactions of type repetitive belonging to the 'Balance Correction' category.

Oh, interesting. Probably missed out on that part, my bad.
