### ISSUE TITLE
[Bug] Restoring backup leads to "Error importing : No file selected"

### ISSUE THREAD

**Issue by Deytron** [jameskokoska/Cashew#163]
**Describe the bug**
After manually creating a backup, and transfering both a .csv and .sql file, trying to restore leads to the following errors:

- For SQL restoring: "Error importing : No file selected"
- For CSV restoring: "There was an error importing the CSV"

**How to reproduce**
- Create a manual backup
- Clear apps data, or start fresh on a new phone
- In Settings, try to restore from the files

**Screenshots/videos**

SQL restore:

![Sans titre-1](https://github.com/jameskokoska/Cashew/assets/20344764/1b2e9d78-6d2c-4ecd-812d-c9e7b88a10b8)

CSV restore:

![Sans titre](https://github.com/jameskokoska/Cashew/assets/20344764/2590bcd7-4dd0-4d89-b5a3-9042fb08541d)

**Details**
 - Device: Xiaomi Redmi Note 11 Pro 5G, Android 14
 - App Version: 5.2.3+328

**Additional notes**

I would like to send you the files so that you can test, but for obvious privacy reason I can't just make them public on the Internet. If I can send you the files privately, do tell me

_PS : First time I see an issues section of a repo so clean. Great job!_

**Comment by jameskokoska** [comment]
Thanks for reporting the issue! It seems very device specific unfortunately. When you attempt to restore a file, does the app not prompt you to select one? 

Also if you would like you can send the files to my email (found within the [More Options] > [About] page of the app)

**Comment by Deytron** [comment]
Thanks for the quick answer 😄 

The app does ask me to select the backup file.
I don't know if I can help further, maybe if you tell me the location I can collect some more logs

**Comment by jameskokoska** [comment]
Fixed here: https://github.com/jameskokoska/Cashew/commit/deaf15f3941761e1aa672e8849e30a56f5bd3b3a#diff-17359594bdf7b1db0a50591dad5bc3b5130b3449b639da96661663fdc6e67f50R44-R47
