### ISSUE TITLE
[Bug] Loan transaction is not displayed in expenses 

### ISSUE THREAD

**Issue by karthikeyantc** [jameskokoska/Cashew#164]
**Describe the bug**
[Enter a clear and concise description of what is wrong]
When a loan transaction that is set to repitative until loan finish for each month and If I mark paid for the current month, it is added to loan but it is not reflecting in the expense section in home page
**How to reproduce**
[Enter the steps to reproduce the bug]
Create a long term loan
Create a repitative payment of some amount until loan completes.
Make the transaction as paid 
Now check the expenses section in home page, enable it if not visible.
The loan transaction will not be calculated 
**Screenshots/videos**
[Screenshots/videos are always helpful]
![Screenshot_2024-03-05-20-12-26-235_com.budget.tracker_app.jpg](https://github.com/jameskokoska/Cashew/assets/128451743/b724cae2-d626-4ef3-af70-8576bab843e1)

![Screenshot_2024-03-05-20-12-21-729_com.budget.tracker_app.jpg](https://github.com/jameskokoska/Cashew/assets/128451743/710eb81f-10cd-4358-828f-3fe26238a5ac)

As you see in the transaction page I can see that is calculated but in home page it is not.
**Details**
 - Device: 
 - App Version: [e.g. 4.9.4+256]

**Additional notes**
[Any additional information can go here]

NOTE TO THE SUBMITTER
Reporting bugs is important for maintaining the app. Thank you for helping make the app a better experience for all!

**Comment by jameskokoska** [comment]
Hi there! You are using quite an old version of the app. Please update the app and update this thread.

I'm a bit confused by the screenshots provided and steps to reproduce, please reproduce a minimal example for clarity as well. Closing for now.
