### ISSUE TITLE
[Feature Request] Import CSV | Decimal and Thousand separator Issue.

### ISSUE THREAD

**Issue by justinmahendra** [jameskokoska/Cashew#165]
**Is your feature request related to a problem? Please describe.**
Import feature QOL. Different regions have different decimal and thousand separator.
In my region comma is used for decimal, but the app uses comma as thousand separator.

**Describe the solution you'd like**
Option to use ";" as separator? Or allow user to assign their own separator. As for "Amount" maybe have the options to either use comma-decimal or decimal-comma.

Maybe more import options in the future? JSON? QFX?

**Describe alternatives you've considered**

**Additional context**
Loving the app so far, just adjusting my csv to match app's requirements.

**Comment by jameskokoska** [comment]
Custom number formatting has been added here: https://github.com/jameskokoska/Cashew/commit/4c60125d30d9f388f9d5681ac5c73a4febf058d4
