### ISSUE TITLE
[Bug] No space between the search box and the selection title

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#166]
**Describe the bug**
When i type something to search in the transaction page, then select those results, the selected title box will overlap the search box.

**How to reproduce**
Type something, then select some of the results found. You will see.

**Screenshots/videos**
![](https://i.imgur.com/19RJbKA.png)
Search Results
![](https://i.imgur.com/rI0zdeM.png)
The selection title box overlaps the search box

**Details**
 - Device: Sony Xperia 1
 - App Version: 5.2.4 (335) Google Play Store

**Comment by jameskokoska** [comment]
Thanks for reporting! Not necessarily considered a bug. The selected transactions app bar is considered an overlay and is not aware of any UI underneath, including the search bar. Closing for now.
