### ISSUE TITLE
Need understanding of Savings goal

### ISSUE THREAD

**Issue by subhashay** [jameskokoska/Cashew#17]
I'm facing this issue currently with my workflow.

Let's say, I have an expense goal of Car loan payment. I move the money from account A to this goals, which is treated as expense and balance is updated fine. No issues here.

But for savings goal, what I do is I move some money to Hendgefunds or some long term investment. Even though this is savings goal, with the current app behavior this will still be in account A and also added to the goal. 

As a workaround I'm marking these goals also as expense but wanted to know if there is any better way or a fix for this?

Please do let me know if more explanation is needed.

Thanks.

**Comment by jameskokoska** [comment]
An expense goal would be the solution in your case. For clarification, a savings goal records income and a spending goal records expenses.
