### ISSUE TITLE
[Feature Request] Click Pie Chart To See Relevant Records

### ISSUE THREAD

**Issue by 8227846265** [jameskokoska/Cashew#170]
**Is your feature request related to a problem? Please describe.**
- There's no easy way to find what transactions make up a percentage of an expense (e.g. Groceries).
- The pie chart only shows how many percentages the category makes up but doesn't show the relevant transactions when clicked
- You'll have to go to History > Filter to get the result.

**Describe the solution you'd like**
- Click a percentage on the Pie Chart
- It will immediately display the transactions associated with that percentage.

**Describe alternatives you've considered**
- At the moment, I have to manually go to History > Filter to get to know more about my transactions in a certain category.

**Additional context**
- None as of the moment

**Comment by jameskokoska** [comment]
The pie chart homepage widget has been revamped here: https://github.com/jameskokoska/Cashew/commit/a61cb37133fd8cc7c7a90892431ac11b908cb60d

Keep in mind the [All Spending] summary will always give the most details, along with a budget summary page. Homepage sections are meant for glanceable information, not necessarily useful analysis information.

![Screenshot_20240310_213538](https://github.com/jameskokoska/Cashew/assets/50821962/40973fba-b115-41c6-b808-c19cdeec7e70)
