### ISSUE TITLE
[Bug] Can't sync with google drive (error 403)

### ISSUE THREAD

**Issue by polman4** [jameskokoska/Cashew#171]
**Describe the bug**
Getting a 403 error whenever i click to sync with google drive. I can log in but can't sync.
Error message: "DetailedApiRequestError(status: 403, message: Request had insufficient authentication scopes"

**How to reproduce**
I go to settings -> Google Drive -> Backup

**Screenshots/videos**
![error_sync](https://github.com/jameskokoska/Cashew/assets/43953633/c299d69b-cab4-4d14-9271-c535bbc30c11)

**Details**
 - Device: 
 - App Version: [e.g. 4.9.4+256]

**Additional notes**
[Any additional information can go here]

NOTE TO THE SUBMITTER
Reporting bugs is important for maintaining the app. Thank you for helping make the app a better experience for all!

**Comment by jameskokoska** [comment]
Hi there, please provide more information about your device and version number when reporting issues.

As the error message states, there are insufficient permissions allowed on that account. Please make sure you have enabled Cashew to access Google Drive on that Google account.
Please see the FAQ: https://cashewapp.web.app/faq.html#drive-permissions

Closing issue for now until more information is provided. Unable to replicate.

**Comment by polman4** [comment]
Hello James.
My version is v.5.2.4+335, db-v46
I'm accessing (https://budget-track.web.app/)from my laptop Windows 11, 23H2, Chrome: Version 122.0.6261.95 (Official Build) (64-bit)
Have only accessed the app in general from the web app. Haven't tried download yet on my phone. (i have iOS)
Please let me know if you need any other info.

Kind regards,
Grigoris

**Comment by jameskokoska** [comment]
Thank you for the information..

As the error message states, there are insufficient permissions allowed on that account. Please make sure you have enabled Cashew to access Google Drive on that Google account.

**Comment by polman4** [comment]
Ok, I managed to fix it.
For some reason, when I was logging from Chrome (win11) I was able to log in but I couldn't see the allow "google drive" permission notification. I even tried from incognito, cleared cookies or tried firefox.
Also, I couldn't see Cashew here: https://drive.google.com/drive/u/0/settings (manage apps)

So I downloaded the app on iOS, logged in, and then I was able to see the google drive permission prompt on my phone. After that I was able to sync data from web app and I can see the data on phone too.

Maybe this happens if your first login is from web app?

Thank you for your effort again.

**Comment by jameskokoska** [comment]
Hmm thanks for letting me know the details. I was still unable to replicate the issue on the web app. I get prompted for permissions on my first login with a new account

![image](https://github.com/jameskokoska/Cashew/assets/50821962/3eeae9ff-8a01-4bf1-b4ee-2fc2130e7710)

**Comment by Chiru-Dey** [comment]
this error is again happening
