### ISSUE TITLE
[Feature Request] Option to Exclude Transactions from Statistics

### ISSUE THREAD

**Issue by szulcDEV** [jameskokoska/Cashew#172]
**Is your feature request related to a problem? Please describe.**
When returns or claims, it's essential to remove the original transaction to keep statistical data accurate. But deleting these transactions leads to an incomplete budget history. The solution is to have an option to disable, rather than delete, such transactions. This allows the transaction to remain in the historical record for context, while ensuring that current statistics are not skewed.

**Describe the solution you'd like**
When creating or editing a transaction, include an option to exclude it from statistics by adding a checkbox.

> There is such a feature on Revolut, for instance.
https://help.revolut.com/help/app-features/budgeting-and-analytics/how-can-i-exclude-a-transaction-from-my-analytics-budget/

**Comment by jameskokoska** [comment]
Hi there! You can already do this by editing a transaction and tapping [More Options] to view the [Include Amount] setting. Additionally, you can exclude from specific budgets here as well.

See screenshots:

![Screenshot_20240310_173056.png](https://github.com/jameskokoska/Cashew/assets/50821962/ea0b01c4-d14b-4f20-b7d2-8cc9c1367c13)

![Screenshot_20240310_173114.png](https://github.com/jameskokoska/Cashew/assets/50821962/1939fa02-658e-426e-b5d2-4ef3c3c87cfc)

**Comment by wenbei** [comment]
Hi, I'm looking for the inverse of this and #203. I would like to exclude a purchase from from the account balance but still include it in the category statistics.
For example, cash purchases that I already withdrew from the account, but still want to track the spending.

Thank you.

**Comment by jameskokoska** [comment]
> Hi, I'm looking for the inverse of this and #203. I would like to exclude a purchase from from the account balance but still include it in the category statistics.
> For example, cash purchases that I already withdrew from the account, but still want to track the spending.

You can create a separate account to do this. This can be useful to track goals or budgets without affecting an account balance as well.
https://cashewapp.web.app/faq.html#set-budget-no-change-balance
