### ISSUE TITLE
Unable to login to google while using microG, Lineage OS 21

### ISSUE THREAD

**Issue by theinhumaneme** [jameskokoska/Cashew#174]
**Describe the bug**

I was trying to use my phone with 0 Google Mobile Services, with microG as a replacement, when clicked on the button to login i get an error, sign-in occurred.
All other google services login fine including google photos, the microG user community mentioned that if google photos is able to login, it is not a microG issue and could most probably be an app issue, I am not a app dev neither am I an android dev, this is all the information that I can offer

**How to reproduce**
Use a device with LineageOS or any Vanilla / DeGoogled AOSP ROM, with microG installed.

**Screenshots/videos**
![photo_2024-03-10_00-53-45](https://github.com/jameskokoska/Cashew/assets/71078441/4a9e5abe-f42d-40d7-beec-3255b3400bcc)

**Details**
 - Device: Redmi Note 12 Turbo
 - Android Version - Android 14
 - App Version: 5.2.4+335 - latest release
 
 Great App, Thank you for all the effort

**Comment by ngocanhtve** [comment]
I think the issue belongs to MicroG and you should report it to them.

**Comment by theinhumaneme** [comment]
> I think the issue belongs to MicroG and you should report it to them.

All google services work fine with microG only cashew app crashes, i have a message link which you can follow up with the microG group on telegram, maybe this can help

[comment thread](https://t.me/microG/125706)

**Comment by ngocanhtve** [comment]
Many apps have issue with MicroG. MicroG updates are quite slow in supporting rare apps or very new apps, for example.

**Comment by jameskokoska** [comment]
> I think the issue belongs to MicroG and you should report it to them.

I agree. Additionally, since MicroG isn't a standard user environment, it's not supported by Cashew. Sorry about that! 

Keep in mind, Cashew has local backups and features that do not require Google services.

**Comment by theinhumaneme** [comment]
Okay makes sense,Thanks
