### ISSUE TITLE
[Feature Request] Total expenses/income for each day

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#178]
**Is your feature request related to a problem? Please describe.**
On the transactions page, just below the month's title is the total balance for the month. We can quickly know the current month's total balance as a result of calculating the sum of expenses and income.

How about each day? Currently, every day after having expenses as well as income, we cannot quickly look somewhere to know how much we have earned today, how much we have spent today. And the sum between them is negative or positive.

**Describe the solution you'd like**
Somehow display each day's cash flow on the trading page. For example today I have expenses like $5, $9 and $22, so there is a place to show the total $36 I spent today.

**Describe alternatives you've considered**
Displayed on the home page is also fine!

**Comment by jameskokoska** [comment]
The cash flow for the current day and all previous days is already available and listed to the right in the date banner.
