### ISSUE TITLE
[Feature Request] Split “Set Amount” into 2 separate strings.

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#179]
**Is your feature request related to a problem? Please describe.**
The string “Set Amount” is used for two different types of number input, one for money amount and one for period length. In Vietnamese it must be translated into 2 different strings, but because the original string is only one, it is difficult to translate accurately into Vietnamese.

**Describe the solution you'd like**
Add one more string “Set Amount” for easier translation into other languages.

**Additional context**
![](https://i.imgur.com/qWSvoHj.png)
![](https://i.imgur.com/prJZEoM.png)

**Comment by jameskokoska** [comment]
Added here: https://github.com/jameskokoska/Cashew/commit/4c60125d30d9f388f9d5681ac5c73a4febf058d4

**Comment by ngocanhtve** [comment]
> Added here: 4c60125

Thank you!
