### ISSUE TITLE
Adding income doesn't update the Budget section in home tab

### ISSUE THREAD

**Issue by rahulTPatil** [jameskokoska/Cashew#18]
Whenever we are adding income transactions, the budget amount will not be updated to include these new income transactions, it only gets updated in the Bank section.

Isn't that how it was supposed to work?

Version: 4.8.4 +245, db v-44
OS: Android

**Comment by jameskokoska** [comment]
Hey there! Make sure your budget is set to include income. See screenshot below. Closing issue for now.

This is also now addressed in the FAQ https://cashewapp.web.app/faq.html#budget-filters

![Screenshot_20231104_100712.png](https://github.com/jameskokoska/Cashew/assets/50821962/cb730f70-ee03-488a-a970-b93b03d74fd6)
