### ISSUE TITLE
[Feature Request] show amount overshot by

### ISSUE THREAD

**Issue by pavonismc** [jameskokoska/Cashew#180]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like that the goals section to show by how much over the target the amount I have saved is. Eg I am supposed to save $300 but I have $370 in the savings entry it should show that I went over by $70.

**Comment by jameskokoska** [comment]
Depending on the goal total type set, it will now display the amount exceeded instead of the total. Added here: https://github.com/jameskokoska/Cashew/commit/4c60125d30d9f388f9d5681ac5c73a4febf058d4
