### ISSUE TITLE
[Feature Request] Subscriptions tab for homepage

### ISSUE THREAD

**Issue by jacobgonzales20** [jameskokoska/Cashew#181]
**Is your feature request related to a problem? Please describe.**
My feature request is more for functionality.

**Describe the solution you'd like**
Would like to see the subscriptions tab, having the ability to be toggled on for the homepage

**Describe alternatives you've considered**
None

**Additional context**
Would be nice to see a subscription widget.

**Comment by jameskokoska** [comment]
Please see the attached screenshot. These tabs can be edited with a long press. You can select the subscription page as a shortcut.

![Screenshot_20240318_093830.png](https://github.com/jameskokoska/Cashew/assets/50821962/87ead6ce-49f6-42f1-b309-ccd9ab0af22e)
