### ISSUE TITLE
Need google calendar sync of the subscription as reminders

### ISSUE THREAD

**Issue by Darchiver** [jameskokoska/Cashew#183]
Today I came across an app called "timely bills" which is pretty similar to cashew . I was surprised by this particular feature and felt useful to sync the subscription reminders in google , Outlook calender by just logging in it. As cashew is already using Google drive login to sync, I thought it would be easy to sync the api of my google calendar with cashew for such features.
 -->![Screenshot_20240318_235602_TimelyBills.jpg](https://github.com/jameskokoska/Cashew/assets/121549490/b2b47ac2-eeb6-4699-b82f-9c33dae30c36)
![Screenshot_20240318_235606_TimelyBills.jpg](https://github.com/jameskokoska/Cashew/assets/121549490/cc43662b-c915-4329-9b6c-51ef8b1b43af)

**Comment by jameskokoska** [comment]
That's a great suggestion, unfortunately, calendar apps are complex in nature and out of the scope for this application.
