### ISSUE TITLE
Need support for using images instead of emojies

### ISSUE THREAD

**Issue by Darchiver** [jameskokoska/Cashew#184]
I use a lots of subscription.  But I have option to choice only a single emoji for all those subscription. In case if there is provision to add png logos of those subscription my self, or any image of that matter would be nice touch to the app. It also help to expand the possibility beyond the limited emoji available in the app or the keyboard.

**Comment by jameskokoska** [comment]
Unfortunately adding your own PNG/image files don't support cross-platform syncing. There are many provided images within the app and there are many emojis. Keep in mind, Cashew is designed in a way where each transaction is not intended to have its own custom icon. It is only meant for categorical groupings.
