### ISSUE TITLE
Change KZT currency symbolt to ₸.

### ISSUE THREAD

**Issue by TRESPSSR** [jameskokoska/Cashew#186]
It shouldn't be лв
![Screenshot_20240320-202258.png](https://github.com/jameskokoska/Cashew/assets/149768843/c954fed1-32ea-4e7f-8cc7-b7c41e52e2d2)

, because it is really inappropriate and means nothing
![Screenshot_20240320-202409.png](https://github.com/jameskokoska/Cashew/assets/149768843/e3ff3308-f1ba-4852-99f8-9514edc04377)

**Comment by jameskokoska** [comment]
Thank you for bringing this to my attention. It has been fixed here: https://github.com/jameskokoska/Cashew/commit/ae4091063fc6f9032e821613702fadbd90349dd3#diff-d3aadd468bdf0471097680e2dc34d13530c546bb283ca10ea7945d3c1038eb83L390
The update will be released when it is ready.
