### ISSUE TITLE
[Feature Request] Change/add transaction's title in bulk

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#189]
**Is your feature request related to a problem? Please describe.**

When I buy an item multiple times through multiple transactions, the title of those transactions some how, some where, not is the same. The problem is that sometimes when reviewing, I want to unify the titles of those transactions so that they are identical because they are all about the same item. What could I do besides correct each transaction individually?

Or let's say I have a lot of transactions in a long-term loan that don't have a title yet (due to import from another application, for example), and now I want to add the same title to all those transactions (my mom borrowed me some cash, for example). What could I do? Enter the title for each transaction one by one?

**Describe the solution you'd like**

Please add an option to change title when selecting multiple transactions, like the **change category/account** features (for multiple transactions) is existing.

The feature will add the same title to multiple currently selected transactions. Or fix all previous inconsistent titles to the same newly entered title.

**Comment by jameskokoska** [comment]
The ability to change the title of selected transactions has been added here: https://github.com/jameskokoska/Cashew/commit/7067b7f7be0ace81df5e5dc74802e6e3b8cd7387

Since the UI got cluttered for the dropdown menu, a new edit button appears prompting the user with options of what to edit in the selected transactions now.

**Comment by ngocanhtve** [comment]
> Since the UI got cluttered for the dropdown menu, a new edit button appears prompting the user with options of what to edit in the selected transactions now.

This is a good design change. The editing options are given a separate bottom sheet which is a good choice also. Great job! Thank you!
