### ISSUE TITLE
transaction managment ideas

### ISSUE THREAD

**Issue by krzemyczek** [jameskokoska/Cashew#19]
hi, I'm really thankful for open source app this good-looking, but it miss so many features that i'm not gonna buy pro version... yet. But here we go with my suggestion and things i miss. Many of them is in "wallet by budget bakers" which i use right now

1. split transaction  (for example. When buying bike's helmet and idk jacket in one shop. And i know that i can do it by making two transaction but it would more convenient) 

2. merge transaction. ( ex. buying a phone and week later return it on warranty. Then after you merge this two thing, in chart there should be count only sum of this two transaction [-1000$ + 1000$ = 0]. Like this because there could be only partly return like 800$ or when you split bill and get refund from your friend. [-30$ + 12$ = 18$])

3. little visual thing but when adding new transaction it would be easer if firstly user has to choose between income, expense and transaction. (Right now incomes category are mixed with expenses and for transfer you have to really wants to make it, because it's a little hidden)

4. showing greyed subscription due the day to confirm it (right now if i'm not mistaken the transaction or be automatically showing as a paid or you have to go to subscriptions panel and there choose "pay")

5. Add filters to transactions (like time range, transaction type [income, expense, transaction], category, if subscriptions etc.

yea. I think that's it for now. If you have questions and want explanations from me, go ahead. It's not a secret that i'm not native speaker. 
And I understand it's really time consuming thing and I appreciate your works regardless it's not yet a app that i could use instead of "wallet by bb"

**Comment by jameskokoska** [comment]
> 1. split transaction  (for example. When buying bike's helmet and idk jacket in one shop. And i know that i can do it by making two transaction but it would more convenient) 

From my point of view, this adds unnecessary complication. Especially when the category needs to be selected twice, and can be different. The easiest solution is to just add 2 separate transactions, since they are separate anyways.


> 2. merge transaction. ( ex. buying a phone and week later return it on warranty. Then after you merge this two thing, in chart there should be count only sum of this two transaction [-1000$ + 1000$ = 0]. Like this because there could be only partly return like 800$ or when you split bill and get refund from your friend. [-30$ + 12$ = 18$])

Again, this adds unnecessary complication. You can merge transactions manually, however I don't see a use case that makes this feature useful.


> 3. little visual thing but when adding new transaction it would be easer if firstly user has to choose between income, expense and transaction. (Right now incomes category are mixed with expenses and for transfer you have to really wants to make it, because it's a little hidden)

Income and expenses can be changed later. They are tied to the category for convenience but are not enforced. Adding more steps to the add transaction process creates clutter.


> 4. showing greyed subscription due the day to confirm it (right now if i'm not mistaken the transaction or be automatically showing as a paid or you have to go to subscriptions panel and there choose "pay")

You can disable automatic subscription payment in the settings page.


> 5. Add filters to transactions (like time range, transaction type [income, expense, transaction], category, if subscriptions etc.

Filters are already added in the search transaction pages.

Thank you for the suggestions! Hopefully, my insights are helpful and you can understand my thoughts. Keep in mind, if another app suits your needs better, you don't need to use this one. There are many great options out there.

**Comment by krzemyczek** [comment]
> > 2. merge transaction. ( ex. buying a phone and week later return it on warranty. Then after you merge this two thing, in chart there should be count only sum of this two transaction [-1000$ + 1000$ = 0]. Like this because there could be only partly return like 800$ or when you split bill and get refund from your friend. [-30$ + 12$ = 18$])
>

> Again, this adds unnecessary complication. You can merge transactions manually, however I don't see a use case that makes this feature useful.


so different example. You buy a phone and return it. after that you buy another one. Both of them for 1000$. For graphs, you spend 2000$ while you only spend 1000$. So it distorts the graphs


> > 3. little visual thing but when adding new transaction it would be easer if firstly user has to choose between income, expense and transaction. (Right now incomes category are mixed with expenses and for transfer you have to really wants to make it, because it's a little hidden)
> 
> Income and expenses can be changed later. They are tied to the category for convenience but are not enforced. Adding more steps to the add transaction process creates clutter.

So then maybe split  "Select Category" into "Income" & "Expense" would be better? Then you could easier choose right category because incomes one would be with other incomes and expenses with expenses and the numbers of clicks remain the same

> > 5. Add filters to transactions (like time range, transaction type [income, expense, transaction], category, if subscriptions etc.
> 
> Filters are already added in the search transaction pages.
I didn't look there! Thanks for info
> Thank you for the suggestions! Hopefully, my insights are helpful and you can understand my thoughts. Keep in mind, if another app suits your needs better, you don't need to use this one. There are many great options out there.

Yea and probably i will stay for now there but i will be trace your app in meantime

**Comment by jameskokoska** [comment]
> 
> 
> > > 2. merge transaction. ( ex. buying a phone and week later return it on warranty. Then after you merge this two thing, in chart there should be count only sum of this two transaction [-1000$ + 1000$ = 0]. Like this because there could be only partly return like 800$ or when you split bill and get refund from your friend. [-30$ + 12$ = 18$])
> >
> 
> > Again, this adds unnecessary complication. You can merge transactions manually, however I don't see a use case that makes this feature useful.
> 
> 
> so different example. You buy a phone and return it. after that you buy another one. Both of them for 1000$. For graphs, you spend 2000$ while you only spend 1000$. So it distorts the graphs
> 
> 

If you return a phone, you can enter a new transaction as income, or in my opinion you should delete the original payment transaction since it is no longer a purchase. This will avoid the distortion. I appreciate the example, but I don't want to clutter the app with too many options for something that can be solved in other more logical ways, albeit a bit more steps.

> > > 3. little visual thing but when adding new transaction it would be easer if firstly user has to choose between income, expense and transaction. (Right now incomes category are mixed with expenses and for transfer you have to really wants to make it, because it's a little hidden)
> > 
> > Income and expenses can be changed later. They are tied to the category for convenience but are not enforced. Adding more steps to the add transaction process creates clutter.
> 
> So then maybe split  "Select Category" into "Income" & "Expense" would be better? Then you could easier choose right category because incomes one would be with other incomes and expenses with expenses and the numbers of clicks remain the same

For now, the way I decided to do income and expenses is that it's tied to the category.

**Comment by jameskokoska** [comment]
I can consider adding an income/expense selector in the select category popup. I have added it to my list but will think about its usability for now. However, it will be tied to the category for now.

**Comment by jameskokoska** [comment]
Reworked income/expense selection in https://github.com/jameskokoska/Cashew/commit/0103dafab266a1f0ca3cab24f6f03c240327b1a5
Precisely in the `addTransaction` file https://github.com/jameskokoska/Cashew/commit/0103dafab266a1f0ca3cab24f6f03c240327b1a5#diff-454a49e5837b7b852937584398d073d50b3dd37f08e362439b7534572e939818
