### ISSUE TITLE
Bill splitter features 

### ISSUE THREAD

**Issue by Darchiver** [jameskokoska/Cashew#191]
While I was splitting the transaction made in a trip we went 2 days before with 5 friends of mine , I was 
1.**not able to select the date of the transaction** while selecting the category.So splitted the bill and the went to transaction page and say the transactions were in today's transaction. So I individually changed the date of transaction for each of my 5 friends to the date 2 days before.

So the solution could be **adding a date and time option** right at the moment of selecting the category of the total bill split.

**Comment by Darchiver** [comment]
2.**Need to select categories in each transactions i split in bill splitter** 

As mentioned in the scenario I was splitting the bills of a one day trip, I can't mention categories for each transactions I entered to split like travel expenses, food expenses, movie tickets for which I have separate categories already. So on the whole I am selecting a totally different category for such occasions to split the bill. So I can't track accurately my travel ,food, movie tickets expenses of the month as it is in a separate categories of therir own .

I know it will be tough to reflect this in the transaction page. But If there is a way of linking those transactions entered in bill splitter to their respective category to improve the accuracy of tracking the expenses I would love it.

After I split the bill , the app shows me how the bill was splitted in the notes area. So you can show me in which category it comes under in in that same notes area and no need to have  separate transactions created for that in the transaction page like shown in image ![Picsart_24-03-23_02-34-54-589.jpg](https://github.com/jameskokoska/Cashew/assets/121549490/6955d359-de29-48a7-a2de-38df709dc13f)

**Comment by jameskokoska** [comment]
Thanks for the suggestions!
I have made it so when adding the title for the Bill Splitter it will use the same prompts when adding a transaction - this supports a date and associated titles. I have also made it so when adding the loan transactions, a subcategory can be selected. Added here: https://github.com/jameskokoska/Cashew/commit/eb51c4b69f0cb7e74e69e2a8f16414677bb38051

To address #2, unfortunately the way the bill splitter and transactions work - each transaction only supports one category and subcategory. If you want to create multiple splitter transactions belonging to multiple categories, you will need to use the bill splitter multiple times.
Keep in mind the Bill Splitter is not the focus of this application either.

**Comment by Darchiver** [comment]
even though the bill splitter is not the focus , i think it has a additional potential usage like in my case . I just like considering some attention to it by you . Because transaction will not be always users personal only . Every user splits their bill with many people in their day to day life . So adding such integrated feature in an expense tracking app is a very very essential feature . i just want you to consider it to in future developments .
