### ISSUE TITLE
[Feature Request] Correct date range when searching

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#194]
**Is your feature request related to a problem? Please describe.**

When searching quickly and don't select a date range. The bottom of the search results page always shows a date range of **Jan 1, 1900 – Jan 1, 2030**. 2030 is in the future without any transactions yet. And I don't think anyone used Cashew to record a transaction in 1900. 😁

**Describe the solution you'd like**

- Change Jan 1, 1900 to the earliest time the transaction occurred in the database. Because in fact before the first transaction in the database is recorded, there is nothing to look for!

- Change Jan 1, 2030 to today, right at the time of search, right now. There is nothing to look for in the future, no deducted transactions have occurred yet.

**Describe alternatives you've considered**

- Change Jan 1, 1900 to the date of the earliest transaction in the search results.

- Change Jan 1, 2030 to the date of the latest transaction in the search results.

**Additional context**

![](https://i.imgur.com/qI1huzn.jpg)

**Comment by jameskokoska** [comment]
'All time's can now be selected in the date range popup. Added here: https://github.com/jameskokoska/Cashew/commit/7067b7f7be0ace81df5e5dc74802e6e3b8cd7387

Additionally, the UI has been reworked when a custom time range is set.
