### ISSUE TITLE
[Feature Request] Display both the day total and net total on the date banner

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#196]
**Is your feature request related to a problem? Please describe.**

Currently, I can only choose to display either net total or daily total. I'm pretty sure it's a necessity when wanting to quickly see both net total and day total information.

**Describe the solution you'd like**

Please add an option to display both instead of only being able to select one of the them as currently.

**Additional context**

![](https://i.imgur.com/sO2zxST.jpeg)

Maybe you would suggest to me that I can see such details in the all expenses page. I completely agree about that. But that forces user [me] to filter out a specific date, and have to constantly change the filter if I want to see other dates. 

Instead, displaying both the net and day totals on the date banner is convenient and doesn't require the user to make any effort.

In a long-term loan, both the net and day totals also helps to quickly grasp the amount of money we have paid that day as well as the outstanding debt balance. Of specific dates in the list, not the final result in the circle displayed at the top of the loan.

**Comment by jameskokoska** [comment]
Unfortunately the way the calculations are handled logically, only one is supported. Additionally, the UI becomes cluttered and it is difficult to display both at once that is clear and concise. Choose the option that best suits your needs. You can always quickly total a day by selecting all transactions on it. In the All Spending page, you can set your time range cycle to 1 day if you need an in-depth daily breakdown.
