### ISSUE TITLE
[Bug] Subcategory background color accidentally the same color as the Cashew accent color when adding/editing transactions

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#206]
**Describe the bug**

When adding/editing a transaction and selecting a category has a background color similar to Cashew's accent color, the selected subcategory will then also have a background color similar to Cashew's accent color thus blending in with the main category's background color.

**How to reproduce**

Add a transaction and select a main category has a similar background color to Cashew's accent color. Then select a subcategory you will see.

**Screenshots/videos**

![](https://i.imgur.com/VmXZZmr.jpeg)

![](https://i.imgur.com/h4kr59C.jpeg)

_Note_: 

The background color of the subcategory is accidentally quite similar to the background color of the main category (accidentally similar to Cashew accent color), they are almost the same and in low screen brightness conditions they blend together. Even when the screen brightness is quite high and maximum, similar background colors sometimes combine to make it difficult for my eyes to distinguish which subcategory has been selected.

**Details**

 - Device: Sony Xperia 1
 - App Version: 5.2.6+345

**Propose**

Make the border around the subcategory different from the background color of the main-category to make the subcategory stand out for more distinction. Or any other possible way.

**Comment by jameskokoska** [comment]
Improved the contrast here: https://github.com/jameskokoska/Cashew/commit/07db42aabf80916f8bb5258e2e1945143f3b6a55

![Screenshot_20240402_200817.png](https://github.com/jameskokoska/Cashew/assets/50821962/cfb5b1c8-22f9-46c4-9559-30512a9fb575)

![Screenshot_20240402_200842.png](https://github.com/jameskokoska/Cashew/assets/50821962/0cf01bd6-ab0f-4807-b2b3-ee5680eaf9d1)
