### ISSUE TITLE
Cashew pro lifetime option issue

### ISSUE THREAD

**Issue by lalisawhiteheart** [jameskokoska/Cashew#207]
**Describe the bug**
Cashew pro lifetime is not reflected on iOS devices 

**365437How to reproduce**
Downloaded the cashew app on android device (Samsung a32 running oneUI 5.1)
Purchased the cashew pro lifetime using the in app purchase method 
Downloaded the cashew app on iOS device and the data are synced from android to iOS and vice versa 
But the cashew pro lifetime option is not reflected in the app and shows a option to buy the same app again via iOS store

**Screenshots/videos**
[Screenshots/videos are always helpful]

**Details**
 - Device:Samsung a32, iPhone 12 mini
 - App Version: 5.2.7+344, db-v46

Expected Result:

should the lifetime purchase be reflected across all platform and allow the user to use all the feature , if that’s the case then the iOS store shouldn’t be showing the purchase option again in my opinion

**Comment by jameskokoska** [comment]
Unfortunately since iOS uses a separate payment method compared to Google Play, Cashew Pro would need to be purchased per device platform. Keep in mind every purchase supports me directly and the development of the application :) You can always use Cashew for free as well.

**Comment by lalisawhiteheart** [comment]
Is this applies to the Web app as well if the app is device platform specific it would be great help if the in app purchase windows says about the app dependency on specific platform billing methods aka device specific purchase 

other than that the app is good 

if possible does purchasing the app on android and creating multiple budget there 
Now after creating multiple budget in android does accessing that triggers a paywall panel when using it on the iOS app

**Comment by jameskokoska** [comment]
Syncing data of premium limitations does not trigger a Cashew Pro popup.

**Comment by lalisawhiteheart** [comment]
That’s great to hear I predominately use android for work and for personal use iOS this helps in bridging the gap 

will purchase the iOS app also in a few days (I’m a college student and used up my allowance for the month by buying cashew ) I want the app to grow more it’s great to be a supporter and see the app grow more features
