### ISSUE TITLE
[Feature Request] Add option to select first day of the month

### ISSUE THREAD

**Issue by josephpaturi** [jameskokoska/Cashew#208]
**Is your feature request related to a problem? Please describe.**
Different people get their income/Salary on different days of the month. As an user of the app , they would like to have an option to select the first day of the month. 

**Describe the solution you'd like**
In the settings menu, have an option to select the first day of the month. 
for example : if I chose 28th as first day of the month , then my calender months for reports,graphs and budgets etc will be 28th of this month to 28th of the next month and so on. 

**Additional context**
[bluecoins app](https://www.bluecoinsapp.com/settings/date-settings/) has this feature and very interested to switch to your lovely app

**Comment by jameskokoska** [comment]
This feature already exists. You can set a custom cycle and select the start date to any day of the month. See screenshot:
![Screenshot_20240403_100238.png](https://github.com/jameskokoska/Cashew/assets/50821962/46a334ea-9535-4d6d-b8b6-28f51af24c7f)
