### ISSUE TITLE
[Feature Request] Support for Indian number system

### ISSUE THREAD

**Issue by Abhijeet-AR** [jameskokoska/Cashew#210]
**Is your feature request related to a problem? Please describe.**
[A clear and concise description of what the problem is. Ex. I'm always frustrated when...]
I'm used to Indian Number System and it's confusing to see the numbers in international Number System.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
I'd like to see an option in Number Format setting to toggle to Indian Number System.

**Describe alternatives you've considered**
[A clear and concise description of any alternative solutions or features you've considered.]
I tried using short number format but I'd still be comfortable with Indian Number system for easy mapping in my mind.

**Additional context**
[Add any other context or screenshots about the feature request here.]
Refer this for more context: https://en.wikipedia.org/wiki/Indian_numbering_system

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating feature requests. Duplicates will not be addressed again.**
Not all feature requests will be considered. This budget app was created with careful thought given to each feature's usability and prevention of feature overload. As you use the app, you will discover possibly related useful features and that may not be obvious right away. 
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jameskokoska** [comment]
Cashew uses the device's locale to determine the number system. If you believe your current locale isn't supported, please file an issue with the Flutter repository.

**Comment by Abhijeet-AR** [comment]
Can we support an override for it? ([link](https://github.com/jameskokoska/Cashew/blob/1c6fd3d09c5d536054320c08811ea1a92966e827/budget/lib/functions.dart#L203))

**Comment by jameskokoska** [comment]
Unfortunately this creates usability complications. Apps should use the default system locale.
