### ISSUE TITLE
Cashew clone on Play Store

### ISSUE THREAD

**Issue by ch3thanhs** [jameskokoska/Cashew#211]
I found a clone of this app on the Play Store with ads - https://play.google.com/store/apps/details?id=work.mywild.xpense

The developer's apps are all just clones of other open-source projects with AI generated app icons.

The dev's GitHub - https://github.com/djacidfx

**Comment by ngocanhtve** [comment]
I just tried installing that clone app and saw that he priced the premium even more expensive than Cashew and especially claimed to be the main developer, eliminating all other credits.

**Comment by jameskokoska** [comment]
The unfortunate world of open source. Really appreciate you letting me know and finding this. I can file a formal report through the Google Play Console. Would appreciate it if you can do is report it as impersonation.

**Comment by ngocanhtve** [comment]
> Would appreciate it if you can do is report it as impersonation.

I just did that.

**Comment by ngocanhtve** [comment]
![](https://i.imgur.com/dULW6qW.png)

He is very stubborn!

**Comment by ngocanhtve** [comment]
> Please keep the issue open so that others who visit the repo can notice and report it.

I also think should keeping this issue so that those who follow this project know and can give a report to the Google Play Store so that Google can pay attention.

**Comment by ch3thanhs** [comment]
I just checked if the app was still up and now they're claiming to be the 'lead developer' in the Play Store screenshots.

<img src=https://github.com/jameskokoska/Cashew/assets/76928501/e4606edc-44ec-439d-9aa9-0a01df25ddad width=50%>

**Comment by ngocanhtve** [comment]
> I just checked if the app was still up and now they're claiming to be the 'lead developer' in the Play Store screenshots.

Exactly, I installed and tested that so I had a verbal battle with him. In particular, I discovered that the Vietnamese translation I made for Cashew also appeared identically in his application, leading to me being quite certain that he stole the source code from Cashew very closely.

**Comment by ch3thanhs** [comment]
I just checked, the app seems to be removed.

**Comment by ch3thanhs** [comment]
The developer's account is suspended.

**Comment by jameskokoska** [comment]
Thanks for letting me know, and there are many more I’m aware of too. Unfortunately, it’s a fight I cannot win. (See https://github.com/jameskokoska/Cashew/issues/725#issuecomment-3702499095)

The only thing that can be done is reporting it on the Google Play Store or leaving a poor review to discourage the use of copycat apps.
