### ISSUE TITLE
[Question] Where is database stored in google drive?

### ISSUE THREAD

**Issue by Abhijeet-AR** [jameskokoska/Cashew#213]
**Describe your question**
[Enter a clear and concise question about a feature or anything related to the app]

I'd like to automate some stuff and create transactions through API. Since Cashew is a server-less application, I'm trying to figure out a way to achieve this. One idea I got is that I'll create an API myself, get the database from the drive, modify and put it in the drive (as latest version). But when I tried finding the database file in the google drive, I couldn't find it. Can you please help me out here. Any suggestion/help is much appreciated.

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating questions. Duplicates will not be addressed again.**
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jameskokoska** [comment]
Any connected app data is not available to be viewed by users using Google Drive. This is to ensure app data does not get tweaked with. If you need to download a backup stored on your drive, Cashew allows you to download these backups within. You can only remove all your app data through Google Drive management, not view it (A quick Google can guide you through the deletion process if needed)

If you want to automate things, take a look at the App Links API that Cashew supports. The documentation can be found in the README

**Comment by Abhijeet-AR** [comment]
I did think of it but it would require us to logged in right?

Do you have any idea if it's possible to authenticate with google and get the app data out? I mean how does google allow this operations? What does it require to say that this user can access this data?
