### ISSUE TITLE
[Feature Request] More automatic backup frequency options

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#215]
**Is your feature request related to a problem? Please describe.**

While I was editing, Cashew hadn't made the latest backup yet because of some unexpected incidents, like having my phone snatched on the subway or dropping my phone into the river. I won't get the latest edited data.

**Describe the solution you'd like**

Please add more options for automatic backup frequency, for example, hourly, minutely, or more optimally, automatically backup when any new transactions are added or any small modifications.

**Describe alternatives you've considered**

Cashew can now swipe down on the homepage and transactions page for instant synchronization across devices.

Some users, like me, only use Cashew on one primary Android device because entering transactions on a primary device that always provides maximum efficiency. I don't want to waste time using Cashew on the web, and I don't have an iOS device. Therefore, I won't use the swipe-down to sync feature; I want that swipe-down action to be used for creating a backup with the latest data.

So, please add a function toggle option between sync or backup for swipe-down action. So that I can choose to have Cashew perform a backup each time I swipe down on the home page and transactions page.

**Comment by jameskokoska** [comment]
Cashew will automatically create a sync backup every time the app is launched (or force refreshed). The auto backup frequency check will also only occur when the app is launched. Because of this, a 'sync' backup for your device is always kept up to date immediately (when the app is launched or force synced). Backups are primarily used a restoration point, while the sync backup can be used for immediate data change restoration (since it syncs everytime the app is launched - unless sync is disabled).

**Comment by ngocanhtve** [comment]
> Because of this, a 'sync' backup for your device is always kept up to date immediately

Do you mean sync backup is the latest backup and always the latest data? If so, then I have got the purpose of the feature and got my wish. Thanks for the explanation!

**Comment by jameskokoska** [comment]
> > Because of this, a 'sync' backup for your device is always kept up to date immediately
> 
> Do you mean sync backup is the latest backup and always the latest data? If so, then I have got the purpose of the feature and got my wish. Thanks for the explanation!

Yep! Everytime a sync is made (everytime you open the app or force sync - if sync data is enabled), it contains the latest data.
