### ISSUE TITLE
[Feature Request] UI Enhancement on Transactions Module

### ISSUE THREAD

**Issue by 8227846265** [jameskokoska/Cashew#217]
**Is your feature request related to a problem? Please describe.**
Hello, please consider optimizing the UI for the Transactions module concerning `Subscriptions` and `Scheduled` transactions.

Currently, I have about 15 recurring monthly transactions listed under `Subscriptions` and `Scheduled` and there's no easy way to hide them without affecting something. 

Plus upcoming transactions are always pinned on top of the transaction list making the process of reviewing newly added records a problem since I have to scroll down past the upcoming transactions to see them.

Scenario:
1. If I use the `Default` filter. For some odd reason, the expense value is different with and without the `Default` filter enabled
2. Additionally while `Default` filter is enabled. Past paid `Subscriptions` and `Scheduled` transactions disappear

**Describe the solution you'd like**
1. I'd like the upcoming `Subscription` and `Scheduled` transactions to be grouped in a dropdown. When I click on the dropdown, the upcoming transaction list will appear on the transactions. Like a "Hide/Show" button.
2. While the past paid `Subscription` and `Scheduled` transactions will appear as normal.

**Comment by jameskokoska** [comment]
Can you please be more specific on which page this poses an issue for you? From a usability standpoint if a transaction should be in a list, it doesn't make much sense to 'hide it' if it belongs in a list. Closing issue for now until more details are identified.

**Comment by 8227846265** [comment]
@jameskokoska It's on this page:
![image](https://github.com/jameskokoska/Cashew/assets/66582769/b43a063b-ab6c-49af-8357-7d75cb325e7c)

I have 10 scheduled transactions and 2 subscription transactions recurring monthly and every single time I look at the `Transaction` page. These 12 upcoming transactions are pinned on top until their payment date.

Hence, I have to scroll down every day just to see my recent and past paid transactions,

And after a month has passed. These 12 upcoming transactions are back on pinned top of the next month's cycle.

Since I know these transactions and their date of payment. It would be better to have them hidden until the time they are paid.

If I need to see them, I can just toggle `Show` to show all the upcoming transactions.

**Comment by jameskokoska** [comment]
Ah okay that makes sense, I can look into collapsing them into a separate section - this has been on my to-do list for some time

I would appreciate it if you didn't mention my username too. I receive all updates on this repository already so it becomes a double ping.

**Comment by jameskokoska** [comment]
Added here: https://github.com/jameskokoska/Cashew/commit/87bdb78a2688de3fde4e31d900121ee155aec213
