### ISSUE TITLE
[Feature Request] Do not automatically decide on cash flow for new transactions that want to add to the loan

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#218]
**Is your feature request related to a problem? Please describe.**

Usually when I add a transaction, the usual order is to press the + FAB button. A bottom sheet pops up to enter title, description, category, then swipe the bottom sheet down to enter the detaile transaction entry page. At this time, I would choose to add a loan.

When I want to add a positive cash flow transaction (borrow more) then I will select a “borrowed” category, this is the income category I created previously. This means that now on the add transaction page, the amount entered is in the income tab.

And when I continued to choose a loan (for which I still owed some money) for this transaction, the cash flow suddenly changed to negative, whereas I want to enter a positive cash flow transaction and have actually selected a income category before.

One thing I realized is that Cashew will automatically record every transaction I enter on that loan as a repayment transaction (Paid tab on the left) until the loan is completely paid off. This makes it difficult for users, they will not always add a repayment transaction, they can borrow more so they will add an additional borrowing transaction. Cashew automatically change transactions into repayments, sometimes without users paying attention, causing the entered transaction to have the wrong cash flow.

**Describe the solution you'd like**

Let the selected income or expense category determine the loan's cash flow when selecting a loan for the transaction to be added.

This means that when I have chosen an income category, then I choose a loan, Cashew must understand that it is an additional borrowed amount (Collected tab on the right). This means that the cash flow is positive, not automatically changed to a negative cash flow.

**Comment by jameskokoska** [comment]
There is a purposeful disconnection between categories income/expense selection when adding to a loan. The loans default should take presidency over the income/expense of a category because the income/expense of a category is no longer labelled as such. The user can understand by seeing the opposite polarity initial transaction, they can always add an extra amount increasing the total.

For now this is an intentional usability design.

**Comment by ngocanhtve** [comment]
> The user can understand by seeing the opposite polarity initial transaction, they can always add an extra amount increasing the total.

Why create confusion to force users to get off their butts to resolve that confusion?

As show above, Cashew leads users in the order of entering title, description, and category, which results in the user actively selecting a positive cash flow category, ultimately, Cashew arbitrarily changing to negative cash flow is disrespectful, regardless of the intentional usability design reasons.
