### ISSUE TITLE
[Feature Request] Use +/- before the amount instead of an arrow

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#219]
**Is your feature request related to a problem? Please describe.**

Currently, cash flow uses arrows next to the left of the numbers to identify. Quickly scrolling through the transaction list, homepage or loans, it is actually difficult to see cash flow immediately.

**Describe the solution you'd like**

Please use +/- signs instead, these 2 signs help our eye see the difference immediately, faster than the existing small arrow.

**Comment by jameskokoska** [comment]
Currently the transaction amounts are designed to show an arrow. There are no plans to change this, it is part of the design.

**Comment by jameskokoska** [comment]
Net total colors have been added as a debug flag: https://github.com/jameskokoska/Cashew/commit/50ec5e9e0da00d4de337eee94344ef76df763069

**Comment by HappyBear-btc** [comment]
Hi I see the new version is up (kudos! great work!) but the colors didn't update.
