### ISSUE TITLE
Ability to add goals to balance tranfers

### ISSUE THREAD

**Issue by subhashay** [jameskokoska/Cashew#22]
Currently there is no option to add goals to balance corrections as in when it is entered.

The use case is, let's say, I have one account for savings and any tranfers to this account, I  would like to add savings/emergency funds goal to this transaction.

Currently the workaround is to manually add goals once the transaction is added but it would be nice if I can add it as in when I do tranfer balance.

**Comment by jameskokoska** [comment]
Since transfers create 2 transactions (transfer in and transfer out) adding these to a goal automatically will always result in a net 0. Therefore, it's better the user adds it to a goal after it has been created.
