### ISSUE TITLE
Supabase - Another way to store the data

### ISSUE THREAD

**Issue by mrmm** [jameskokoska/Cashew#220]
**Is your feature request related to a problem? Please describe.**

The main reason to propose this is that there is no way to share access to the budgets, transaction, and their management with another person without sharing the same email (as the data is stored in Google Drive)

**Describe the solution you'd like**
Using a central database (like Supabase) will allow the possibility to have the data centrally stored somewhere where it could be accessed by another person while not needing any backend server. As Supabase RBAC can do the trick.

**Comment by jameskokoska** [comment]
There are no plans to support sharing of transactions other than the method you have described. Syncing and sharing data with multiple users not only creates security concerns, but adds major complexity.

**Comment by jameskokoska** [comment]
This has already been addressed here: https://github.com/jameskokoska/Cashew/issues/61
