### ISSUE TITLE
[Bug] Cycle period cannot select past month

### ISSUE THREAD

**Issue by wesleywerner** [jameskokoska/Cashew#223]
**Describe the bug**

Selecting a monthly cycle period with a start date in a previous month is not possible.

**How to reproduce**

Tap on your bank button from the home screen, then tap the date range. Select "Cycle" every 1 month and choose a day in January. The actual period calculated starts in current month instead. 

Choosing:
- 1 January reverts to 1 April 
- 5 January reverts to 5 April

**Screenshots/videos**

![ResizedImage_2024-04-13_20-31-03_2216](https://github.com/jameskokoska/Cashew/assets/551913/e66880a7-f2d2-40ec-88a4-9a52c2006718)

![ResizedImage_2024-04-13_20-28-01_2430](https://github.com/jameskokoska/Cashew/assets/551913/cacdaec3-3d91-4448-af88-ec554314a9f3)

**Details**
 - Device: Android 13,  Google pixel
 - App Version: 5.2.8 +348 db v46

**Comment by jameskokoska** [comment]
This is the expected behavior.
