### ISSUE TITLE
[Question] Android Manifest Query Packages

### ISSUE THREAD

**Issue by TempUser13** [jameskokoska/Cashew#224]
Why does your android manifest have the permission to query installed packages and it's commented out?

**Comment by jameskokoska** [comment]
I was toying with the idea of the app reading notifications to automatically add transactions. Then the user can choose which installed app's notifications to read. However, this was commented out with this feature. You can use git blame to see when this change was made in the commit history.

**Comment by jameskokoska** [comment]
Commented out permissions has been removed here: https://github.com/jameskokoska/Cashew/commit/cc1da8bb58751732caaa3e0aeefe3cb1bd809ae0
