### ISSUE TITLE
Add shortcuts for Web App for Quick Navigation

### ISSUE THREAD

**Issue by Maaaz-Shaheen** [jameskokoska/Cashew#226]
**Is your feature request related to a problem? Please describe.**
I generally don't like to use the mouse and use the keyboard for complete navigation. For browser-based navigation, I use an extension called Vimium which adds vim navigation to Chrome. However, it doesn't seem to be working on the cashew web app. 
This introduces friction which detracts me from using it. Not a dealbreaker obviously but still takes away from the experience. 

**Describe the solution you'd like**
I can think of two solutions:
1) See why vimium doesn't work on the web app and fix that issue. 
2) Add custom and simple to understand shortcuts to the website so that people are able to quickly navigate the web app.

**Comment by jameskokoska** [comment]
No plans to support web shortcuts on web or third party extensions. In the end, Flutter web apps will never be the same as a native implementation. The basic keyboard interactions are already supported. - such as number input and using the escape key to pop navigation.
