### ISSUE TITLE
[Feature Request] Add support for “Get it on Obtainium” installation method

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#228]
**Is your feature request related to a problem? Please describe.**

Installation method via Obtainium is not yet supported.

**Describe the solution you'd like**

I see that the Bura weather app has a Get it on Obtainium button that when clicked will redirect to the Obtainium app, which will download the apk from Github's release page and install, supporting update tracking.

**Additional context**

![](https://i.imgur.com/zoiKZUg.png)

**Reference**

Bura: https://github.com/davidtakac/bura

Obtainium: https://github.com/ImranR98/Obtainium

**Comment by jameskokoska** [comment]
You can manually add the app on Obtanium if you wish by using the repository link. Currently Cashew only endorses the official redistribution channels managed by myself.

**Comment by ngocanhtve** [comment]
> official redistribution channels

Obtainium is not a distribution channel that forces you to manage uploading apk to it. Have you visited Obtainium's Github following the link I provided?

Obtainium allows you to install and update apps directly from their _releases pages_, and receive notifications when new releases are made available.

The only requirement for this feature is that you will have to add a single line to the readme.md that will navigate to the Obtainium app when clicked, has nothing to do with redistribution.

You just need to visit Bura and Obtainium's Github and you will get the point.
