### ISSUE TITLE
Issue Regarding Login

### ISSUE THREAD

**Issue by ezzyshabbir05** [jameskokoska/Cashew#23]
Everytime I relaunch the app, the google login for backup says me to login again. It should stay logged in.

**Comment by jameskokoska** [comment]
What platform are you using?

**Comment by ezzyshabbir05** [comment]
Android

**Comment by jameskokoska** [comment]
Could you specify the device and Android version? Android should automatically sign the user in, once they are properly authenticated once.

**Comment by jameskokoska** [comment]
Could you also provide the steps to replicate the issue/provide a video

**Comment by ezzyshabbir05** [comment]
Launch the app, login, close the app from recents, signed out automatically

**Comment by jameskokoska** [comment]
Sorry with those instructions I am unable to replicate the issue

**Comment by ezzyshabbir05** [comment]
I will share video recording link in few mins, i am using OnePlus Nord 3, Oxygen OS 14, Android 14

**Comment by ezzyshabbir05** [comment]
Also please provide a way to get debug logs so that i can share with you

**Comment by ezzyshabbir05** [comment]
https://photos.app.goo.gl/xif9sni89THiiYUj6

**Comment by jameskokoska** [comment]
Please wait for the app to complete the login process when initially logging in. You can see it is still trying to load data from your account after login. Then after closing the app and reopening, wait a few seconds for the auto login to commence. If the settings page is loaded before the auto login process completes, the UI won't update with your logged in username. However, tapping the Login button again will not prompt for another login, as internally the user is already logged in. This login request was done automatically when launched.

If possible could you send another video? It seems the login functions fine if everything is properly awaited for. Closing issue for now.
