### ISSUE TITLE
[Bug] Net Worth displays incorrect transaction amount and only counts the first three accounts

### ISSUE THREAD

**Issue by saamdotexe** [jameskokoska/Cashew#233]
**Describe the bug**
The "Net Worth" Section displays different (and incorrect) data based on the page you're in.

**How to reproduce**
My Accounts setup is as follows (I'll list only transaction amounts due to privacy)

A - 8 transactions
B - 889 transactions
C - 37 transactions
D - 526 transactions
E - 1 transactions
F - 4 transactions

- **Home**
The amount of money is exactly equal to the sum of the first three accounts.
The number of transactions displayed equals to the sum of the first 3 accounts in the list, **minus one**.
Should be **934** but it's **933**

- **All Spending (When clicking on the net worth card)**
The amount of money is equal to the sum of all the accounts, to the cent.
The number of transactions is **1456**, but should be **1465**, 9 short of the total transactions number.

**Additional notes**
I've checked settings, the account settings, filters etc. But couldn't find anything that suggests something i did on my end. I guess the expected value displayed on the main page should be the sum of all the accounts after all.

This behavior is present both in the Web App and the Android App.

**Comment by jameskokoska** [comment]
Hi there! Without more information it's difficult for me to figure out where the problem lies. Consider sending your data file if you wish to my email and I can look into it further. There can be many factors. For example, ensure that the homepage net worth widget includes all accounts. Closing issue for now unless more information is provided.

**Comment by jameskokoska** [comment]
Keep in mind that using the account transaction amount totals includes all transactions in that account. In the net total, 'unpaid' transactions are not counted towards the total transactions number and net total itself. This may be where the discrepancy is.

**Comment by saamdotexe** [comment]
I found the culprit.
The only thing I didn't think to do was long-pressing the card of the net worth, the last three accounts were unselected...
Sorry for wasting your time.

**Comment by jameskokoska** [comment]
No worries! Glad it's all sorted.
It's just difficult to identify the issue with the given information. I should however look into keeping consistent total transaction numbers, such as the net total including unpaid transactions in the number of transactions count.

**Comment by jameskokoska** [comment]
Unpaid transactions will be included in the transaction total count. Added here: https://github.com/jameskokoska/Cashew/commit/6b0b7c6e982dff5999f334485c1f3c19c996ee84
