### ISSUE TITLE
[Feature Request] Add option to differentiate Expense and Income in CSV files

### ISSUE THREAD

**Issue by Rafee-M** [jameskokoska/Cashew#234]
**Is your feature request related to a problem? Please describe.**
Currently when importing a CSV file you can't specify a transaction as income or expense. All of the transactions get set as income.

**Describe the solution you'd like**
Ability to select fields from the CSV files to classify a transaction as a expense or income for expense management apps that support. It would make importing over much easier.

**Describe alternatives you've considered**
Manually setting respective transactions as expenses (would take a lot of time depending on the number of transactions)

**Comment by jameskokoska** [comment]
As shown as an example in the provided CSV templates, expenses are negative amounts in a CSV. Please refer to the CSV template provided within the application.

**Comment by Rafee-M** [comment]
Indeed, the issue was the with the CSV file I was exporting from another app. It didn't have negative amounts for expenses. I'm linking this [python script](https://github.com/FosRexx/paisa-to-cashew) here in case someone has problems moving CSV from Paisa to Cashew or other apps.
