### ISSUE TITLE
Sorted Long Term Loans

### ISSUE THREAD

**Issue by Umang-Vadadoriya** [jameskokoska/Cashew#235]
**Is your feature request related to a problem? Please describe.**
When I look for long-term loans, I wonder if it will be a nice addition to the app if it's sorted by how much the amount has left.

**Describe the solution you'd like**
We can add a sort functionality to long-term loans to sort it out by remaining amount-wise.

**Describe alternatives you've considered**
You can consider other sorting functionalities like the latest modified transactions, remaining amount, Alphabetic Order, Etc.

**Comment by jameskokoska** [comment]
This is a great suggestion! However, I've toyed around with this idea before and I find that when an automatic order based on amount is used, it creates inconsistencies when the position changes abruptly.

For now, you can manually reorder long term loans by heading to the edit page.
