### ISSUE TITLE
[Feature Request] Possibility of adding amounts in a different currency to the account.

### ISSUE THREAD

**Issue by DrwOOx** [jameskokoska/Cashew#237]
When a new amount is added to an account configured in one type of currency, it does not allow the amount to be inserted in another type of currency and Cashew performs the conversion.

This can be useful in subscriptions (Netflix, Spotify...etc) that are paid in foreign currencies and it is the bank that performs the conversion.

I hope you can value the suggestion and implement it. Thank you.

Regards.

**Comment by jameskokoska** [comment]
Duplicate of https://github.com/jameskokoska/Cashew/issues/109
