### ISSUE TITLE
[Question] cashew pro share in different platform

### ISSUE THREAD

**Issue by lamedts** [jameskokoska/Cashew#238]
**Describe your question**
i bought the `pro lifetime` via apply app store, is this `pro lifetime` share between all platform (andriod and webapp) too? 

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating questions. Duplicates will not be addressed again.**
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jameskokoska** [comment]
Duplicate of https://github.com/jameskokoska/Cashew/issues/207
