### ISSUE TITLE
[Feature Request]Possibility to modify an existing transaction in a "transfer in/out"

### ISSUE THREAD

**Issue by FrancescoCuragi** [jameskokoska/Cashew#239]
First of all I would like to compliment you on the amazing application you created, it is super useful and user friendly!
I've started using the app recently and I uploaded all my transactions from all my different accounts. I could not find an option that could allow me to modify an existing transaction into a "transfer". I can only modify it as an income/expense.

For now the only solution I could find is to create a transaction equal to the existing one, set it as a transfer and finally deleting the imported transaction. This method is fine but it will take me ages to modify all the transfers I have.

Could it be possible to add a feature that allows you to modify transactions in "transfers"?

PS:.
I could not find this topic being discussed in previous issues, I hope I'm not posting a duplicate.

Thanks in advance for the consideration!

**Comment by jameskokoska** [comment]
Hi there, great question! To import transfers, your export source (original application) needs to be able to convert transfer transactions into single income/expense transactions. A single transfer would consist of 2 transactions, an outgoing account and incoming account transaction. This would be the universal format. Once this is done, Cashew can import the transactions. These imported transfer transactions should be under one 'category'. Now merge these transactions with 'Merge Category' into the 'Balance Correction' category within Cashew.

Note: the 'Balance Correction' category may not exist. It is automatically created when at least one transfer or balance correction is made within Cashew. So if it is missing, create a transfer or balance correction on an account.

**Comment by ngocanhtve** [comment]
> Now merge these transactions with 'Merge Category' into the 'Balance Correction' category within Cashew.

Previously, I used to select all transfer transactions (imported from the old application) then select change category and then select the “Balance Correction” category. But it's still not thorough. These transactions are not linked like direct transfers in Cashew.
