### ISSUE TITLE
New Idea: Can we have transfers ?

### ISSUE THREAD

**Issue by ayushjaipuriyar** [jameskokoska/Cashew#24]
I got this idea from another app called ivy wallet, i like your design better.
They have this another type of transaction called transfer , that is money transfer from one account to another.

**Comment by jameskokoska** [comment]
Hi there! You can transfer balances already by editing the wallet (long pressing)
![image](https://github.com/jameskokoska/Cashew/assets/50821962/8531ee6e-679d-4844-9311-0e9f318aff60)
Alternatively, on the account details page, tap the three dot menu and tap transfer balance.
![image](https://github.com/jameskokoska/Cashew/assets/50821962/691b44e5-b8ee-48c3-99bb-b499dd94f574)
