### ISSUE TITLE
Enhance Transaction Repetition Options for Specific Days of the Week]

### ISSUE THREAD

**Issue by zeradawit** [jameskokoska/Cashew#242]
As a user of the Cashew app, I’ve encountered a limitation in the current transaction repetition settings. Specifically, I need to schedule transactions to occur on specific days of the week, but the existing options don’t allow me to deselect certain days. For instance, if I choose the daily repetition, transactions occur every day of the week, which means I have to manually skip the days when the transaction shouldn’t happen. This manual process becomes overwhelming and time-consuming.

Feature Request: 
I propose enhancing the transaction repetition feature to allow users to select specific days of the week for recurring transactions. Ideally, I’d like to set up transactions to occur only on certain days (e.g., Mondays, Wednesdays, and Fridays) without having to manually skip unwanted days.

The app is perfect as it is. But every enhancement you make, just make it 100 plus!

**Comment by jameskokoska** [comment]
Great suggestion! Unfortunately this deviates from the current implementation of repetitive transactions and the way they function at the core and stored in the db. To achieve this, create a separate weekly repetitive transaction for the days you are interested in repeating for. You can also set transactions to be automatically changed to the date/time the transaction was marked: https://cashewapp.web.app/faq.html#repetitive-behavior

**Comment by zeradawit** [comment]
> Great suggestion! Unfortunately this deviates from the current implementation of repetitive transactions and the way they function at the core and stored in the db. To achieve this, create a separate weekly repetitive transaction for the days you are interested in repeating for.

Thanks That may be another alternative. I don't think the solution you mentioned may work for me, though. You might get my idea when you have many daily repetitive transactions for all days of the week except the weekends. Setting those transactions in the weekly repetition list may not be the ideal solution.
