### ISSUE TITLE
Enhance Notification Bar with Quick Action Options for Upcoming Transactions

### ISSUE THREAD

**Issue by zeradawit** [jameskokoska/Cashew#243]
**Description**:
The current version of the **Cashew** app lacks a convenient way for users to interact with upcoming transactions directly from the notification bar. To address this, I propose adding quick action buttons that allow users to perform essential actions (such as paying or skipping) without having to open the app itself.

**Proposed Changes**:
1. **Pay Button**: When a transaction is due.
2. **Skip Button**: For cases where users want to postpone a transaction.

Thanks. Keep continue your active development.

**Comment by jameskokoska** [comment]
Unfortunately the Cashew UI thread has to be running in order for the database to be updated. Therefore, the app must be opened. Cashew is quite optimized and opens quickly, so I don't see this as an issue. The UI also gives a consistent interface across platforms.
