### ISSUE TITLE
Hope to add multi-channel support [Cashew Pro].

### ISSUE THREAD

**Issue by pengweizhong** [jameskokoska/Cashew#244]
**Describe your question**
[Enter a clear and concise question about a feature or anything related to the app]
Hello. How can I support Cashew Pro if there is no international currency payment method? I'm from mainland China, thank you developer~  
   _ _ _ _________________________________________________________________
In addition, I would like to ask a question, that is, the Paisa App I used before has generated a lot of historical data. How can I import Paisa data into Cashew? Thanks
NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating questions. Duplicates will not be addressed again.**
Yes, no duplicates detected

**Comment by pengweizhong** [comment]
The above content comes from Google Translate. Some words may not be appropriate, but the general meaning should be the same.

**Comment by jameskokoska** [comment]
The payment methods supported by the app stores are the only methods accepted to purchase Cashew Pro, as they are the only purchase channel available.

You will need to export your data as a CSV. To import your data, you may need to format your CSV into a format Cashew understsnads. You can find an example of a CSV template within Cashew. To import a CSV file in Cashew: [More] > [Settings & Customization] > Import & Export, Import CSV

**Comment by pengweizhong** [comment]
Thanks I'll try it
