### ISSUE TITLE
[Bug] Security bug: App Opens Despite Biometric Failures

### ISSUE THREAD

**Issue by bassamsdata** [jameskokoska/Cashew#247]
**Describe the bug**
Hello,
Security concern: When attempting multiple failed biometric scans, the app displays a message indicating biometrics failure but ultimately opens normally.

Subsequently, after the biometric failure and app opening, the biometric lock automatically deactivates in the settings.

**How to reproduce**
1. Activate biometrics.
2. Attempt multiple biometric scans with an unregistered finger.
3. Wait for the message indicating biometric failure but refrain from pressing cancel.
4. The app will open and display the following message with app opening normally.

**Screenshots/videos**
![Screenshot_20240430-090804](https://github.com/jameskokoska/Cashew/assets/105807570/d85b5482-eaf0-4953-8801-d8c3c1320538)

**Details**
 - Device: Galaxy S10
 - App Version: v5.2.9+358, db-v46

**Additional notes**
Thank you for this amazing app.

**Comment by jameskokoska** [comment]
Hi there! This is an intentional design decision. If there is a biometric error the app will open and since the API does not provide any more information there is no way to tell whether biometrics are just inaccessible or errors due to force. This is because say a user restores a backup onto a device that does not support biometrics/the users biometrics on their device is broken they will have no way to recover and open the application. The biometric lock is not used to protect the app in any way necessarily, just to add an extra layer of protection. The main layer of protection would be the initial devices locking system.

**Comment by jameskokoska** [comment]
This issue arises from fixing this issue: https://github.com/jameskokoska/Cashew/issues/139

**Comment by bassamsdata** [comment]
Thanks for the prompt reply, 

> just to add an extra layer of protection. 

well, I'm not convinced that this is an extra layer of security if it's easily bypassed. It gives us a false sense of protection.

> there is no way to tell whether biometrics are just inaccessible or errors due to force.

I'm not entirely sure how Android APIs work, but why do other similar apps function flawlessly with biometrics? I've read the issue https://github.com/jameskokoska/Cashew/issues/139 but I'm unsure why the app initially requested biometrics when the user hadn't activated this option.

> The biometric lock is not used to protect the app in any way necessarily

Would you please consider displaying a message when the user activates biometrics, stating that the main protection lies in the device's security features? I believe this would be a reasonable compromise.

I'm suggesting this because security should be the top priority for such an app, considering it registers all financial income and expenses.

Thank you again for considering this.

**Comment by jameskokoska** [comment]
It has been changed so that only when a backup is restored will biometric bypass be possible: https://github.com/jameskokoska/Cashew/commit/5317891ad8e1a234891286be816a96d2a4cae767

**Comment by bassamsdata** [comment]
Thank you for taking the time to implement this. Appreciated!
