### ISSUE TITLE
[Bug] Sync Not Working Across Multiple Devices

### ISSUE THREAD

**Issue by TheLegendaryPhoenix08** [jameskokoska/Cashew#248]
**Describe the bug**
I loggind in into two android devices at different locations with the same acocunt in Cashew and updated expenses with One Device and it's been more than an hour the other device shows everything zero

**How to reproduce**
Using Samsung One UI 6 on one phone adn Realme UI on other
**Screenshots/videos**
Privacyt Reasons

**Details**
 - Device: SMA525F
 - App Version: 13

**Additional notes**
I tried uninstalling and logging into the app twice or thrice and also tried syncing with different account between the ANDROID app and Desktop, still nothing worked.

**Comment by jameskokoska** [comment]
Without more information it is difficult to determine the issue. Please look at https://github.com/jameskokoska/Cashew/issues/118
