### ISSUE TITLE
Issue: Date format

### ISSUE THREAD

**Issue by ayushjaipuriyar** [jameskokoska/Cashew#25]
I have been trying to import data from another app and it has failed because of date, the way you are storing the date is very wrong , instead string , make it milliseconds from epoch , in that approach you can use timezone and convert the time to users timezone accordingly.

**Comment by jameskokoska** [comment]
Please consider using a CSV template to import your data. There is one provided in the app. The app reads the date properly if it is properly formatted in an excel document. There is also a custom date format available when importing a CSV.
