### ISSUE TITLE
[Feature Request] Add transaction in different currency

### ISSUE THREAD

**Issue by krpti-a** [jameskokoska/Cashew#250]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to add different currency transaction to an account. For example I can't add EUR transaction to an USD account.

**Describe the solution you'd like**
I would like to be able to set the currency for new transactions and recurring payments. It would be convenient and I would hugely appreciate this feature!

**Describe alternatives you've considered**
Currently only transfers make it possible to specify different currencies.

**Additional context**
Nothing

**Comment by jameskokoska** [comment]
Duplicate of https://github.com/jameskokoska/Cashew/issues/109
