### ISSUE TITLE
Clipboard Support To Long Term Loans

### ISSUE THREAD

**Issue by Umang-Vadadoriya** [jameskokoska/Cashew#251]
**Is your feature request related to a problem? Please describe.**
I'm suggesting that I'll be a great addition to the app if we can share our long-term loans with others.

**Describe the solution you'd like**
We can implement something like copying all transactions or selected transactions of a particular long-term loan.
So we can send them this is how much you owe me. 

**Describe alternatives you've considered**
This Idea is not perfect any improvements are welcome from your side the only criteria is we could show or paste the transaction and the amount that they have to pay back.

**Additional context**
The clipboard could look like this
Subway Lunch - 300
Dominoz - 250
You Owe Umang = 550

**Comment by jameskokoska** [comment]
Because long term loans are not just for owed money it's difficult to determine a format that makes sense for sharing. You can long press the total amount to copy it to your clipboard already.

**Comment by Umang-Vadadoriya** [comment]
What do you think about coping selected transaction title, amount, and total amount of the selected items?
Don't you think that's way more easy to share when you want to share it with someone via other texting apps?

**Comment by jameskokoska** [comment]
I like the idea, not going to advertise it as 'sharing' since its more of a copy details/summary to clipboard feature. It has been added so that when you tap the transaction count in the selected transactions app bar it will 'share' a list of transaction details. If you long press it will copy the details to clipboard. 

![image](https://github.com/jameskokoska/Cashew/assets/50821962/baea1def-2395-4507-8af8-abe5fc854da1)

**Comment by Umang-Vadadoriya** [comment]
Sorry James but I don't know why,
Couldn't replicate it.
Can you help me further?

**Comment by jameskokoska** [comment]
Are you talking about not being able to use the feature? The feature is not released, only available in the code right now. Releases roll out over periods (I actually did update the GitHub builds though, so you can get it there)

**Comment by Umang-Vadadoriya** [comment]
Ok, Cool Thanks For it.
And is it only available in the transaction section or everywhere?

**Comment by jameskokoska** [comment]
Any transaction selection you make, it will be available in the top selected transactions bar

**Comment by Umang-Vadadoriya** [comment]
Yey It's Cool,
So far loving your work.
Thanks A Lot. 🥂
