### ISSUE TITLE
[Feature Request] Need an option to choose "Quarterly" as time period for my Subscriptions

### ISSUE THREAD

**Issue by NinjaGobbler** [jameskokoska/Cashew#252]
I have certain subscriptions that charge me on a quarterly basis, but when I attempt to add it to the app it does not have that option.

Currently as a workaround I could only do the math in calculator and make it monthly. But this is not very helpful and accurate with respect to how its actually done. 

If you can actually even add an option to add a custom duration, that would be best and flexible for user to decide on the duration.

**Comment by jameskokoska** [comment]
You can set a repetitive transaction to repeat every 3 months, which is the quarterly time period.

![Screenshot_20240501_104656.png](https://github.com/jameskokoska/Cashew/assets/50821962/7cd0ce54-6492-4183-bfdb-08d7665e8238)
