### ISSUE TITLE
[Question] How to View all the transactions at once?

### ISSUE THREAD

**Issue by TheLegendaryPhoenix08** [jameskokoska/Cashew#253]
**Describe your question**
Currently , it shows only upon monthly basis, I want to see all the income and expenses from Year To Date, how can I?

**Comment by jameskokoska** [comment]
You can press the 'Search' button in the top right corner of the Transactions page to view a list of all transactions. Alternatively, on the homescreen transactions list, you can tap 'View All Transactions' at the bottom of the list.
