### ISSUE TITLE
[Feature Request] Automatically Sync Whenever A Transaction is added or modified

### ISSUE THREAD

**Issue by TheLegendaryPhoenix08** [jameskokoska/Cashew#254]
**Is your feature request related to a problem? Please describe.**
I so much annoying to just pull down everytime so that the transaction also appear to my co-manager in real time, it would be great if it automatically sync itself whenever transaction is add and also auto sync Evey minute so that when opened on another device, it get synced without have to pull down again and again.
**Describe the solution you'd like**
I really love this app as this is the only one in the market with good UI and sync support as I have to share a compelete details of the expenses and income to my colleagues in real-time, but the pull down to sync just destroys the ease of use, please take this into your consideration 

**Describe alternatives you've considered**
There are no alternatives which are as good as Cashew and can fit my usage

**Additional context**
Thanks for making it open-source 

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating feature requests. Duplicates will not be addressed again.**
Not all feature requests will be considered. This budget app was created with careful thought given to each feature's usability and prevention of feature overload. As you use the app, you will discover possibly related useful features and that may not be obvious right away. 
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jameskokoska** [comment]
Sorry this has already been addressed in your previous issue: https://github.com/jameskokoska/Cashew/issues/248

As mentioned, please see: https://github.com/jameskokoska/Cashew/issues/118

Please do not duplicate topics that have already been addressed.
