### ISSUE TITLE
[Question] Possible To Sync App Settings As well? Such as Home screen layout,  and ither options 

### ISSUE THREAD

**Issue by TheLegendaryPhoenix08** [jameskokoska/Cashew#255]
**Describe your question**
[This would be very much useful as I would not have to configure the settings for each and every device, 

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating questions. Duplicates will not be addressed again.**
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jameskokoska** [comment]
To load settings into another device, consider restoring a backup of your data. Backup restoration will load all data, including settings.

Settings are not synced. Certain users may want different preferences per device.
