### ISSUE TITLE
[Feature Request] Add an option to configure the default selected date for every new transaction

### ISSUE THREAD

**Issue by irman** [jameskokoska/Cashew#257]
**Is your feature request related to a problem? Please describe.**
Currently, whenever we create a new transaction, it defaults to the current date. Most of the time, when I'm doing tracking, it'll not be instantly or on the same day. 

**Describe the solution you'd like**
It would be great to have an option where it would remember the date of the last created transaction. I don't even mind if this date value being reset daily or some of the time.

**Describe alternatives you've considered**
The problem forced me to keep selecting the date for previous transactions. Or using the duplicate feature, this also costs few extra clicks.

**Additional context**
The MoneyLover app has this feature and I'm migrating over. Thanks!

**Comment by jameskokoska** [comment]
The proposed solution is somewhat counterintuitive. Currently, you can select multiple transactions and update the date for all selected transactions. This workflow is more intuitive.
