### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by offline136** [jameskokoska/Cashew#259]
**Describe your question**
 I have a lock on the Cashew App. When I tried to open the web app, it was also locked without any option to unlock it. All it shows is "There was an error using the device's biometrics. Please check your system settings"
Please suggest to me how to fix this. 
Thank you

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating questions. Duplicates will not be addressed again.**
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jameskokoska** [comment]
Hi there, the fix is now deployed to the web app. Please ensure you force refresh the page (ctrl + refresh button) to get the fix
