### ISSUE TITLE
[Feature Request] Enable number of days for future transactions on the trading/transaction tab

### ISSUE THREAD

**Issue by cpasoft** [jameskokoska/Cashew#261]
It would be great to have the same option to mark future trading days as in the home page trading widget in the trading tab.

![imagen](https://github.com/jameskokoska/Cashew/assets/29692062/42bd4894-cad9-4978-a66c-1ee6b9b48d14)

**Comment by jameskokoska** [comment]
The transactions tab will always show the full range of dates respective. For example, May will always show all May transactions. The homepage list is an 'at a glance' list of transactions. To fix the issue where too many upcoming transactions would clutter the lists, they can be collapsed.

**Comment by cpasoft** [comment]
If you like, I can open a new topic/suggestion with this new idea. I don't know if this is necessary

**Comment by jameskokoska** [comment]
No worries, I can look into changing it to 3. Let me first check to see if this is an appropriate amount. Do you have any screenshots to help support the UI clutter issue on your end?

**Comment by cpasoft** [comment]
> No worries, I can look into changing it to 3. Let me first check to see if this is an appropriate amount. Do you have any screenshots to help support the UI clutter issue on your end?

Of course, here you have a sample with 4 future transactions:
![imagen](https://github.com/jameskokoska/Cashew/assets/29692062/107102ea-9d2a-4df8-8229-8f7b1c88e552)

I would change it as soon as there are more than 1 or 2. Another option is to make this number user configurable, like the transaction list on the home page.

**Comment by jameskokoska** [comment]
Changed to 3 or more here: https://github.com/jameskokoska/Cashew/commit/be4769aeb48fe2a86a820c65476e394b5723bec7
