### ISSUE TITLE
[Question] Sorting Transaction by Amount

### ISSUE THREAD

**Issue by sonvertb19** [jameskokoska/Cashew#262]
Hi,
Is there an option to sort the transactions by their amount?

In the monthly transaction view, I often require to view the entries that I have spent the most on.

**Comment by cpasoft** [comment]
I don't think so. It would be a good improvement to add sorting options, for sure...

**Comment by jameskokoska** [comment]
The way Cashew works internally requires all transactions to be sorted chronologically. If you need to find the specific cost of transactions, or see the highest amount use the provided filtering system.

**Comment by jameskokoska** [comment]
This has been added in the beta. You can now sort transactions by amount in the Search Transactions list page and other fields.

See #725 for Beta Testing instructions and information

![image](https://github.com/user-attachments/assets/f59d1be3-ac17-46a0-a244-4e3de93c71be)
