### ISSUE TITLE
[Feature Request] Increase the decimal precision limit

### ISSUE THREAD

**Issue by Alexuty07** [jameskokoska/Cashew#263]
**Is your feature request related to a problem? Please describe.**
I am unable to represent the full and true balance of my Monero (XMR) wallet due to a decimal precision limit of 10, whereas monero balances have 12 decimal places.

**Describe the solution you'd like**
Increase the limit.

**Comment by jameskokoska** [comment]
Increased to 12 here https://github.com/jameskokoska/Cashew/commit/324e08fde8a8ca1185755638f3340c49d300240f
