### ISSUE TITLE
Add transaction card status

### ISSUE THREAD

**Issue by pengweizhong** [jameskokoska/Cashew#265]
In the account list, I have an expired card. I can still see and select it when creating a new transaction (although I can ignore it), but I want to block it but not delete it (because deletion will cause all related transactions to disappear). Therefore, can this card [status invalidation] or similar functions be supported? Thanks

**Comment by jameskokoska** [comment]
Currently you cannot archive an account. However, you can hide a wallet from most homepage widgets (i.e. not pin it) and can change its order to the end of the account list.

**Comment by RijoKsd** [comment]
@jameskokoska  Still the **hide account** feature is not implemented right ?

**Comment by jameskokoska** [comment]
This has been added in the beta. You can now archive (hide) accounts.

See #725 for Beta Testing instructions and information
