### ISSUE TITLE
Allowing attachments without the need to login to google drive

### ISSUE THREAD

**Issue by akzjcrafts** [jameskokoska/Cashew#266]
Today I was sad to find out you cannot use the attachment feature without logging into google drive. 

**Describe the solution you'd like**
I am hoping you can just have attachments save as part of the rest of the saved data that is created when transactions are made. 

**Describe alternatives you've considered**
Adding the attachments to my existing cloud storage folder that holds my manually exported Cashew backups. 

**Additional context**
I don’t know if this is possible as I am not sure how other similar apps store their attachments locally but if it’s not too difficult I hope you consider it. I really love the app and already purchased the lifetime pro for iOS so if it is too difficult/not possible to implement I will just use my workaround. Thank you!

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating feature requests. Duplicates will not be addressed again.**
Not all feature requests will be considered. This budget app was created with careful thought given to each feature's usability and prevention of feature overload. As you use the app, you will discover possibly related useful features and that may not be obvious right away. 
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jameskokoska** [comment]
Due to syncing there are no plans to support attachments without Google Drive

**Comment by akzjcrafts** [comment]
Okay thank you!

**Comment by Der-Flip** [comment]
Probably making a fool of myself asking this but how is the syncing reason for the lack of attachment support when offline?
