### ISSUE TITLE
[Bug] Making a transfer recurring doesn't act right. 

### ISSUE THREAD

**Issue by Nightangel224** [jameskokoska/Cashew#267]
**Describe the bug**
When you make a transfer recurring it acts ok, but when you go to use the next recursion it starts moving things around weird and not tracking it properly in the accounts.

**Details**
 - Device: 
 - App Version: [e.g. 4.9.4+256]

NOTE TO THE SUBMITTER
Reporting bugs is important for maintaining the app. Thank you for helping make the app a better experience for all!

**Comment by jameskokoska** [comment]
Would need more details. As per my recent tests, transfer transactions are working as intended.

**Comment by Nightangel224** [comment]
> Would need more details. As per my recent tests, transfer transactions are working as intended.

The initial transfer works just fine. The issue I saw was when I went into the created transfer and made it recurring so that it showed up on upcoming. When I went to pay/deposit on the upcoming one made by the app it would not do it fully. 

Let's say I made the pay side recurring for once a week. I hit pay and it does everything it is supposed to, it transfers the money, creating a deposit transaction to go with the pay transaction, and creates a new pay action for the next week. When I go to pay on the next week it seems to just move the previous deposit transaction while still making the new pay transaction. 

Does that better explain what is going on?

**Comment by jameskokoska** [comment]
Unfortunately, I was unable to replicate the issue. The previous paid status may have gotten out of sync. Consider making your transfer transactions again and setting its type to repetitive.

**Comment by Nightangel224** [comment]
I'll try replicating it and take screenshots later. 
 
  On Mon, May 13, 2024 at 3:38 PM, ***@***.***> wrote:   


Unfortunately, I was unable to replicate the issue. The previous paid status may have gotten out of sync. Consider making your transfer transactions again and setting its type to repetitive.
