### ISSUE TITLE
[Bug] String missing in sheet to translate

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#268]
**Describe the bug**
There is an English string that does not appear in the sheet for translation.

**How to reproduce**
Access the subscriptions place

**Screenshots/videos**
![](https://i.imgur.com/5NqI0Md.png)

**Details**
 - Device: Sony Xperia 1
 - App Version: 5.2.9+366

**Additional notes**
The string is: _No subscription transactions_

**Comment by jameskokoska** [comment]
Thanks for catching this! Fixed here: https://github.com/jameskokoska/Cashew/commit/dfb8be263f6ed7c863deaf745ed4217ff2ee71ea
