### ISSUE TITLE
Getting too much extra margin for all pages heading

### ISSUE THREAD

**Issue by thesanjithkumar** [jameskokoska/Cashew#27]
![Screenshot_20231106-194648](https://github.com/jameskokoska/Cashew/assets/53137451/253d0411-ed71-46f4-ad1d-ee989da48670)

Getting too much extra margin on top of each page headings.

**Comment by jameskokoska** [comment]
It is designed that way for reachability.

**Comment by thesanjithkumar** [comment]
> It is designed that way for reachability.

Is there any way to disable it?

**Comment by jameskokoska** [comment]
A debug option has been added to force a small header. Will make it an official setting soon.
Changes here: https://github.com/jameskokoska/Cashew/commit/2bbded946bb09378d81ed18a961d641c45401f5b#diff-5613e1f1054ebef2429bc714f5fd7348b8826f34e34dc91fe75a914a72eb8e02R125

**Comment by thesanjithkumar** [comment]
oh nice, thanks for the inclusion of it in the future build.

**Comment by jameskokoska** [comment]
Option added! 
https://github.com/jameskokoska/Cashew/commit/b4ea3652ea4cf6c9424fa6b323cdd53a8b18028a
