### ISSUE TITLE
[Question] Automatically assign transactions with the same name to specific categories. It doesn't work!

### ISSUE THREAD

**Issue by domaesil** [jameskokoska/Cashew#270]
**Describe your question**
"Custom Titles: Automatically assign transactions with the same name to specific categories, saving time and ensuring consistency. These titles are stored in memory and popup when you add another transaction with a similar name."
I'm adding a transaction with the same name, but it doesn't assigned to specific categories. When I click the category, on the bottom, it says "Associated Titles" and below there is a list of titles. However, when I add a transaction with that exact title, it's not assigned to any category. What am I doing wrong?

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating questions. Duplicates will not be addressed again.**
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jameskokoska** [comment]
Hi there! You'll have to tap the title (or press 'enter/submit' in the keyboard) when it pops up when adding a transaction. See screenshots below:

![Screenshot_20240516_194114.png](https://github.com/jameskokoska/Cashew/assets/50821962/5d2405a3-050a-4d0b-b79a-4dc4e70d4cbb)

![Screenshot_20240516_194127.png](https://github.com/jameskokoska/Cashew/assets/50821962/6e16c4e8-8c87-4141-be7c-3803f260c28d)

**Comment by domaesil** [comment]
Hi, yes but it pops up with no category. Please see the
![IMG_0478](https://github.com/jameskokoska/Cashew/assets/167365484/7a8e9427-74c7-49d6-b7b6-05e3616586a2)
![IMG_0479](https://github.com/jameskokoska/Cashew/assets/167365484/08713814-007b-4002-a1a4-dd2d97d896a4)
![IMG_0480](https://github.com/jameskokoska/Cashew/assets/167365484/2f4864d0-55e9-489e-bb32-f1de8b6ea902)
 screenshots.

**Comment by jameskokoska** [comment]
Hmm it seems that some titles don't have an associated category. Can you check the [Titles] page in [More] for any titles that contain those labels? Do they have a category associated with them? There may be a big when merging categories and updating the categories of titles - was this done recently?

**Comment by jameskokoska** [comment]
To add on, the app should run `deleteWanderingTitles()` on startup so any titles that don't belong to a category. 

Try restarting the app and feel free to let me know what the result is.

**Comment by domaesil** [comment]
Ohhh when I went to more -> titles and searched for that title, there were 2 titles (exactly the same title) but one of them was category not assigned. So i deleted that one! Thank you

**Comment by jameskokoska** [comment]
Glad it's solved! I'll look into why this occurred, thanks for the info
