### ISSUE TITLE
[Feature Request] Show amount of individual subscriptions according to users choice

### ISSUE THREAD

**Issue by railw29** [jameskokoska/Cashew#271]
# Feature Request
Hello Cashew Team!

I hope this finds you well. I really like Cashew and I have got a new feature request.

This feature request is about the subscription page.

**Description of the feature:**
As a user, I would like to see the payment amount I have selected (monthly/yearly) for all individual subscriptions. 

**That means:** 
- If I select yearly subscriptions, the yearly amount of all individual subscriptions should be displayed.
  * If the individual subscription is stored as a monthly subscription , the yearly amount should also be shown
  * If the individual subscription is stored as a yearly subscription, only the yearly amount should be shown
- If I select monthly subscriptions, the monthly amount of all individual subscriptions should be displayed.
  * If the individual subscription is stored as a monthly subscription, only the monthly amount should be shown
  * If the individual subscription is stored as a yearly subscription, the monthly amount should also be shown 

---

Below there are two screenshots attached. The first one is the new view. The second one is the adusted view with an explanation.

Thank you for considering my suggestion!

# Screenshots
**This could be one possibility for what the new subscription page looks like:**
![Subscription_withoutexplanation](https://github.com/jameskokoska/Cashew/assets/170073801/18a7c1b9-2008-4626-ac79-d8c0e175f896)

**The new subscription page explained:**
![Subscription_withexplanation](https://github.com/jameskokoska/Cashew/assets/170073801/61f6edd2-e85b-416a-b208-bf4794833da6)

**Comment by jameskokoska** [comment]
This is a bit more complicated as a user can specify different term lengths such as every 2 months or every 5 years. However, the subscriptions page has already gotten overhauled already to reflect the selected term totals for each transaction, as you requested. See screenshot below:
![image](https://github.com/jameskokoska/Cashew/assets/50821962/50959c67-400c-40f6-9be1-a76b87561844)
