### ISSUE TITLE
[Bug] The edit loan button disappears

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#274]
**Describe the bug**
When all loans are hidden, the edit loan button - the button to access where to hide or show loans - will disappear.

**How to reproduce**
Go to loans, touch the pen button in the upper right corner, hide all loans.. then

**Screenshots/videos**
![](https://i.imgur.com/OQeFQiU.png)

**Details**
 - Device: Sony Xperia 1
 - App Version: 5.2.9+366

**Additional words**
Why is this a bug? Because if the user accidentally hides the last loan, they will immediately not be able to access it to reopen the loan. After all, the loan can be hidden and reopened many times.

**Comment by jameskokoska** [comment]
Intentional, at least for now. If there are no long term loans listed or displayed, the feature is 'disabled'

**Comment by jameskokoska** [comment]
Fixed here: https://github.com/jameskokoska/Cashew/commit/64e2b95072bb850d9b0db4fa949cf283aa8a9277
