### ISSUE TITLE
Option to hide (filter) accounts in the Accounts/Accounts List widget. 

### ISSUE THREAD

**Issue by anjuthanmj** [jameskokoska/Cashew#276]
**Is your feature request related to a problem? Please describe.**
I would like to have a feature to display only desired accounts on the home screen accounts/accounts list widgets. The reason is that my major saving account will have lot of money which is supposed to be used only when needed. I do not want this to be on home screen to prevent anyone from seeing it accidentally when I open the app to enter an expense. 

The net worth tile has the ability to filter out accounts which is great and I like this to be added to account tiles as well. 

**Describe the solution you'd like**
Ability to filter which accounts are shown in the accounts or accounts list widgets.

**Comment by jameskokoska** [comment]
You can select which accounts to pin to the accounts list by editing the homepage. Tap the accounts list widget of interest to select accounts. ![Screenshot_20240522_011508.png](https://github.com/jameskokoska/Cashew/assets/50821962/65e7e327-11fc-4eda-a1a3-c180887b0d28)

**Comment by anjuthanmj** [comment]
@jameskokoska Sorry if I wasn't clear. My request was not about whole list. It about filtering individual accounts in the accounts list.

**Comment by anjuthanmj** [comment]
@jameskokoska That's awesome. Thanks.
