### ISSUE TITLE
Export Data File is not working and giving an error (Screenshot and details provided)

### ISSUE THREAD

**Issue by NomanBaigA** [jameskokoska/Cashew#28]
In the settings backups section when i am trying to export data file after selecting folder its giving me error.

Tested on Android 6 and Android 9 device

Error Screenshot - 

![Screenshot](https://github.com/jameskokoska/Cashew/assets/49509445/a2edf0a5-b0ad-424e-9d9a-5f66ec72187f)

**Comment by jameskokoska** [comment]
Might be an issue with permissions. Will look into it. By chance what device are you using?

**Comment by NomanBaigA** [comment]
> Might be an issue with permissions. Will look into it. By chance what device are you using?

- App is asking for permission and i am giving it but still this issue.
- Realme C2 and Vivo V5
- Its working fine in Android 11 device

**Comment by jameskokoska** [comment]
Fixed here: https://github.com/jameskokoska/Cashew/commit/446271e249fd11fb23a734df845758e728320292#diff-00b152447cae922c0b6d68feb98e2508f57e80af45a222aea50fda76e0a2315fR11

Also bumped [file_picker](https://pub.dev/packages/file_picker) version
