### ISSUE TITLE
hours and minutes are switched in places in right to left languages [Bug]

### ISSUE THREAD

**Issue by HappyBear-btc** [jameskokoska/Cashew#283]
**Describe the bug**
minutes are displayed to the left of the hours in right to left languages.

**How to reproduce**
switch to Hebrew or Arabic add a transaction or watch any previously added txs.

**Screenshots/videos**
![Screenshot_20240601_081657](https://github.com/jameskokoska/Cashew/assets/122559990/9966c0f7-17d2-446f-9685-325d0d5b83dd)

**Details**
 - Device: Android & web app
 - App Version: v5.3.0+375, db-v46

**Comment by jameskokoska** [comment]
Fixed here: https://github.com/jameskokoska/Cashew/commit/fce9ddf65f2074d8307c0e71135a680e0b49cac8
Also improved other UI aspects for RTL locale
