### ISSUE TITLE
[Feature Request] Transfers history on account page

### ISSUE THREAD

**Issue by guit4eva** [jameskokoska/Cashew#285]
**Is your feature request related to a problem? Please describe.**
Unable to view inter-account transfers.

**Describe the solution you'd like**
It would be really useful to have a transfers page (next to Outgoing and Incoming tabs on account page) that shows all transfers to that account (from another account), along with the history graph as shown in Outgoing/Incoming. Will be amazing to have that information for accounts such as investment accounts.

**Comment by jameskokoska** [comment]
You can apply filters on the All Spending page to achieve your desired result.
