### ISSUE TITLE
[Feature Request] Add a section or indication that a loan has been cleared

### ISSUE THREAD

**Issue by Grabstertv** [jameskokoska/Cashew#287]
**Is your feature request related to a problem? Please describe.**
In the loans tab, when a loan has been paid in full/settled, it stays within the list with no indication that it has been settled. Both in one-time and long term loans. It becomes a problem overtime when settled loans pile up. You may have only 2 active loans but you will be seeing every loan from the past in the same list that do not require any action.

**Describe the solution you'd like**
There needs to be a separate section under "active" loans for loans that have been settled for archival purposes. It needs to be collapsible in a way so it does not interfere with active loans list but can be referred to quickly or searched if needed. Alternatively an archive list would also work.

**Describe alternatives you've considered**
Currently the only way to hide settled loans is to delete them entirely.

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating feature requests. Duplicates will not be addressed again.**
Not all feature requests will be considered. This budget app was created with careful thought given to each feature's usability and prevention of feature overload. As you use the app, you will discover possibly related useful features and that may not be obvious right away. 
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jameskokoska** [comment]
You can already archive long term loans by heading to [More] > [Loans] > Long Term tab > Edit Icon, and toggling the 'Eye' for each loan you would like to archive

**Comment by Grabstertv** [comment]
Oh fabulous! Not sure i missed it. However the option is still not there for one time loans so would be great if its also present there.

Thanks!
