### ISSUE TITLE
[Feature Request] Option to display total cash in and out flow (eg include loans lent) in the 'Expense & Income' tile. 

### ISSUE THREAD

**Issue by anjuthanmj** [jameskokoska/Cashew#289]
**Is your feature request related to a problem? Please describe.**
When I give a loan to someone say $50, the money actually flows out for this month until the person return it. The 'Expense & Income' tile does not count this. In transaction page banner, we can see lent amount also added to expense. Seeing total outflow for this month as of today will be more beneficial to get an idea on the expense. Idea is that until the person repay the money, it is an expense on my end at that moment. 

**Describe the solution you'd like**
Give an option to display total cash outflow in the 'Expense & Income' tile. 

**Describe alternatives you've considered**
Or provide a new tile for total cashflow.

**Comment by jameskokoska** [comment]
Within Cashew, lent money is not considered an expense. To see a total of lent money, you can enable the 'Loans' homepage widget which will total 'Lent' and 'Borrowed' transactions separately.

**Comment by anjuthanmj** [comment]
@jameskokoska Is it possible to give a new tile showing total cash flow in home screen. I see the data is already available in transaction tab. Seeing the total cash outflow is beneficial for some.

**Comment by anjuthanmj** [comment]
@jameskokoska I just noticed in 'Pie Chart' tile, there is an option to show only expense and income or 'All outgoing & Incoming' transactions. Could you please add it to the expense tile as well. I think it will be easier than creating a separate tile.

**Comment by j-perezr** [comment]
I understand your point, but, as user, I would like to see all the money that leaves my accounts, including loans.
Can you please consider giving us the flexibility by adding an option to enable it? It is already happening, in the "All expenses" going to "history" tab shows all expenses including the loans.
