### ISSUE TITLE
Currency stays when viewing goals target

### ISSUE THREAD

**Issue by ReDarkTechnology** [jameskokoska/Cashew#29]
Not sure how to explain, it's the version is on the latest one on the Google Play Store, I don't think it's supposed to act like that?

![IMG-20231108-WA0001](https://github.com/jameskokoska/Cashew/assets/53262904/0bedfd39-bba4-4046-bc47-c022b80a60e7)
![IMG-20231108-WA0000](https://github.com/jameskokoska/Cashew/assets/53262904/bb105305-babe-4e1a-a458-df77eaca1564)

**Comment by jameskokoska** [comment]
It is expected behavior, but I guess logically it should store the original currency it was created in

**Comment by jameskokoska** [comment]
Fixed here https://github.com/jameskokoska/Cashew/commit/446271e249fd11fb23a734df845758e728320292

Added new walletFk database column to objectives (goals), budgets, and budget category limits
Added conversion code between as well
You can select the currency when entering the amount for each
Defaults to primary currency on database column creation
