### ISSUE TITLE
[Bug] White line between selected transactions

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#291]
**Describe the bug**
When selecting transactions. There is a white line in the middle. If there are lines in between all transactions or no lines at all, it will be very normal. Now, the lines appear seemingly randomly.

**How to reproduce**
Selecting 3 or 4 transactions.

**Screenshots/videos**
![](https://github.com/jameskokoska/Cashew/assets/125894401/ab730712-f826-4adc-bd91-999160bc58ca)

**Details**
 - Device: Sony Xperia 1
 - App Version: 5.2.9+336

**Comment by jameskokoska** [comment]
Unfortunately this is an issue with the Flutter engine and cannot be fixed.
