### ISSUE TITLE
[Bug] Heatmap display incurs heavy performance cost

### ISSUE THREAD

**Issue by skff-err** [jameskokoska/Cashew#292]
**Describe the bug**
Heatmap display on home causes stuttering and slowdowns when enabled

**How to reproduce**
On home display, go to the menu in the upper right corner and enable heatmap display

**Screenshots/videos**
Heatmap off: Average FPS
![Screenshot_20240606_145138](https://github.com/jameskokoska/Cashew/assets/66136655/cdf44620-f3dd-4cb7-90dc-da470e9234f1)

Heatmap on: Average FPS
![Screenshot_20240606_145120](https://github.com/jameskokoska/Cashew/assets/66136655/7384bb59-f17f-4d0f-a925-43d176b293d8)

**Details**
 - Device: Samsung Galaxy A51 (SM-A515F)
 - App Version: 5.3.1 (Play Store)

**Comment by jameskokoska** [comment]
Unfortunately the Flutter engine's performance is very device specific. The Heat map has to listen to many calculations and it already has lazy loading and is optimized (i.e. the days are only loaded if displayed). If it causes performance issues I recommend to disable this homepage section
