### ISSUE TITLE
[Feature Request] Default page when launch

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#293]
**Is your feature request related to a problem? Please describe.**
When I launch the app, it always takes me to the Home page. But I rarely want to go to the Home page, I just want to go to the Transactions page immediately.

**Describe the solution you'd like**
Please add option to choose the default page I want to go to when launching the app.

**Describe alternatives you've considered**
Remembers the page opened at last launch.

**Additional context**
I want to go to the Transactions page almost all the time, only occasionally I want to go to the Home page to see a few things.

**Comment by jameskokoska** [comment]
From a usability perspective and the fact that the homepage can be customized to your liking to include a transactions list, there are no plans to support a different default page.

**Comment by jameskokoska** [comment]
After reconsideration, I may make it so the first tab can be customized to any page.

**Comment by jameskokoska** [comment]
Added here: https://github.com/jameskokoska/Cashew/commit/bfb232761aff49aa7152ce47cdc2d47756303e17
