### ISSUE TITLE
[Bug] Accidentally enabled syn while selecting transactions

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#299]
**Describe the bug**
Synchronization was accidentally activated while selecting transactions.

**How to reproduce**
On the transaction page, swipe down to see the latest transaction. Long press then swipe down quickly to select transactions.

**Screenshots/videos**
https://github.com/jameskokoska/Cashew/assets/125894401/495fd44a-5fd4-453c-abc4-684af76e96b2

**Details**
 - Device: Sony Xperia 1
 - App Version: 5.2.9+366

**Comment by jameskokoska** [comment]
Thank you for reporting this issue! It has been fixed here: https://github.com/jameskokoska/Cashew/commit/848e52e9bf5548d9f9a83cf04c7b444469d6fe89
