### ISSUE TITLE
Local Backup of App Data

### ISSUE THREAD

**Issue by TheHawaiianKoala** [jameskokoska/Cashew#3]
**Introduction**
Hello
Been using the app for the past 3 days and only found the following missing feature. Although you can export the CSV file, you cannot create a local backup. This is a big problem for those of use who do not have a google account

**Steps to Reproduce**
1. Open App
2. Open Settings
3. No Local Export/Import

**Information**
- Android Version: Graphene OS 13
- Phone: Pixel 4
- App Version: 4.4.6

**Comment by TheHawaiianKoala** [comment]
I think [this](https://github.com/jameskokoska/Cashew/commit/2d52cf3de4d6cccf241f1458e059ff0f23514d52) implement this so I guess this issue can be closed. Thanks for such a fast response

**Comment by jameskokoska** [comment]
No problem! It's still not tested fully (especially on web) and bundled in a complete release so I'll keep the issue open until then.

**Comment by jameskokoska** [comment]
Completed in https://github.com/jameskokoska/Cashew/releases/tag/4.5.1%2B212
