### ISSUE TITLE
Option to exclude transfers and balance correction from income and expense.

### ISSUE THREAD

**Issue by athuldaas** [jameskokoska/Cashew#30]
I'm currently using different accounts for bank,cash and credit cards. So whenever I make a credit card transaction and later pay it back it'll add towards my total income and expense. I would like to have an option to exclude transfers from this.

**Comment by jameskokoska** [comment]
Balance correction transactions already don't apply to income and expense totals

Please see the FAQ for a detailed explanation of the balance correction category https://cashewapp.web.app/faq.html#balance-corrections

**Comment by athuldaas** [comment]
Oh sorry. Actually for some reason all my imported balance correction entries are being added to income and expense. Might have to fix them manually.
