### ISSUE TITLE
[Bug] Title with an empty name can be added to "Associated Titles" of the category

### ISSUE THREAD

**Issue by shitcoding** [jameskokoska/Cashew#306]
**Describe the bug**
When adding some title to category's "Associated Titles" section (that should be automatically added to this category), it's possible to set an empty name of the title.

**How to reproduce**
- Select some category
- Add a title to "Associated Titles", set empty name

**Details**
 - Device: Android and web app
 - App Version: v5.3.1+379

**Comment by jameskokoska** [comment]
This has already been fixed in https://github.com/jameskokoska/Cashew/commit/d47986275207531f9c3d4339a9b1c2745b8ca7b6
