### ISSUE TITLE
[Feature Request] Adjust font size

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#308]
**Is your feature request related to a problem? Please describe.**
A dude who is my friend thinks the font is kinda big for his eyes, he wants the font to be smaller to display more information on the screen.

**Describe the solution you'd like**
Please add adjust font size feature.

**Describe alternatives you've considered**
I suggested he adjust the font size in the system settings, which he did, but that affects the entire system, which is not suitable in case he only wants to adjust it within Cashew.

**Additional context**
Any way, thanks!

**Comment by jameskokoska** [comment]
Unfortunately Cashew follows system guidelines for accessibility including font size. As you mentioned, to adjust font size it will need to be adjusted in the system settings.

**Comment by jameskokoska** [comment]
This has been added in the beta. You can now adjust the font scale.

See https://github.com/jameskokoska/Cashew/issues/725 for Beta Testing instructions and information

![Image](https://github.com/user-attachments/assets/16e63aea-f41f-426f-805e-028486df84ba)
