### ISSUE TITLE
Feature: Receipt scanning and parsing

### ISSUE THREAD

**Issue by fpfuetsch** [jameskokoska/Cashew#31]
I think a really nice feature would be to allow users to scan their receipts, analyse them using OCR, match the items with existing categories and automatically create matching transactions. This would not just speed up adding transactions itself, but would also allow to split up sums, e.g. when you buy groceries and a gift in the same store.

Have you already thought about such a feature or are you even already working on it?

**Comment by jameskokoska** [comment]
This feature was always in the back of my mind, however the complexity vs reward is not worth it. Receipts can be formatted in so many different ways and in the end, the most important number is the total. 

There are other apps out there whose sole purpose is just to analyze receipts for bill splitting. This app has no plans of implementing features of those apps.
