### ISSUE TITLE
Carry forward previous cycle balance to current cycle income.

### ISSUE THREAD

**Issue by anjuthanmj** [jameskokoska/Cashew#310]
**Is your feature request related to a problem? Please describe.**
Usually in book keeping, previous month/cycle balance is added as 'Carried Forward' which is added in the balance column. All previous apps i used for personal expense tracking had option to enable this. But Cashew doesn't seem to have this feature. If I have balance $500 from previous month and income $5000 this month, and then I spend $5100 total this month, the balance for this month shown as -100.

**Describe the solution you'd like**
Give option on settings to enable option to transfer balance of previous cycle as carried forward income and add it to income. This should be optional as some people may not need it but this should be an essential feature for an expense app.

**Comment by jameskokoska** [comment]
If you use the cycle filter for accounts, balances are already carried forward between the cycles set on that account. The account's total doesn't reset per cycle, as it is just a filter.

As for budget cycles, this is already addressed in this issue https://github.com/jameskokoska/Cashew/issues/134

**Comment by anjuthanmj** [comment]
@jameskokoska But in income tile and the cash flow summary in transactions, the carried forward amount is not added.

In the uploaded pictures, you can see i have 1975 LKR balance. In July that amount is not added as income. 
![Screenshot_20240701-142052](https://github.com/jameskokoska/Cashew/assets/26527505/0280bee7-1577-4f2f-96ea-f93746123f90)
![Screenshot_20240701-142029_1](https://github.com/jameskokoska/Cashew/assets/26527505/560c3abe-58bd-4301-91dd-28a856aa5e87)

**Comment by jameskokoska** [comment]
That total only shows the current month. To view a full total of your spending use the 'All Spending Summary' page.

**Comment by anjuthanmj** [comment]
@jameskokoska Sorry if I wasn't clear. There is a concept in accounting where the previous cycle balance is added as income to the next cycle. So if I have $50 balance last month and this month income is $5000 total income shown as 5500. Because that 500 is available for this month to spend. Two apps i used earlier had option to enable this.
