### ISSUE TITLE
[Feature Request] Archive a budget, and limitless budgets

### ISSUE THREAD

**Issue by uderbashi** [jameskokoska/Cashew#311]
**Is your feature request related to a problem? Please describe.**
I have multiple trips related to my work a year. I wanted a tag system like (Paris, May 2024) to find all the transactions related to that trip. Budgets seem to be the way these kind of things are intended to be handled. But I have two issues with them. 

1) an added budget, even after it's time has ran out, is still available to be chosen in the interface. 

2) I am tracking my spending without the intention of having a limit, but as a work necessity. So a budget without a limit (for the purpose of tagging) is something that would be beneficial for me. 

**Describe the solution you'd like**
1) the availability of choosing a budget in an expense entry is deactivated either after the time has expired on a budget, or with an option inside the budget. (I prefer the option rather than the timer) 

2) having the option to make a budget track expenses without a target (checkbox or by entering 0) 

**Describe alternatives you've considered**
1) I am not sure of any existing alternatives, as titles are tied to categories, and don't provide the overview that the budgets have. 
2) I am setting the budget on €1, and spending 20000%. It is not nice, but it's a walkaround. 

**Additional context**
None that I can think of. 

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating feature requests. Duplicates will not be addressed again.**
Not all feature requests will be considered. This budget app was created with careful thought given to each feature's usability and prevention of feature overload. As you use the app, you will discover possibly related useful features and that may not be obvious right away. 
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by uderbashi** [comment]
Sorry, I am on the phone and pressed enter and it sent the thing up. I am editing the body now.

**Comment by jameskokoska** [comment]
You can already archive budgets. See https://cashewapp.web.app/faq.html#archiving

Unfortunately there are no plans to support limitless budgets. The budget's interface all revolves around a total 'limit'. You can use the 'All Spending Summary' with a cycle as the date and time filter. This will also give you more freedom to apply any filters to your analysis.
