### ISSUE TITLE
[Bug] Shouldn't the amount available to be spent on each remaining day of a budget cycle account for upcoming payments?

### ISSUE THREAD

**Issue by ea-ooe** [jameskokoska/Cashew#313]
**Describe the bug**
Underneath a budget's progress bar, there is a small line of text telling the me that I can spend X more euros for Y more days. I have an upcoming transaction set up, for which I would not have enough money in my budget, if I were to actually spend X amount of money each day.

**How to reproduce**
Have a budget and set up an upcoming transaction, due within this budget cycle. 

Calculate the number of days remaining times the amount that can be spent each day.
The result is the budget max - the amount already spent; I am of the opinion, that it should be the budget max - (amount spent + amount scheduled)

**Screenshots/videos**
![Screenshot_20240701-235931.png](https://github.com/jameskokoska/Cashew/assets/144854499/bd654cd3-d486-4ad9-a813-4315905b373a)
![Screenshot_20240702-001119.png](https://github.com/jameskokoska/Cashew/assets/144854499/5215fc9e-1728-493c-90e6-2463e7c70a00)

15,81€ × 31 days = 490,11€ ≈ 490,15€ = 500€ - 9,85€

In my opinion it should be
(500€ - 9,85€ - 29€) ÷ 31 days ≈ 14,87€/day remaining.

**Details**
 - Device: Pixel 7a
 - App Version: 5.3.2+395

**Comment by jameskokoska** [comment]
Upcoming transactions are not marked as 'paid' and therefore are not included in any totals. Once it is paid, it will change the budget total.

Edit - See the FAQ https://cashewapp.web.app/faq.html#future-repetitive-transactions

**Comment by ea-ooe** [comment]
I'm not sure this can be considered a total. It makes sense for the actual total already spent not to include this. 

However, the app telling me that I can spend a certain amount of money each day is misleading. In my opinion this number should reflect the amount of unplanned spending each day that will allow me to stay within budget.

If I have to adjust this daily spending limit in my head to account for this, then depending on the size of the discrepancy between this number and the actual necessary limit to stay within budget I don't believe it to be a useful metric worth showing to the user...

**Comment by jameskokoska** [comment]
I understand your point of view but to be consistent with how all upcoming transactions work within Cashew it has been implemented this way. Upcoming transactions are not 'paid' and therefore don't count towards any totals. If you want it to count towards your total, mark it as paid on the date of the upcoming transaction. Cashew has a setting where you can change the date transactions are marked as paid. or you can always modify the date afterwards 
![Screenshot_20240701_185932.png](https://github.com/jameskokoska/Cashew/assets/50821962/e01a1c3c-1c2d-4639-864e-988b72b09514)

**Comment by santigarcor** [comment]
@jameskokoska, what happens if I want to make a budget of the month to know how much will I have by the end of the month if i spend in other stuff, there's no way of knowing that because those future transactions are not taken into consideration even for the budgets, and me having to manually mark them all paid and then unpaid doesn't make sense. Also, having to manually use the calculator to do `incomes-expenses` beats the purpose of the app.

**Comment by frogiraffe** [comment]
I agree, if scheduled payments are not going to affect the daily budget view until payment, it defeats the purpose of daily budget being there.

**Comment by tayjoy** [comment]
Hey @jameskokoska! Loving the app so far. I also want to add that I'm looking for some forecasting capabilities. I've been trying to use the graph on the account screen to visualize this, but the current total in the app is factoring in future transactions, which can be confusing.

I'd like to request an option to display my current total (excluding future transactions) versus my future total. Having this view available on both the account screen and the home screen would be a huge help for reconciliation and give me a clearer picture of my account status up to today's date.

**Comment by massimostanzione** [comment]
Hi @jameskokoska, thank you for this app! I totally agree with requesting a feature for forecasting or seeing total/filtered budget in a future time, counting repeated transactions as "paid" just in a fictitious transitional state (... also, maybe including also the average of the last "n" months? Or, even more, on the average of the last "n" periods in the previous years? In such a way to emulate some real _-ish_ simulation of the next months). I also see that a consistent number of people is requesting it, even in duplicated issues. Maybe it could be a new feature? 😄 And maybe discussing it in a more related issue, like #315.

I mean, I see your point of view, and the fact that a transaction should be effective only when flagged as "Paid", I have read other comments in other related issues and also the related FAQ, but... it seems that this feature is highly requested!
