### ISSUE TITLE
period ("month" "year" etc) is not translated in the "all spending" screen above the graph

### ISSUE THREAD

**Issue by HappyBear-btc** [jameskokoska/Cashew#314]
translation doesn't work for all languages
![Screenshot_1](https://github.com/jameskokoska/Cashew/assets/122559990/b8648b21-a739-4ab9-ade5-64f1be5b497a)

**Comment by ngocanhtve** [comment]
You are right!

**Comment by jameskokoska** [comment]
Thanks for reporting! Fixed here: https://github.com/jameskokoska/Cashew/commit/331078d8bfc533e087745fe9b72922e1813fff1e

**Comment by ngocanhtve** [comment]
Btw, when you change the source English string, sometimes the translated string in Vietnamese does not change accordingly. How do I know if an English string has changed so I can correct the translation in time?

**Comment by jameskokoska** [comment]
Performing an app restart after selecting a locale will ensure all strings are translated upon launch of the new application instance.

**Comment by ngocanhtve** [comment]
Let me make it clearer.

_Column en_ was A, which was translated to B in _column vi_.
Then you change A to C in _column en_, but _column vi_ is still B. 

I just wish I could somehow know when A was changed to C, so I could update translation B to a new translation that matches C.

**Comment by jameskokoska** [comment]
Oh I see, usually when I change an English translation I create a new entry at the bottom of the sheet. If not you should be able to view edit history as an editor and see what changes have been made when.

**Comment by ngocanhtve** [comment]
> If not you should be able to view edit history as an editor and see what changes have been made when.

Oh i see, I will pay attention to this point later. Thanks!
