### ISSUE TITLE
[Bug] Settle loop upcoming transactions when restoring data using Drive method

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#316]
**Describe the bug**

Upcoming transactions are in _settle loop_ after restoring data from Drive, actually when just logging back into Google account after reinstalling the app from the Play Store.

**How to reproduce**
- Install version 5.3.4 from gihub.
- Create a separate account (ex: account T) to receive interest.
- Set up an upcoming transaction, add an interest to the above account, will pay tomorrow and repeat daily, a positive amount will increase the account balance every day.
- Back up data (use Drive method). Then uninstall the github version. Then install the Google Play version, then purchasing Pro, then swipe all app data, then launch the app and login back your Google account again.

**Screenshots/videos**

https://github.com/jameskokoska/Cashew/assets/125894401/037248d8-6b06-4338-814f-dfe5d8a58168

`You can see in the clip above, transactions paid many days, months ago are reopened and affect the actual balance`

https://github.com/jameskokoska/Cashew/assets/125894401/feded35d-4a7f-460c-a175-23b536bbdad5

https://github.com/jameskokoska/Cashew/assets/125894401/ba5a7dac-6e24-4e4f-bbb6-5186e87ad389

**Details**
 - Device: Samsung Galaxy Note9, Android 10
 - App Version: 5.3.4 Google Play Store (Pro Lifetime)

**Additional notes**

- Although the issue on the Google Play version after purchasing Pro, it also appeared when double check on the github version.

- 
Currently, over an hour since the issue, the balance of account T is continuously increasing because upcoming transactions are continuously occurring in a settle loop, causing the number of paid transactions to increase.

**Important Note**

All issue stop when using the offline file recovery method, not Google's Drive method.
I guess the bug occurs in the step where the data is backed up to Drive. When restoring from Drive, it will cause corrupt data, payment loop, etc.

**Comment by jameskokoska** [comment]
Data backup to drive and from a local file should behave the same. It seems you have auto payment of upcoming transactions enabled. Since the transaction was in the past it will automatically pay the transaction until it has reached the present. An optimization would be to batch write the creation of the transactions requiring a payment to avoid individual payments, but this is behaving as expected.
![Screenshot_20240702_145352.png](https://github.com/jameskokoska/Cashew/assets/50821962/d24f0d11-4f36-4af9-8a2f-1f632beaa30e)

**Comment by ngocanhtve** [comment]
> It seems you have auto payment of upcoming transactions enabled. Since the transaction was in the past it will automatically pay the transaction until it has reached the present.

But at the time I backed up there was only 1 auto payment transaction. But after it restored, it created 2-3 more.

**Comment by jameskokoska** [comment]
Hmm okay I can look into that. By chance, when restoring via Google Drive did you have any sync backups that were restored when they got duplicated?

**Comment by ngocanhtve** [comment]
> By chance, when restoring via Google Drive did you have any sync backups that were restored when they got duplicated?

(My friend) carefully deleted all app data before restoring, and did not turn on sync because he only used it on one device. Sorry, I'm just reporting this case, it didn't happen on my device bcoz I also don't use the same transaction style as him.

**Comment by jameskokoska** [comment]
No worries, thanks for the extra information. Unfortunately I wasn't able to replicate the issue, the GutHub version and Google Play version are basically identical so I don't think that has to do with its recreation. I will however focus on optimizing the upcoming payment of overdue transactions when I get the chance as updating one by one is not optimal from a database perspective.
