### ISSUE TITLE
[Feature Request] Improve One Time Loan collect when using Partially Collect

### ISSUE THREAD

**Issue by williamd1k0** [jameskokoska/Cashew#318]
**Is your feature request related to a problem? Please describe.**
I've recently started using the One Time Loan feature and I like it because it's easy to use as you can collect the amount quite quickly (no need to add any more info, just press a single button).
But when I use the <kbd>Partially Collect</kbd> button, it converts to a Long Term Loan and then there's no <kbd>Collect?</kbd> button. Then I have to create a transaction and add additional info (such as title, category, date, etc.) instead of just clicking <kbd>Collect?</kbd> + adding the amount.

**Describe the solution you'd like**
I think it would make sense to add a helper button like <kbd>Collect?</kbd> for Long Term Loans to show only the amount value prompt, so you can just collect the amount if you don't care about additional info (which should be filled in automatically).

**Comment by jameskokoska** [comment]
Partially collecting a loan turns it into a long term loan. Long term loans give the freedom for users to add more details to each transaction that occurs in a long term loan. You are free to create a separate category to categorize these long term loan transactions if you wish for quick additions.
