### ISSUE TITLE
[Feature Request] A field for description in account details

### ISSUE THREAD

**Issue by akhil-rana** [jameskokoska/Cashew#319]
# [Feature Request] A field for description in account details

**Is your feature request related to a problem? Please describe.**
Currently, there is no dedicated field to store additional details for accounts such as account numbers, crypto addresses, or credit card numbers. This makes it difficult to keep track of important account information within the app.

**Describe the solution you'd like**
Add a new "Description" field in the account details section. This field should:
- Allow users to input and store text information
- Be optional for users who don't need it
- Support storing sensitive information like account numbers securely
- Be searchable within the app

**Describe alternatives you've considered**
- Using the account name field to store this information, but this clutters the main view and limits the account name's usefulness
- Storing this information in transaction notes, but this is not centralized and requires repetitive entry

**Additional context**
This feature would enhance the app's utility for users who manage multiple accounts or need to reference account details frequently. It would be particularly useful for:
- Banking accounts (to store account numbers)
- Crypto wallets (to store wallet addresses)
- Credit cards (to store last 4 digits or full numbers securely)

**Comment by jameskokoska** [comment]
You should not store this information within Cashew. Cashew is not encrypted.
Because of this, a notes section makes much sense. I don't want to encourage users to store personal information within Cashew.
