### ISSUE TITLE
Account transactions

### ISSUE THREAD

**Issue by vjay-jadeja** [jameskokoska/Cashew#32]
There should be separate transaction list when selecting an individual account, it's showing all transactions even when we select only one account, it's bit confusing

Ex. I have two accounts house, business

I selected business but it shows house expense entries together with my business expense entries, it's really confusing, or you can make kind a setting to show all entries together or selected accounts

**Comment by jameskokoska** [comment]
Selecting an account only sets the app's currency exchange. If you want to see the transactions from that account only, tap the selected account again to open the Account Spending details page. You can filter accounts in the search transactions if you only want to see transactions from that account.
