### ISSUE TITLE
[Feature Request] Correct statistics for pressing the Month Total Banner 

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#321]
**Is your feature request related to a problem? Please describe.**
Pressing this banner now access the All spending page, but with statistics that are not pertaining to the current month.

**Describe the solution you'd like**
Please correct the statistics for the current month only (the month where the banner was pressed) instead of the statistics that were previously date range selected in the All spending page.

**Additional context**

![ResizedImage_2024-07-05_20-58-20_2540](https://github.com/jameskokoska/Cashew/assets/125894401/5655133d-5c13-434c-9063-c995a73f8644)

**Comment by jameskokoska** [comment]
Great suggestion! Now when you tap that banner and the net total section in the homepage, the correct date range is applied on the opened All Spending page. Added here: https://github.com/jameskokoska/Cashew/commit/f8a0ac457310d0959825eae8200c9769c3ee2a99

**Comment by ngocanhtve** [comment]
Great. Thanks!
