### ISSUE TITLE
[Feature Request] Layout issue of Loan/Upcoming transactions 

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#323]
**Is your feature request related to a problem? Please describe.**
In transactions like loans, upcoming, subscriptions, There will be an additional icon representing those transactions, smaller and to the right of the category icon. It can be seen that the name of the subcategory is therefore missing.. If it is a loan transaction, the name of the loan will be missing.

**Describe the solution you'd like**
I don't know, but somehow rearranging or cutting out some things will make the information appear more complete.

**Describe alternatives you've considered**
Move the icons slightly in the direction of the arrow.

**Additional context**
![](https://i.imgur.com/rBr5LSD.png)

**Comment by jameskokoska** [comment]
Because that extra icon to the right of the category is an interactive button, unfortunately the spacing is already minimal to support a user interaction in the current layout.

**Comment by jameskokoska** [comment]
To add, there is an (unsupported) debug flag which adds more space to transaction entries

![Screenshot_20240706_010853.png](https://github.com/jameskokoska/Cashew/assets/50821962/d8768be9-8cd0-44da-a444-6922304131ae)

**Comment by ngocanhtve** [comment]
> The gap between the subcategory and the amount is still quite wide, so take advantage of this space to display the full name of the subcategory.

> there is an (unsupported) debug flag which adds more space to transaction entries

Yeah, make it official please!

**Comment by ngocanhtve** [comment]
Could you consider putting the subcategories and loans to the right, the row height is quite good, maybe move the amount up a bit.

![](https://i.imgur.com/EV9J7yP.png)

It can be turned into a second option for those who want to enable it, if not enabled it will be displayed by default.

**Comment by jameskokoska** [comment]
Because it is a debug option, that means I have ran experiments with this feature. However, it hasn't made production for various reasons which could include: reliability and consistency, or it was deemed not necessary during usability testing. Although it's unsupported, you are free to use this option if you find it creates a better experience for you.

**Comment by ngocanhtve** [comment]
> you are free to use this option if you find it creates a better experience for you.

How do I access debugging features?
