### ISSUE TITLE
[Question] Average monthly upcoming transactions

### ISSUE THREAD

**Issue by mimol91** [jameskokoska/Cashew#324]
I've created 2 Scheduled transactions
- 31 July, 444
- 15 August, 200
<img width="773" alt="august" src="https://github.com/jameskokoska/Cashew/assets/2659069/b942539c-6bd4-45d1-98ca-d1f7f75c3298">
<img width="768" alt="july" src="https://github.com/jameskokoska/Cashew/assets/2659069/ca1f6bb8-8d77-4993-aa68-290777ff4c12">

I would expect that Avg monthly is `(444+200) / 2 = 322` (As those transactions are scheduled in two different months)

However app shows sum of those transactions `644` (This same value as Total upcoming)

<img width="798" alt="avg" src="https://github.com/jameskokoska/Cashew/assets/2659069/909f4b79-3a67-4900-aacb-6aa6e27faa2a">

Is it intended, or rather a bug?

---
Attaching DB
[cashew-2024-07-08-19-39-16-120.zip](https://github.com/user-attachments/files/16131451/cashew-2024-07-08-19-39-16-120.zip)

**Comment by jameskokoska** [comment]
Because the transactions are not repetitive, these are the ones upcoming. The average can only take into account repetitive transactions per month. It doesn't necessarily show the amount coming up within the next month.
