### ISSUE TITLE
[Feature Request] Option to exclude Txs of specific category from total spendings/income

### ISSUE THREAD

**Issue by shitcoding** [jameskokoska/Cashew#326]
**Is your feature request related to a problem? Please describe.**
There is an option to exclude specific tx from overall spendings/income stats ('More options' > 'Include amount' checkbox when creating a tx)
This is useful for transfers between own bank accounts / wallets / etc. that will make the stats wrong if included in income/spendings.

(This kind of transfers occurs when you use 'Transfer balance' function for some account, and 2 txs  for transfer in and transfer out with 'Balance correction' category are created automatically. However, I have created a category 'Transfers' with subcategory 'Own accounts', that does pretty much the same, but it's more suitable for my workflow than 'Transfer balance' > 2 'Balance correction' txs default workflow). 

However, this needs to be done manually for every txs for this kind.

**Describe the solution you'd like**
It would be great to have an option to exclude specific category/subcategory of txs from overall spendings/income.
Like 'Include amount' checkbox for single txs, but for the category.

Thanks in advance!

P.S. Love Cashew, it's awesome!!11

**Comment by jameskokoska** [comment]
There are currently no plans to support this at the category level. You should use filters to achieve this result.
