### ISSUE TITLE
Request to add a Sunburst chart

### ISSUE THREAD

**Issue by HappyBear-btc** [jameskokoska/Cashew#327]
Today the pie chart has a toggle between categories and sub categories 
it would be nice to have both on a single chart.
not sure what the right name for it, in excel it's called "Sunburst"

![nested1](https://github.com/jameskokoska/Cashew/assets/122559990/c8a862fd-2bef-4f58-bbc7-0425a326cb0c)

**Comment by jameskokoska** [comment]
Thanks for the suggestion! Unfortunately there are no plans to support this chart. The current implementation already provided a clear and concise visualization of data. Additionally the charting library Cashew uses does not have support for these types of charts.

**Comment by HappyBear-btc** [comment]
sure it's understandable... 
I do this chart anyway in excel after I import the data from Cashew..
thanks in any case!
