### ISSUE TITLE
[Bug] New Account's Calendar is Hard to see

### ISSUE THREAD

**Issue by parthokunda** [jameskokoska/Cashew#328]
**Describe the bug**
The New Account on the webpage has a calendar on the homepage. The calendar is too short in width. The 'View More' icon does not appear fully.

**How to reproduce**
Create a new account. Add spending on different days. Check the calendar on the homepage. 

**Screenshots**
![Screenshot from 2024-07-12 11-36-28](https://github.com/user-attachments/assets/3602ab94-b1b4-4770-96c2-1dfbee710239)

**Details**
 - Device: Web App, Google Chrome
 - App Version: [e.g. 5.3.2+395]

**Comment by jameskokoska** [comment]
This issue was fixed in 5.3.4+396, however I forgot to publish this hot fix release on the web app. The web app release has now been updated.
