### ISSUE TITLE
[Feature Request] Add a way to format notes.

### ISSUE THREAD

**Issue by Dev123456689** [jameskokoska/Cashew#329]
**Is your feature request related to a problem? Please describe.**
Do I have to write as showed in the example?
I am always frustrated when I write a note about a transaction as I like the include all the necessary details about the transactions but it clutters up the notes. Oh God its such a hard work to write a note that is detailed, clear and concise.

**Describe the solution you'd like**
Add notes formatting options such as bold, italic, underline, etc.

**Describe alternatives you've considered**
My smooth single celled brain don't have the processing power to come up with an alternative solution.

**For such small requests what additional context may be given? If any please let me know.**

**Please ignore the mistakes in writing as my English is poor**

**Comment by jameskokoska** [comment]
Thank you for your suggestion! Unfortunately there are currently no plans to support note formatting as the main goal of Cashew isn't a focus for note taking. Formatting adds extra complexity to an already intuitive note taking experience. The notes section is just for adding quick extra details about a transaction.
