### ISSUE TITLE
Linking real bank accounts

### ISSUE THREAD

**Issue by Byteingpython** [jameskokoska/Cashew#33]
Will there ever be an option to link your real bank accounts?

**Comment by jameskokoska** [comment]
The ability to connect your bank account will not be added. It is an expensive feature for (me) the developer. It costs around 1$/user/month from my end which is way too much for a single developer like me to handle at the moment, especially given the current business model. Adding transactions automatically from a bank did not seem worth it to me based on my usage of the app throughout its development. 

I found once you get into the habit of logging down your transactions, it is not a big deal :)

**Comment by rokso** [comment]
@jameskokoska it can be offered as premium feature and at less cost than other players in market, no?

**Comment by ThatOneCalculator** [comment]
Please consider this again, I would happily pay $5-10/mo to link my account. I have ADHD and tracking my spending habits with GPay really helped but Google announced they're shutting it down for US citizens in June. I have a hard time remembering to write everything down, so being able to have another solution to automatically track my spending would be a life-saver.

**Comment by KillianB** [comment]
Hello @jameskokoska ! Sorry for digging up this issue but I would be very happy If you would reconsider adding bank syncing. This would be a mega plus for your app even if I need to subscribe monthly to Cashew as a consequence. Did you look into https://www.powens.com ?

**Comment by jameskokoska** [comment]
Cashew has an API that allows you to automatically add transactions. You can use this feature to sync with your bank. See this thread: https://github.com/jameskokoska/Cashew/issues/127
