### ISSUE TITLE
[Feature Request] Split annual subscription/payment in [n] splits. Probably 12.

### ISSUE THREAD

**Issue by eddsaura** [jameskokoska/Cashew#331]
It would be amazing to have the option to split a recurrent annual payment like gym subs or car insurance to 12 to fit them automatically into budgets. 

And maybe use them as a reminder to save that part of money, but that's an extra.

Really nice job with the app!

**Comment by jameskokoska** [comment]
Cashew already provides a way to create installment payments through the use of a goal.

**Comment by eddsaura** [comment]
> Cashew already provides a way to create installment payments through the use of a goal.

Okay but is not a goal, it is a subscription.

Anyway, do you have an comprehensive guide instead of a FAQ? Do you need help? I would be happy to help you 😄
