### ISSUE TITLE
[Feature Request] Random Color Button 

### ISSUE THREAD

**Issue by Akv2021** [jameskokoska/Cashew#333]
**Is your feature request related to a problem? Please describe.**
At all places in the app where we have option to select icon & color, we get an option to use few pre-selected colors or a custom color using the last option. But since the same colour is used in charts, selecting unique colours is somewhat difficult task. 

**Describe the solution you'd like**
1. In the colour picker menu, There should also be a button to choose "Random/Unique" colour. This button would assign an unique colour that is not already used throughout the app for any other Category/Goal/Loan etc. 
2. Can additionally implement logic to "derive" the sub category color as a shade of category color. 
3. While working on this, you may also want to modify the existing pre-selected colors. I think the most recently used custom colors should also be available to directly select.

**Describe alternatives you've considered**
Having unique colors will make the pie charts much more readable since currently the custom color selections are likely have similar colors.

**Additional context**
This fun & simple tweak will enhance the usability.

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating feature requests. Duplicates will not be addressed again.**
Not all feature requests will be considered. This budget app was created with careful thought given to each feature's usability and prevention of feature overload. As you use the app, you will discover possibly related useful features and that may not be obvious right away. 
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jameskokoska** [comment]
Given the color picker within the application, there are no plans to add a random color generator. This introduces unnecessary complication in both usability and in terms of logic (i.e. we don't want random colors to be too similar to each other, otherwise the user may not think a new one was generated.)

**Comment by contact-maximux** [comment]
sure, but please add few more colors to select. include primary color also
