### ISSUE TITLE
[Feature Request] Value input/calculator: paste value in expression

### ISSUE THREAD

**Issue by Cleric-K** [jameskokoska/Cashew#338]
**Is your feature request related to a problem? Please describe.**
When using the value input (keypad/calculator) it is possible to paste a value (long press on the value). However, the pasted value discards any mathematical expression that is being currently entered. For example, I often find myself in the need to copy certain value to the clipboard then use the calculator to type some number then hit the `-` operation and I want to paste the copied value (in order to subtract it from the first value). This however, discards the whole expression.

**Describe the solution you'd like**
The pasted value should be added to the expression as if it has been typed through the keypad.

**Describe alternatives you've considered**
Presently the only alternative is to memorize the value (instead of copy/pasting it) and manually type it in the expression.

**Comment by jameskokoska** [comment]
Added here: https://github.com/jameskokoska/Cashew/commit/7583c535ec2c4f04c60956f0b6ea4ec543e0870b
You can paste in the calculation to append to it
