### ISSUE TITLE
[Bug] Android 14 Material You Color not changing in the app

### ISSUE THREAD

**Issue by KenStarry** [jameskokoska/Cashew#339]
**Describe the bug**
Whenever you try to change the Accent color and you select system color, it keeps defaulting to the same color but isn't adaive to the actual system color.

For instance, I'm on Android 14 and I have dynamic Material You colour but it doesn't change on the app.

**How to reproduce**
Settings > Accent Color

**Screenshots/videos**
![Screenshot_20240725_172404.jpg](https://github.com/user-attachments/assets/1a1109ab-d48b-4859-aa40-fbab58574df2)

**Details**
 - Device: Vivo v30
 - App Version: 5.3.4+396
 - Android Version: 14

I'm really impressed with the work you are doing!! Can't wait for more exciting updates!

**Comment by jameskokoska** [comment]
Unfortunately I am unable to replicate the issue on Android 14. It is probably worth creating a minimum reproducible example and submit an issue to the package https://github.com/bdlukaa/system_theme

Alternatively, Cashew bumped `system_theme` version to 3.0.0 with version `5.3.5+400` onward, so this may have already been fixed within Cashew.

**Comment by KenStarry** [comment]
Is the update on Google Play yet?

**Comment by D3478** [comment]
Same issue on Vivo X300 ultra. Android 16 and origin os?
