### ISSUE TITLE
Search filters for all spending page, incorrect filtering with account selection combined with period on all spending page 

### ISSUE THREAD

**Issue by Jakopt** [jameskokoska/Cashew#34]
It would be really useful for me if the pie chart for a budget would show either expenses or incomes, like in the all spending view.

**Comment by jameskokoska** [comment]
Budgets are reserved for spending. Just curious about why you want to track income in a spending budget?

**Comment by Jakopt** [comment]
If I earn money during my budget period, I want that money to bump up the budget. I can't really plan how much money I'm going to make in the future, so I just use the budget as a baseline that automatically goes up when I make money. Might not be the intended use case, but it actually works quite fine, without the separation for income / expense the budgets are just a bit broken. I can also do this in the all spending view, but it's kind of annoying that I can't filter there.

**Comment by jameskokoska** [comment]
I see, thanks for the explanation! Could you expand on why the all spending page doesn't work for your use case? I want to improve the all spending page to serve this purpose of being able to compare income and expenses

**Comment by Jakopt** [comment]
Well, basically I want to be able to filter out my capital income from the rest of the income, because I don't want to see money that comes from my savings as money I can spend. The transactions for this have a separate category, so all I need would be an option to exclude that category. The other half of my problems with that page already got solved with the new account selector, so thank you for that. As a long-term, it would be nice to have all or most of the filters from search on there too. And maybe a way to calculate in planned payments during the selected period for the net total.

**Comment by jameskokoska** [comment]
Yes you're right, the pie chart display is incorrect. I can work on adding the filters to the all spending page. The issue from the technical point of view is storing these filters in memory so the user doesn't need to set them each time

**Comment by jameskokoska** [comment]
Added new feature here https://github.com/jameskokoska/Cashew/commit/446271e249fd11fb23a734df845758e728320292

Revamped the all spending page, relies on filters now
By doing so, incorrect account selection filter combination has been fixed, as it now relies on filters
