### ISSUE TITLE
right to left languages display wrong direction in calculator when entering sum

### ISSUE THREAD

**Issue by HappyBear-btc** [jameskokoska/Cashew#341]
**Describe the bug**
right to left languages display wrong direction in calculator when entering sum

**How to reproduce**
go through process of entering transaction up to a point of a keypad. enter expression +/- etc the expression is displayed in reverse.

**Comment by jameskokoska** [comment]
Fixed here: https://github.com/jameskokoska/Cashew/commit/fa6da78dc8d5a29e578e7297f2e3ff299d9adc82
