### ISSUE TITLE
[Feature Request] Add tab for “all” transactions in spending page next to incoming and outgoing

### ISSUE THREAD

**Issue by Radwan-Albahrani** [jameskokoska/Cashew#342]
**Is your feature request related to a problem? Please describe.**
In the all spendings page, I would like an option to show all transactions, instead of separating outgoing and incoming. I would like them to still be categorized as well. 

**Describe the solution you'd like**
In the budgets page, this feature is already implemented. However the spends allows me to set specific times and dates which I use to review my transactions. Ability to see both outgoing and incoming transactions would be very useful. 

**Describe alternatives you've considered**
I switched to cashew from the WalletApp by budget bakers. They had a “reports” page which did exactly that. Showed me all my transactions categorized and combined. And like I said this feature is already implemented in budgets view. 

**Additional context**
![image](https://github.com/user-attachments/assets/0b819ee6-31cb-4364-b3ab-2d0ef5a0f8e5)

**Comment by jameskokoska** [comment]
There is an 'All Spending' page within Cashew already.

**Comment by Radwan-Albahrani** [comment]
That’s not what I meant. I added additional context

**Comment by Radwan-Albahrani** [comment]
Hello. The feature is already implemented in budgets. As shown in the new edit. I want this same chart but for the all spendings page

**Comment by Radwan-Albahrani** [comment]
Commutative is also not the same. As you can see in the budgets page the pie chart calculated the combined total. 

For example: I use a card that has Cashback feature. I usually mark the Cashback within the same category. Making it calculate that within the budget.

**Comment by Radwan-Albahrani** [comment]
You could also instead collapse the categories in the transactions page instead. Really I just need a categorical view with combined outgoing and incoming transactions in order to review my spending in specific areas
