### ISSUE TITLE
[Feature Request] Categorical Grouping within transactions page. 

### ISSUE THREAD

**Issue by Radwan-Albahrani** [jameskokoska/Cashew#344]
**Is your feature request related to a problem? Please describe.**
A button to collapse transactions into their categories in the transactions page. . I would like to know the exact cash flow of a specific category (both incoming and outgoing) 

**Describe the solution you'd like**
A small button (same as the one under the pie chart for example) to collapse transactions into their categorical grouping. 

**Describe alternatives you've considered**
The budgets page is a good alternative but it lacks the flexibility of the transactions page with filters and such. Especially date filters.

**Comment by Radwan-Albahrani** [comment]
Not a combined total. Both incoming and outgoing.

**Comment by jameskokoska** [comment]
This has already been addressed in your previous issue https://github.com/jameskokoska/Cashew/issues/342#issuecomment-2250995430

**Comment by Radwan-Albahrani** [comment]
> This has already been addressed in your previous issue [#342 (comment)](https://github.com/jameskokoska/Cashew/issues/342#issuecomment-2250995430)

Maybe I’m bad at explaining.
@jameskokoska 

the commutative total is not what I am looking for because it takes in the entire lifetime of the app. What I want isn’t a commutative total of everything. What I want is a consultative total for a specific period. Same as the budgets page. 

I could use the budgets page as a workaround but it’s harder to edit and save a budget every time I want to get reports on a different period. 

In the mentioned issue. I showed how the feature is implemented in the budgets, where a category total (next to the category) includes both incoming and outgoing transactions in one grouping.

**Comment by Radwan-Albahrani** [comment]
![image](https://github.com/user-attachments/assets/7eb68e26-aa34-49f1-8219-252b4d0eb228)


This is an example of a quick workaround budget. I need that but in transactions (includes both)
