### ISSUE TITLE
[Feature Request] Expense VS Income

### ISSUE THREAD

**Issue by Zidrenn** [jameskokoska/Cashew#345]
Hello!

Im dealing with a problem when i try to have fast information about my monthly expense/income. I dont get my salary at the same day of the month and that make the possibles configurations (on the "Income & Expenses" menu) not good for me. I always want to the cycle to restart every time i add my income (dont be all the incomes, but in specific one that i choose).

One of the solutions i thougth of about was when i make a new transition of the type income, i can make (with a checkbox or something like that) the income & expense reset. I hope im making myself clear...

Another way that i thougth its on the menu "Income & Expenses" (in addition to "All time", "Cycle", "Past Days" and "Date Range") having the possiblity to have the reset agregated to some category.
For example:
I have the main category "Job", inside this category i have the sub-category "my company name". My idea is every time i add some income with that category the cycle will reset. One little detail in this option is to have the possibilty to not let the cycle to reset, for example, i can have in the middle of the month some extra bonus and i want that to be included on the income of that specific month.

If you want, or need, some more information please feel free to ask!

Thank you.

**Comment by jameskokoska** [comment]
Hi there! If you want a detailed breakdown of your spending, I recommend using the 'All Spending' page. You can apply filters and use custom time periods to view all spending details and statistics.
