### ISSUE TITLE
[Bug] Budgets show excluded transactions.

### ISSUE THREAD

**Issue by Radwan-Albahrani** [jameskokoska/Cashew#346]
**Describe the bug**
In the budgets page, excluded transactions still show up in the list of transactions, but only when selecting all categories then unchecking excluded categories. 

**How to reproduce**
- Make a spending budget.
- Select all categories. 
- Exclude a category

![image](https://github.com/user-attachments/assets/6ea62ff9-fa4d-450b-ad85-3700eaa7c37d)

![image](https://github.com/user-attachments/assets/054dfe3d-3b51-4049-ade8-3887bc61e55c)

**Details**
 - Device: iPhone 14 Pro
 - App Version: 5.3.4-396

**Comment by jameskokoska** [comment]
Thanks for letting me know!
Has been fixed here: https://github.com/jameskokoska/Cashew/commit/04d2c02500b83c8bfc817a01909a967c31e85d36
