### ISSUE TITLE
[Feature Request] Category spending goals improvement

### ISSUE THREAD

**Issue by nick-kulkarni** [jameskokoska/Cashew#347]
**Is your feature request related to a problem? Please describe.**
Currently the category spending goals show the allocated budget. (e.g. 119 / 282.15 or 42.31% / 100%) When trying to create a zero-based budget, it is frustrating to adjust spending goals for the categories because I need to figure out how much money/percentage of my budget is left to be allocated. This especially applies to discretionary spending where one might want to move limits around as the month goes by. 

**Describe the solution you'd like**
1. I would like to have the option to see a "left to be allocated" number on the category spending goals page. This could be similar to the total remaining/total spent option for Budgets.
2. Also convenient would be the ability to do calculations when 'spending limit type' is set to Percent and not only when it is set to Amount. This way, if I am 0.56% over 100%, I can quickly subtract that value from one of the categories.

**Describe alternatives you've considered**
As for now I do mental math to find out how much is left to be allocated when it says 1083.51 / 2165.77.
If it is 99.53% / 100% I will switch to Amount view, and then continue with the mental math.

**Comment by jameskokoska** [comment]
Added here: https://github.com/jameskokoska/Cashew/commit/1864fdde94bd0b0aa2be575c3e7895410ef5bcf7
