### ISSUE TITLE
[Bug] Transaction note tooltip doesn't show correct data

### ISSUE THREAD

**Issue by cHAuHaNz** [jameskokoska/Cashew#348]
**Describe the bug**
If the note of a transaction contains `@` symbol, it will only display the text after the `@` symbol when clicking on Notes icon in transaction list. For example If the text is `Paid to James@SubWay` the tooltip will only show `SubWay`

**How to reproduce**
Add a new transaction, in the transaction note enter `Paid to James@SubWay` or anything with an `@` symbol, select any category and enter any amount, after the transaction is added, in the transactions list hover/tap on the note icon.

**Screenshots/videos**
<img width="596" alt="Screenshot 2024-07-29 at 1 11 47 AM" src="https://github.com/user-attachments/assets/a3e81ce1-38b4-4ddd-80c1-7d00b8becd14">

**Details**
 - Device: iPhone for App and MacBook for Web
 - App Version: 5.2

**Comment by jameskokoska** [comment]
Fixed here: https://github.com/jameskokoska/Cashew/commit/b4c271137ed82f45bc06584241d86ff8a61749c4
