### ISSUE TITLE
[Feature Request] Separate transaction for loan settlement/payment

### ISSUE THREAD

**Issue by SMRehan96** [jameskokoska/Cashew#350]
**Is your feature request related to a problem? Please describe.**
Right now if i settle a loan it isnt recorded as a separate transaction, which limits me to:
1. record date of payment
2. record account in/from which payment was made

The alternative i am using for past loans is to record each transaction as an expense/income. for example if someone loaned me $X i will record it as an income with category Loan(in) and when i pay it back i will record it as an expense with category Loan(out). But with this method i cant see my loans in the loan section or the home page widget so its not straight forward to track loans. 

I would like that the settlements(partial and full) should be recorded as a separate transaction but linked to the original loan transaction.

**Comment by jameskokoska** [comment]
Use a long term loan to track these details.
