### ISSUE TITLE
[Question] Add details in documentation to create transactions from notifications using app links

### ISSUE THREAD

**Issue by Akv2021** [jameskokoska/Cashew#352]
**Describe your question**
WhilE #227 is a great idea, but from the discussions I see that it's not planned anytime soon. I see that the current recommended way of achieving this functionality is to use App links & an additional app like Tasker/Automator for triggering the App link. 

For those new to the Tasker/Automator flows, could you add a section in documentation with a sample script to achieve this ? Interested users can make changes on case to case basis. 

This is required since it'll atleast log the approximate time an expense is made. Currently some banking apps don't show the exact time of transaction which constraints the user to guess/ use current time for making the transaction. Also, it'll automate the manual transactions by a large extent.
The sample flow can use a "Misc" category to create the transaction in default account which we can manually edit later as required.

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating questions. Duplicates will not be addressed again.**
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jameskokoska** [comment]
As mentioned in the documentation, please see this thread for App Link discussions: https://github.com/jameskokoska/Cashew/issues/127
