### ISSUE TITLE
[Question] Add transaction to multiple budgets

### ISSUE THREAD

**Issue by artlp** [jameskokoska/Cashew#353]
Hi, is it possible to add a transaction to multiple budgets? I tried long pressing etc, but it doesn't work. I found nothing in old issues and faq.

**Comment by jameskokoska** [comment]
Only one transaction can be added to one 'Added Only' type budget. This is the same for goals and long term loans. However, transactions can overlap between the single 'Added Only' budget and as many 'All Transactions' budgets with respective filters.
