### ISSUE TITLE
[Feature Request] Bill Splitter: Generate Goals instead of loans

### ISSUE THREAD

**Issue by Radwan-Albahrani** [jameskokoska/Cashew#355]
**Is your feature request related to a problem? Please describe.**
The bill splitter feature is handy. However, the fact it generates loans means it assumes you’ve already paid the bill yourself and are just expecting the other people involved to pay you. Say I’m renting an apartment with my friends. They are all supposed to pay me, and I am supposed to pay the landlord by the end of the lease. My friends are not paying me immediately, they will be paying me throughout the term of the lease. I want to keep track of everything they are paying me (example through a long term loan or a goal) without me having to consider the amount paid to the landlord. 

**Describe the solution you'd like**
Generating goals instead of loans as an option would make it so no amount of money is yet moved from any account. For example, it will generate a “collection” goal for each person, and then a final “payment” goal for the total bill amount.

**Describe alternatives you've considered**
The alternative I’ve been using currently is using the bill splitter for calculations then making the goals manually. 

**Additional context**
Just a question to add, what’s the release schedule on iOS? It hasn’t been updated in a month so I’m wondering when will the next release come?

**Comment by jameskokoska** [comment]
After using the bill splitter, the generated loan transactions can be converted into a long term loan automatically already.

Releases will be made available when they are ready.

**Comment by Radwan-Albahrani** [comment]
The main problem with the bill splitter is that the transactions generated automatically deduct amounts from the associated accounts. 

Generating goals would make it so the calculations are ready but no payments have been made yet, and no amounts have been deducted. This makes it so I can keep track of everything at my own pace.
