### ISSUE TITLE
[Bug] All Spendings page shows Wrong type and selects wrong dates when Long Term Loans are being paid

### ISSUE THREAD

**Issue by Radwan-Albahrani** [jameskokoska/Cashew#358]
**Describe the bug**
In the All Spendings page, in the card that separates expenses from income, when there is “borrowed” or “lent” money through a long term loan, it selects the wrong type. 

Also, when clicking on it, it shows the wrong transaction and selects the wrong date range.

and because it’s the wrong transaction type, it shows the wrong transaction. That caused the change.

**How to reproduce**
- Have a long term loan
- pay off some of that loan.
- check the all spendings page. 

**Screenshots/videos**
![image](https://github.com/user-attachments/assets/d34f4188-a535-44cd-8ed7-80bf6b955e97)

other issue:
![image](https://github.com/user-attachments/assets/66aec784-c869-407d-aa15-47900b799560)

When clicking on the “borrowed” section of the card
Actual result:
![image](https://github.com/user-attachments/assets/d278fc32-3c9e-40a1-bc2f-c00ca2fe753e)

Expected Result:
![image](https://github.com/user-attachments/assets/3b0a9d9f-d228-4208-803d-31786d5669d0)

**Details**
 - Device: iPhone 14 Pro
 - App Version: 5.3.4-396

**Comment by Radwan-Albahrani** [comment]
I guess technically the type makes sense cuz I’m “paying off what I borrowed” but then clicking on it is the issue. Shows the wrong transactions cuz it uses the wrong dates and the wrong filter type

**Comment by jameskokoska** [comment]
Unfortunately, I am unable to replicate the issue. When tapping on the Lent or Borrowed section of the All Spending page card, it always opens the loans page, not the transactions list. As shown in brackets, lent and borrowed totals are only shown for All Time on the All Spending page.
