### ISSUE TITLE
[Bug] All Spendings Page Total Mismatch for Lent and Borrowed Money

### ISSUE THREAD

**Issue by Radwan-Albahrani** [jameskokoska/Cashew#359]
**Describe the bug**
When having multiple long term loans, some are in previous months, and then you start paying them off, the total starts to not match the card that separates income, expense, borrowed, and lent.

**How to reproduce**
- Have multiple long term loans in different months.
- Pay some long term loans from previous months 
- Pay some long term loans from this month

**Screenshots/videos**
![image](https://github.com/user-attachments/assets/2a0a1abe-3d5b-4c5e-a89e-048e4b3f4013)

As you can see above, the net total holds 2 transactions: 
![image](https://github.com/user-attachments/assets/275918af-7e28-4528-8dbb-1e9137218e59)

but then the separate expenses card shows only 1 borrowed transaction in the negative polarity. And when clicked, shows this:
![image](https://github.com/user-attachments/assets/a3fd4cfd-79f3-476f-b053-643882599011)

**Details**
 - Device: iPhone 14 Pro
 - App Version: 5.3.4-396

**Comment by jameskokoska** [comment]
As shown in brackets in the Lent and Borrowed section, the All Spending page always shows the Lent and borrowed totals for all time.

I was unable to replicate the issue. Tapping the expenses section in the All Spending page does not apply filters for Borrowed transactions as you've mentioned.

**Comment by Radwan-Albahrani** [comment]
Sorrryyy I didn’t know how to reopen it…. But yes I uploaded a video in #360. Hopefully it helps

**Comment by jameskokoska** [comment]
The All Spending page totals have been revamped so that the net total makes more sense intuitively. With this, the redirects will follow the same filters as that in the total amount unless all time. Changed here:  https://github.com/jameskokoska/Cashew/commit/f455e376c3929b7bbb304fdd97860980249e1c42
