### ISSUE TITLE
Period support start date and end date

### ISSUE THREAD

**Issue by vnaso** [jameskokoska/Cashew#36]
More -> All spending -> Period

it would  be better to select Period  with  both start date and end date.

BTW, “view all transactions” button always show search page without any filters, while I'm viewing a specific category's transactions list. Is this a bug or feature?

**Comment by jameskokoska** [comment]
Both have been addressed here https://github.com/jameskokoska/Cashew/commit/446271e249fd11fb23a734df845758e728320292
Mainly in this file https://github.com/jameskokoska/Cashew/commit/446271e249fd11fb23a734df845758e728320292#diff-3178ffea9b66220b8311244aadffa4c14e8d426e9fa922151d00e65b4ff7df00L39

The view transaction button now applies the set filters that correspond to the users action/filters set on that page
