### ISSUE TITLE
[Bug] Borrowed/Lent Sections in all Spendings page do not take you to the loans page only when filters are applied.

### ISSUE THREAD

**Issue by Radwan-Albahrani** [jameskokoska/Cashew#360]
**Describe the bug**
Based on the previous reported bug #359 , the borrowed and lent sections of the all spendings page should take you to the loans page. However, when filters are applied, they instead take you to a search page with these filters applied. 

Moreover, even if it were to take you to the search page, the filters become incorrect as it doesn’t actually show the correct transactions. 

**How to reproduce**
- Go to all spendings page 
- Apply any filters (in the video below, I applied account filters)
- Click on borrowed/lent

**Screenshots/videos**

https://github.com/user-attachments/assets/820cd96e-4c68-4bf9-871e-ea4e0f5d1b08

**Details**
 - Device: IPhone 14 Pro
 - App Version: 5.3.2-396

**Comment by jameskokoska** [comment]
Please stop duplicating issues and continue the conversation on the original issue.
