### ISSUE TITLE
[Feature Request] Unify Transfer Money Model

### ISSUE THREAD

**Issue by Radwan-Albahrani** [jameskokoska/Cashew#361]
**Is your feature request related to a problem? Please describe.**
When creating a transaction, the transfer model from within the transaction creation page is different from the transaction model that pops up on quick transfer (holding on the plus sign)

**Describe the solution you'd like**
To Unify the models. The quick model, while concise and brief, makes adding a title/time a bit of a bother, since it pops up yet another model when I click edit. 

Transaction Model inside transaction page:
![image](https://github.com/user-attachments/assets/cbdd5a4f-1b8e-4755-ada3-490ebb762364)

Transaction Model using quick transfer:
![image](https://github.com/user-attachments/assets/916f6ac5-e43a-4c65-a2ba-65388f770bb4)

Adding title with the quick transfer method:
![image](https://github.com/user-attachments/assets/ac2cfe7b-1eb9-4487-944d-fe29cd9979ec)

Also, pressing Done in this page does not get rid of the edit title model:

https://github.com/user-attachments/assets/d178031d-bc36-4b91-a291-4f94b8c9daa8

**Comment by jameskokoska** [comment]
This is intended. When adding a transfer without the extra inputs, it is designed for just that of a quick transfer at the time. These can always be edited by tapping the icon. When adding a transfer through the Add Transaction page, more details are added as, when adding a transaction, more details are usually edited.

**Comment by Radwan-Albahrani** [comment]
@jameskokoska what about the bug where pressing done doesn’t close the keyboard model? Should I submit a bug report for that?
