### ISSUE TITLE
[Bug] Clicking “Done” Does not close keyboard in Quick Transfer Model

### ISSUE THREAD

**Issue by Radwan-Albahrani** [jameskokoska/Cashew#362]
**Describe the bug**
In the quick transfer page, edit transfer details model, pressing done does not close the keyboard

**How to reproduce**
- Hold + in the main page
- Select “Transfer Balance”
- Click on the edit icon on the top right of the model
- Type a title
- Click Done

**Screenshots/videos**

https://github.com/user-attachments/assets/3e3caec2-c977-4852-816b-65ea73ca9773

**Details**
 - Device: iPhone 14 Pro
 - App Version: 5.3.4-396

**Comment by ngocanhtve** [comment]
> Details
> 
> Device: iPhone 14 Pro
> App Version: 5.3.4-396

Mine too!

Device: Sony Xperia 1 (DerpFest Android 14 AP2A.240705.005)
App Version: 5.3.4-396

**Comment by jameskokoska** [comment]
Fixed here: https://github.com/jameskokoska/Cashew/commit/00b4d85df3defa9951c0bcf9dbd94add338eb72a
