### ISSUE TITLE
OFX File Format support

### ISSUE THREAD

**Issue by lserp** [jameskokoska/Cashew#363]
**Is your feature request related to a problem? Please describe.**
I've been using other budget managers and all support ofx file format which makes portability easier. As it stands, I cannot use Cashew due to this, even the Pro version. Furthermore, my bank also uses ofx so I can load up my transactions once a month 

**Describe the solution you'd like**
Import File feature support for ofx file format

**Describe alternatives you've considered**
Using the provided template is not compatible with any other financial app I use nor with my bank.

**Comment by jameskokoska** [comment]
Hi there! In order for Cashew to support a standard format, it has developed its own template. You will need to manually convert your specific format into that of the Cashew template to import. It's not feasible for Cashew to support importing of every different format.
