### ISSUE TITLE
[Feature Request] Add option to exclude transaction amount from Lent and Borrowed type

### ISSUE THREAD

**Issue by vazirani-mukesh** [jameskokoska/Cashew#364]
**Is your feature request related to a problem? Please describe.**
If any new user set up this app, he/she might have already given/borrowed some money to/from someone and he/she might have to track how much is collected/paid.

But there is no option to exclude that transaction money of borrowed/lent.

So account goes to Negative/Positive balance, but there is no point to deduct/credit amount from account as it was already done and this initial setup of app So will add amount of account which is present at that moment.

**Describe the solution you'd like**
Add toggle to "Include Amount" in Lent and Borrowed type Transaction. Just like we have in Expense and Income type Transactions

**Describe alternatives you've considered**
NA

**Additional context**
![Screenshot_20240806-090343](https://github.com/user-attachments/assets/b13d414b-42cb-4b0f-91cf-245b98b9ba1f)

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating feature requests. Duplicates will not be addressed again.**
Not all feature requests will be considered. This budget app was created with careful thought given to each feature's usability and prevention of feature overload. As you use the app, you will discover possibly related useful features and that may not be obvious right away. 
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jameskokoska** [comment]
Unfortunately, the way loan type transaction function, they do not support excluding the amount as that flag is used to track if a loan is settled. To correct a total, you can use the built-in Balance Correction for accounts to correct the total balance to a non-negative when setting up the application. Long term loan transactions can be excluded, however they will also be excluded from the total of the long term loan.

**Comment by vazirani-mukesh** [comment]
Thanks for quick reply @jameskokoska
