### ISSUE TITLE
[Feature Request] Quick Transaction Widget

### ISSUE THREAD

**Issue by Anu6is** [jameskokoska/Cashew#365]
**Is your feature request related to a problem? Please describe.**
Currently, when adding a standard transaction there are few main options.  
- Duplicate an existing transaction
- Use the add transaction API with a pre-defined URL. 
- Add the transaction from scratch 

These options are somewhat inconvenient for frequently recurring transactions

**Describe the solution you'd like**
I'd like to suggest implementing a quick transaction widget for mobile devices. This widget would allow users to:

1. Define a specific transaction when adding the widget to their device's home screen.
2. Automatically create the pre-defined transaction with a single tap on the widget.

The functionality would be similar to the Google Maps directions widget, providing a streamlined, one-tap solution for adding common transactions.

**Describe alternatives you've considered**
Creating and saving URLs for the various transactions as browser shortcuts -_-

**Additional context**
The widget could include customization options such as:

- Transaction name
- Amount
- Category
- Account
- Date (current date by default, with an option to prompt for date selection)
- Notes (optional)

**Comment by Anu6is** [comment]
What about the possibility of favoriting transactions? The transaction in question may not be a recent transaction and so the long press may not necessarily help. Favorites would prevent you from having to search. The favorites list would give quick access to transactions that you could then duplicate.

**Comment by HappyBear-btc** [comment]
I think it's a great idea to be able to add a pre defined set. it doesn't have to be a widget also in app option to be able to define category but ask for amount or pre defined amount and ask for category or just one click to add all defined amount and category.
it's not a recent transaction but rather a template of a transaction.

**Comment by jameskokoska** [comment]
Pinned transactions, similar to "favoriting transactions" has been added to the beta of Cashew. 

See #725 for Beta Testing instructions and information
