### ISSUE TITLE
[Feature Request] Budget history - Filter by subcategory

### ISSUE THREAD

**Issue by mimol91** [jameskokoska/Cashew#366]
**Is your feature request related to a problem? Please describe.**
Currently, you can see the budget history for specific categories.
I want to be able to filter it by subcategory too.

**Describe the solution you'd like**
I would like to be able to filter budget history by subcategory

**Describe alternatives you've considered**
No alternatives now

**Comment by jameskokoska** [comment]
The budget history page is just meant to be a quick overview with main category spending analysis. Adding in subcategory watching of categories will add quite a bit of complication into user interaction and the inner workings of watching a category within the budget history in its current implementation. To get a detailed analysis of your spending with any filter combination, use the All Spending page.
