### ISSUE TITLE
[Bug] Missing Upcoming Transactions with Net Zero Amount

### ISSUE THREAD

**Issue by Anu6is** [jameskokoska/Cashew#367]
**Describe the bug**
When an account has future transactions that net off to $0 (e.g., a transfer in and a transfer out of equal amounts), the upcoming transactions are not displayed under the account details.

**How to reproduce**
- Create a new account.
- Add a future-dated "Transfer In" transaction of $100.
- Add a future-dated "Transfer Out" transaction of $100.
- Navigate to the account details page.

**Observed Behavior**
- The total count of transactions under "Account Total" is correct.
- "View All Transactions" correctly displays the future transactions.
- Only the "Expense" and "Income" lines are displayed in the account details.
- The "Upcoming" and "Net Total" sections are missing, even though the transaction count is greater than zero.

**Expectation**  
The "Upcoming" and "Net Total" sections should be displayed as long as there is at least one transaction in the group, regardless of whether the net amount is $0.

**Details**
 - Device: Pixel 6 
 - App Version: 5.3.4

**Additional notes**
- The issue is particularly noticeable with the "Upcoming" section, but the "Net Total" is also affected.
- This behavior can lead to confusion for users who expect all transaction details to be visible, even when the net result is zero.

**Comment by jameskokoska** [comment]
Good catch! 
Fixed here: https://github.com/jameskokoska/Cashew/commit/9c2163193d75b3645eda3c7f357d1168485c4775
