### ISSUE TITLE
[Feature Request] Display 'Available Balance' in Account Details

### ISSUE THREAD

**Issue by Anu6is** [jameskokoska/Cashew#368]
**Is your feature request related to a problem? Please describe.**
The current Account Total displayed for an account doesn't provide an accurate representation of the funds available for immediate use. This can be misleading, especially when there are upcoming transactions that reserve part of the account balance. It would be convenient if there was a simple way to see how much money is actually available for spending after accounting for these future commitments.

**Describe the solution you'd like**
Introduce an Available Balance section alongside the existing `Net Total`, `Expense`, `Income`, and `Upcoming` categories in the account details. The `Available` balance would be calculated as:

```
Available Balance = Account Total − Upcoming Transactions
```

This would give users a clear, at-a-glance view of how much money they can spend, factoring in the amounts already reserved for future transactions.

**Describe alternatives you've considered**
Manually calculating the difference

**Comment by jameskokoska** [comment]
Upcoming transactions will not be included in any totals. This is to be consistent with all totals within the app. See related for more information: https://github.com/jameskokoska/Cashew/issues/313
