### ISSUE TITLE
[Feature Request] Notes auto complete

### ISSUE THREAD

**Issue by isJasonYeh** [jameskokoska/Cashew#369]
**Is your feature request related to a problem? Please describe.**
Manual input is required to enter the same notes for similar transactions.

**Describe the solution you'd like**
I hope that the transaction notes field can have an auto-complete/suggestion feature like the title field, so that when similar content to what was previously entered appears, there's no need to manually re-enter it.

**Describe alternatives you've considered**
In addition to simply comparing all past notes for the auto-complete function, it would also be helpful if the notes suggestions could be filtered based on the entered title. This means that only notes with the same title would appear in the auto-complete list.

---

These are my suggestions. I usually enter the store name in the title and provide more detailed information in the notes. If this feature could be implemented, I believe it would make the software even more user-friendly. If further clarification is needed, feel free to ask. Thank you for creating such a useful budgeting APP.

**Comment by jameskokoska** [comment]
No plans on giving suggestions for notes. Notes are intended to be different per transaction. If you need, you can duplicate transactions to copy each field.
