### ISSUE TITLE
Transactions - current total monthly expense/income amount

### ISSUE THREAD

**Issue by Michele-x98** [jameskokoska/Cashew#37]
Hi James, very nice and well-made app, congratulations!
Is it possible to see/add the total amount of expenses and income for the current month on the transactions tab?
Now the only information that i can see month by month ( and i need to search it ) is the **Total cash flow** that is very useful but wouldn't be better to have it at the top of the transactions list?

**Comment by jameskokoska** [comment]
It's more of a design decision, logically it makes more sense to go at the bottom. If this information is important to you, consider adding the home page widget for net worth and customizing the time period, or view the all spending page.

**Comment by jameskokoska** [comment]
Actually I like the idea, I can consider it. Maybe a banner showing expense income and net in a smaller form factor for that month

**Comment by Michele-x98** [comment]
Yes exactly, I already have the ones on the home page and those are useful for a fast check, but allow the user to check how was its cashflow and the total amount of expense/income in a specific month by simply swiping back and forth inside the transactions list, would be awesome.

**Comment by jameskokoska** [comment]
Has been added here https://github.com/jameskokoska/Cashew/commit/446271e249fd11fb23a734df845758e728320292#diff-0d61b79d4d1ed41eb036f55b047f29b7cc4588ba707fa8ccab92eadbe4cb83ecR539

Also the all spending page has been revamped, so you can also see a summary of your spending per month (or a custom period) on that page
