### ISSUE TITLE
[Feature Request] Add Transaction Amount Filter to Scheduled Transactions Page

### ISSUE THREAD

**Issue by Anu6is** [jameskokoska/Cashew#376]
**Is your feature request related to a problem? Please describe.**  
Currently, the scheduled transactions page does not offer a way to easily view transactions based on their amount, making it difficult to identify larger or smaller scheduled transactions at a glance.

**Describe the solution you'd like**
I would like to see a filter feature added to the scheduled transactions page that allows users to filter transactions by amount. This could be implemented using a filter slider, similar to the one already available on the transactions page, which would allow users to set a minimum and maximum transaction amount. Alternatively, the search functionality could be enhanced to accept **`>`** and **`<`** operators, enabling users to search for transactions that are greater than or less than a specified amount (e.g., >500).

**Describe alternatives you've considered**
N/A

**Additional context**
This feature would greatly enhance the usability of the scheduled transactions page by providing more control over how transactions are viewed and managed. It would be especially useful for users who regularly schedule payments of varying amounts and need to monitor specific thresholds.

**Comment by jameskokoska** [comment]
The scheduled transactions page provides an overview of upcoming and overdue transactions. If you need to see statistics on a more defined level, the All Spending page should be used.

**Comment by Anu6is** [comment]
@jameskokoska what I'm really interested in is a simple way on the scheduled page to view the monthly/annual income vs expenses. The information is already available there but it doesn't have a way to filter between the two. Using all spending doesn't really give the same feedback.
