### ISSUE TITLE
[Feature Request] Add your Android app to Accrescent App Store

### ISSUE THREAD

**Issue by yyuu22** [jameskokoska/Cashew#377]
Accrescent is a private and secure Android app store built with modern features in mind, includin but not limited to strong security mechanics like app signing key pinning, signed repository metadata, unprivileged automatic updates and developers own apk signing keys. 

Accrescent is currently trusted from privacy and security minded project (you can download Molly, a hardened versione of Signal; Organic Maps; IVPN and other app).  

Accrescent is much more user-friendly and not as bloated with excess unneeded features like F-Droid.  

Thank you for making Cashew and I hope that this could be considered.

PS: i'm not affiliated with Accrescent, i just like the project.

https://accrescent.app/

**Comment by jameskokoska** [comment]
Thanks for the suggestion! Unfortunately, I don't plan on supporting more release channels apart from GitHub, Google Play and iOS.
