### ISSUE TITLE
Subtractions of loans from each other (instead of addition)

### ISSUE THREAD

**Issue by kelvinelove** [jameskokoska/Cashew#38]
If I list 1+ loans I've got (under borrowed), my total owings are a subtraction of those loans instead of an addition: 

![Screenshot 2023-11-16 at 19 03 14](https://github.com/jameskokoska/Cashew/assets/8897257/c2e8d3bc-6c32-4270-8c1b-4f2be775f613)

I believe my total owing should be Loan A + Loan B .....

**Comment by subhashay** [comment]
Looks like one of them is income (200 one) and the other one is expense. That's the reason I  guess.

**Comment by jameskokoska** [comment]
Fixed here https://github.com/jameskokoska/Cashew/commit/446271e249fd11fb23a734df845758e728320292#diff-31cbe1b5db0e98885b59434814b637c0d7234f50a6b288a531bcf2cc008eb21bR2775

@subhashay is correct, seems like it got created incorrectly. Credit and debts have a set value for income and expenses. They now are forcibly set when the query for adding a transaction runs. If you tap the transaction and save it again, it should be fixed.
