### ISSUE TITLE
[Feature Request] Setting to control number of matches to display for title recommendations/auto complete

### ISSUE THREAD

**Issue by keilun** [jameskokoska/Cashew#381]
**Is your feature request related to a problem? Please describe.**
When adding a transaction in the WebApp, the quick add transaction field for `Title` will only show 1 title recommendation. If you close out the quick add transaction widget and use the transaction editing page, the `Title` field will display up to 5 title recommendations. 

The way I've configured titles in my setup is by vendor. However often times vendors match multiple categories (Ex. Costco). So I created separate titles with separate categories. However if I type Costco, the title recommendations shows me an incomplete list of title matches. I've worked around this by being verbose with my title names (Ex. 'Costco - Groceries', 'Costco - Garden', etc.), but it would be great to be able to show all of the auto complete matches.

**Describe the solution you'd like**
Either a user setting to show all title auto complete matches or a user setting to control the upper bound number of auto complete title matches to display.

**Describe alternatives you've considered**
Using verbose title names (Ex. 'Costco - Groceries', 'Costco - Garden', etc.). Requires extra typing which makes entering transactions slower than they need to be.

**Additional context**
Love the app, thank you for creating it!

**Comment by jameskokoska** [comment]
Ideally Cashew is designed so the title is the name of the payee and the Notes would be used for extra information. Cashew also provides subcategories that could fit this use case. Additionally, when only one transaction shows up in the recommended, the "Submit" workflow (Pressing Enter) makes the most sense - selecting the only title that is shown. If multiple are shown, selecting the first on a text field "Submit" may not be intuitive.

**Comment by keilun** [comment]
> Ideally Cashew is designed so the title is the name of the payee and the Notes would be used for extra information. Cashew also provides subcategories that could fit this use case

I was indeed trying to use Payee as the title (Costco in this case). The main use case I was aiming to get is so that I don't have to select the category each time. But since Costco matches a variety of categories (Groceries, Clothes, etc.), you'd wind up with multiple titles named `Costco` and the recommendation matches by name would be the barrier because you couldn't refine the recommendation search if all the title names were the same. That's the only reason I encoded the category name into the title so I could then refine the recommendation search.

I can see what you mean about wanting the Submit workflow to be clear for the quick add transaction widget though. But there is at least the full transaction page which shows up to 5 titles which presents the same problem once you reach more than 5 categories for a single Payee.

Anyway if you feel this breaches the design, my workaround will suit me just fine. Thank you for considering it.
