### ISSUE TITLE
[Feature Request] Option to select accounts in the Home Transaction List

### ISSUE THREAD

**Issue by Rafee-M** [jameskokoska/Cashew#383]
**Is your feature request related to a problem? Please describe.**
Currently the transaction list displays recent transactions of all accounts. I think if we could select which accounts to display, it'd make it easier to take a quick glance at the important accounts.

**Describe the solution you'd like**
Like the pie chart, income & expenses, etc. a checkbox to select which accounts to be displayed would be helpful. I noticed you wish to keep the home transaction list simple and I believe this addition would maintain that.

**Additional context**

<img src="https://github.com/user-attachments/assets/edb72a45-9fa8-4548-a905-dc9a1e6e23f9" width="270" height="182">

(The checkbox)

**Comment by jameskokoska** [comment]
To cater to usability, the transaction list on the homepage should show all recent transactions. You can use the transaction list page to apply filters if you wish
