### ISSUE TITLE
The animations are very lazy

### ISSUE THREAD

**Issue by IamRezaMousavi** [jameskokoska/Cashew#384]
**Describe your question**
Is it possible to reduce the duration of each animation a little?  Or only animations with a long duration?
Because the app seems slow and lazy.

**Comment by Rafee-M** [comment]
There's an option to set app animations to minimal. It seems to reduce a couple of long animations noticeably.

**Comment by IamRezaMousavi** [comment]
> There's an option to set app animations to minimal. It seems to reduce a couple of long animations noticeably.

I want all animations but only with less duration.  Does this option do this for me?

**Comment by jameskokoska** [comment]
As @Rafee-M mentioned, you can set the animations to minimal.

**Comment by Rafee-M** [comment]
That is a valid option, I agree
