### ISSUE TITLE
[Feature Request] Option to make the View All Transaction button in Account menu more accessible

### ISSUE THREAD

**Issue by Rafee-M** [jameskokoska/Cashew#385]
**Is your feature request related to a problem? Please describe.**
The way to reach the View All Transaction button (i.e Search) for an account is either from:
1. Go to Accounts menu > Scroll to the bottom 
2. Go to Transactions tab > Search > Filter

While these do work well, I think it the number of clicks could be reduced

**Describe the solution you'd like**
I believe it could be made easier to check all transactions by moving the View All Transaction button in the accounts menu a bit higher to the page. It would make it more easy to reach it.

**Additional context**

<img src="https://github.com/user-attachments/assets/089a1c2b-5db0-4fae-9b84-408b52125e01" width="203" height="430">

<img src="https://github.com/user-attachments/assets/d7cbf297-858c-424e-b68f-28d681f05ba3" width="203" height="430">

Not necessarily like this, but something of this essence would a be nice quality of life improvement.

**Comment by jameskokoska** [comment]
Tapping the account total will view all transactions.

**Comment by Rafee-M** [comment]
Oh my bad I hadn't noticed it. That's perfect, thanks!
