### ISSUE TITLE
[Bug] All Spending History - Per Period Expenses/Income Doesn't Tally

### ISSUE THREAD

**Issue by 8227846265** [jameskokoska/Cashew#386]
**Describe the bug**
1. The total income / total expense on All Spending > History doesn't tally. It shows more than the actual total per period.

**How to reproduce**
1. Go to `All Spending,` then click `History.`
2. Period Setting / Cycle:
A. Every 1 Month
B. Beginning March 1, 2024
C. Spending Totals = Per Period
D. Filter = All / Default

**Screenshots/videos**
I'm sorry, but the All Spending History page is quite sensitive, so I won't be able to upload a screenshot.

**Additional Note**
The Net Total shows correctly. Only the Total Income and Total Expense don't tally.

**Details**
 - Device: Xiaomi Poco F3
 - App Version: v5.3.8+410, db-v46

**Comment by 8227846265** [comment]
I found the possible cause of the problem. The All Spending > History page seems to include `Transfer` transactions between `Accounts` as part of the total and attributes them to the `Total Income` and `Total Expense`.

If you use the filter function and check `Income` and `Expense,.` The total income and expenses will be correct.

**Comment by jameskokoska** [comment]
This is intended. The total should be cash flow, not income and expenses only. If it was income and expenses like before, the total net would be incorrect, as it was previously.

**Comment by 8227846265** [comment]
But green and red text color indicates income and expenses.

Plus transfer function is simply moving money from one account to another which doesn't signify any additional income or additional expenses.

**Comment by 8227846265** [comment]
If transfer will still be counted then. I would like to suggest a feature in the settings to allow users to select Income and Expenses filter by default when opening the All Spending > History page.

Users like me prefer to see the actual total income and total expense when viewing the history page to see how much I improved my finances.

**Comment by jameskokoska** [comment]
To add some more context: This change was made to ensure that the total net would be consistent for that time period. (Changed here: https://github.com/jameskokoska/Cashew/commit/d1826330d0d41eacf0a67a0dc1e7f427f8a00c7d) When balance corrections were not included, the net displayed in the History tab would be incorrect (if there was an offset of balance corrections). The green and red amounts in the history tab represent the cash flow, not necessarily the income and expense for that time period. 

However, by applying an "Income" and "Expense" filter, this will ensure only those are shown and the user will be aware of this selection.

**Comment by 8227846265** [comment]
I understand.

However, by applying an "Income" and "Expense" filter, this will ensure only those are shown and the user will be aware of this selection.
- Would it be possible to add a settings to automatically select both filters? For me, my main use case is to accurately understand how much income and expenses I made each month.

At the moment the all spending > History page income and expense shows 45% more than I actually I'm capable of spending or earning each month.

**Comment by 8227846265** [comment]
It's 45% more since I Bank account and Cash Account. I transfer the huge portion balance from Bank to Cash each month and that counts to the Income and Expense value on All Spending > History page.

**Comment by Ahmed-Abosamaha** [comment]
I prefer the previous version 

To active the filter  to show the income and expense each time when visiting the all spending history page is not the proper way.

**Comment by 8227846265** [comment]
The latest update seems to have fixed the issue.

I can see the total income / total expenses correctly now without needing to activate the Income/Expense filter.

**Comment by Ahmed-Abosamaha** [comment]
Thanks for responding 😊

**Comment by jameskokoska** [comment]
It has been reverted here https://github.com/jameskokoska/Cashew/commit/91afa44ecbe330b7c02f0a33a350d86ea53575d8
