### ISSUE TITLE
[Bug] Web App > Sync Failed

### ISSUE THREAD

**Issue by 8227846265** [jameskokoska/Cashew#387]
**Describe the bug**
I am encountering a sync error on the web app. My Android device is already using the latest version of Cashew, and I have attempted to resync it multiple times, but the sync error persists. 

I already deleted the old backups on both Android and Web apps, but the issue persists.

**How to reproduce**
1. Login on the web app

**Screenshots/videos**
![image](https://github.com/user-attachments/assets/dcf0e9d7-0dcd-47b5-8c5a-4cf8d76ae524)

**Details**
 - Device: Windows 11 Laptop / Brave Browser (Latest Stable)
 - App Version: v5.3.8+410, db-v46

**Comment by jameskokoska** [comment]
Unfortunately, without more information I am unable to replicate the issue. As the error states, please delete your sync backups and try again.

**Comment by jameskokoska** [comment]
By chance have you been using Notifications or Email scanning debug feature? I removed syncing for these values and that created an out of range enum index. This has been fixed, and I have added an error output when this error pops up. If you still experience the issue, feel free to continue the conversation with this new output error.

**Comment by 8227846265** [comment]
By chance have you been using Notifications or Email scanning debug feature
- No.

But thank you for the update. I'll see if my work laptop still has syncing issue once I get back to the office.
