### ISSUE TITLE
Option to reorder the "Accounts" in Homepage

### ISSUE THREAD

**Issue by Umairuem** [jameskokoska/Cashew#39]
The "Accounts" in the homepage remain in the order they are created in. 
Whereas some of these accounts have a higher priority order while some are those which are of lower priority order for us.

The high priority order accounts can be pinned, yes, but not when there are a lot of accounts and you want to arrange them in some certain way.

Simply put, I request some feature similar to how we can reorder our "Categories" as well.

**Comment by jameskokoska** [comment]
Accounts can be reordered on the Edit Accounts page. You can find this page by going to [More] > [Accounts] 

In the next update, an edit icon will appear in the popup shown by tapping the plus on the homepage. It will redirect the user to this page.

**Comment by Umairuem** [comment]
Oh, got it. Thanks! 
I did check out that page, but I did not notice the Reorder symbol there, and mostly managed my accounts in the Homepage.

Anyways, Great App! 💯
I've been searching for such a budget management app for a long time. Finally got to know about Cashew, and I have been fully enjoying it. 
Thanks for this great contribution.

**Comment by jameskokoska** [comment]
Glad you enjoy Cashew :‎)

**Comment by ruben-vl** [comment]
> Accounts can be reordered on the Edit Accounts page. You can find this page by going to [More] > [Accounts]

Thanks! Took me longer than I'd like to admit to find this. Single-click on the account in the homepage UI and then edit in the account overview is more intuitive to me than the 'hold' to edit account. Rearranging on 'hold' feels more natural. No criticism, great app, just letting you know that I might not be the only one with that problem.

> In the next update, an edit icon will appear in the popup shown by tapping the plus on the homepage. It will redirect the user to this page.

I don't think this has become a feature? Or at least I cannot find it on the iOS app.
