### ISSUE TITLE
[Bug] Subcategory not being saved in auto-suggested titles

### ISSUE THREAD

**Issue by mrkranky** [jameskokoska/Cashew#392]
**Describe the bug**

When a new transaction is created with a title, a category and a sub-category, the sub-category is not saved under the "Edit Titles" tab. 
If I manually change the sub-category inside the "Edit Titles", everything is fine. But once I make some other changes in that same transaction and save it, then the sub-category information is again lost under the "Edit Titles" tab. 

**How to reproduce**

1. Create a transaction with a category and sub-category. 
2. check under "Edit titles" tab, that this suggested title has lost the sub-category information
3. Edit that title now and choose the correct sub-category and save changes. The title is now linked with correct sub-category.
4. Now go back and edit the same transaction (like add some notes etc.) while keeping the transaction under the same sub-category and save the transaction. 
5. Check the "Edit titles" tab to see that the sub-category information has been lost again. 

**Screenshots/videos**

**Details**

 - Device: Iphone (IOS)
 - App Version: 5.3.8 +410

**Additional notes**
[Any additional information can go here]

NOTE TO THE SUBMITTER
Reporting bugs is important for maintaining the app. Thank you for helping make the app a better experience for all!

**Comment by jameskokoska** [comment]
Titles only store the main category. They support subcategory selection, but this is not automatic. The subcategory was intended to be added later in the add transaction flow.

**Comment by mrkranky** [comment]
@jameskokoska any work arounds for this until we have sub-category as part of transaction? It would be  nice to not keep editing the sub-category in the "Edit Titles" tab all the time

**Comment by jameskokoska** [comment]
Ah I understand, if a transaction uses the same title as one that has a subcategory - a new title would be created with the main category (which will overwrite the title in recommendations with the custom subcategory). This has been changed so that will no longer be the case. Changed here: https://github.com/jameskokoska/Cashew/commit/e2af69ee53540e80622ed4fe0a10a29f57754333

**Comment by mrkranky** [comment]
@jameskokoska thanks for the fix. When will this fix be released for either webapp, android or iOS for testing?

**Comment by jameskokoska** [comment]
This has been addressed in the latest beta (6.2.7+470)
A subcategory (if selected) is now saved for titles automatically instead of the primary category.
See #725 for Beta Testing instructions and information.
