### ISSUE TITLE
[Question] What's Firebase for?

### ISSUE THREAD

**Issue by MaxiPepa** [jameskokoska/Cashew#397]
Hi! I was wondering, in the app page and here in GitHub it says that the app uses Firebase. For what end does it use it? As far as I'm aware, the data is all stored locally or in Google Drive backups, so what's Firebase doing exactly in the app?
Thanks!

**Comment by jameskokoska** [comment]
Firebase is used to handle the feedback form within the application. It's also used to host the web app, however external from the code. It was previously used for the discontinued shared budgets feature - some code remains but is completely unused and disabled, and no longer functions correctly. You are free to explore the source code to see the exact use cases.
