### ISSUE TITLE
[Question] Automatically "refill" an account 

### ISSUE THREAD

**Issue by ReddishPython** [jameskokoska/Cashew#398]
I frequently use a payment app which has a predetermined availability, which gets automatically refilled every Monday from my bank account.
I was wondering if it's possible to create a transaction that would automatically transfer funds from the "bank" account to the "payment app" account and have the amount automatically filled to (weekly availability - current balance).

I hope my explanation was clear enough

**Comment by jameskokoska** [comment]
Duplicate of https://github.com/jameskokoska/Cashew/issues/160
