### ISSUE TITLE
Portuguese translation issue

### ISSUE THREAD

**Issue by jrom99** [jameskokoska/Cashew#40]
![Screenshot_2023-11-21-00-23-36-720-edit_com.budget.tracker_app.jpg](https://github.com/jameskokoska/Cashew/assets/47498278/8af31eb3-20ee-40ee-bb80-16602141f3f0)

In the provided screenshot, the budget card ("Orçamento") has "por 10 mais (number) dias", which doesn't make much sense in Portuguese. I'm unsure what is the original string, but I may be able to help.

My OS is MIUI 13.0.2 (Android 12), with Cashew release is v4.8.8+250.

**Comment by jameskokoska** [comment]
Thank you for letting me know! It has been fixed in the [translation spreadsheet](https://docs.google.com/spreadsheets/d/1QQqt28cmrby6JqxLm-oxUXCuM3alniLJ6IRhcPJDOtk/edit?usp=drivesdk). Translations are pushed periodically to the repo.
