### ISSUE TITLE
[Feature Request] Printable "statements" 

### ISSUE THREAD

**Issue by ITron-Legends** [jameskokoska/Cashew#400]
**Is your feature request related to a problem? Please describe.**
[A clear and concise description of what the problem is. Ex. I'm always frustrated when...]
My parents started using this app but they want printable statements so they can keep a record offline. 
They also want by month so using the excel sheet isn't possible. 
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Statements should be downloadable by account, year or month or specific dates 
I've made a example on how it should look 
I'll update with a more maybe good looking one, but I really need this. 
**Describe alternatives you've considered**
[A clear and concise description of any alternative solutions or features you've considered.]
Not really any alternatives....
**Additional context**
[Add any other context or screenshots about the feature request here.]
![Picsart_24-08-28_18-44-29-083](https://github.com/user-attachments/assets/6d873c86-8c71-477e-9070-755cc1f37498)

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating feature requests. Duplicates will not be addressed again.**
Not all feature requests will be considered. This budget app was created with careful thought given to each feature's usability and prevention of feature overload. As you use the app, you will discover possibly related useful features and that may not be obvious right away. 
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by Keinta15** [comment]
> Thank you for the reply but I can't seem to find the export csv option with a custom date range it just exports 

When you click on "Export CSV File" it asks which accounts and to select either "all time" or "date range"
