### ISSUE TITLE
Importing Data with Subcategories and Matching Column Formats

### ISSUE THREAD

**Issue by EmmeMax** [jameskokoska/Cashew#403]
**Describe your question**
Is it possible to import data with subcategories? The template only includes a category column, but I've added categories and subcategories in the app. I want to import my bank-exported data and include the categories from the app.

I noticed that the exported data from Cashew contains many columns not displayed in the import template. Could using the same format as the exported data be a solution?

**Comment by jameskokoska** [comment]
Duplicate of https://github.com/jameskokoska/Cashew/issues/87 and https://github.com/jameskokoska/Cashew/issues/202
