### ISSUE TITLE
[Bug] Current Period is not updating to the set start date of the budget.

### ISSUE THREAD

**Issue by kaleluser564** [jameskokoska/Cashew#404]
**Describe the bug**
So I was trying to set-up a budget for a month ahead (in this case, for September since its August 31st and is the first time I am using the app). So I open and create a new budget, set it to begin tomorrow. However, when I click submit, it still saves the time period as between August and Today, which doesn't make sense since I have set the start date on the 1st of September.

**How to reproduce**
Create a budget that is set to begin the next month and see if it will reflect the time period as starting from the date provided or the previous month's tims period.

**Screenshots/videos**
![20240831_094100](https://github.com/user-attachments/assets/62528e8e-d664-4487-99fb-e737f931e10b)
![20240831_094051](https://github.com/user-attachments/assets/0435acbd-4ede-429f-affb-796ec3455407)

**Details**
 - Device: Samsung Tab S9 and S24+
 - App Version: 5.4.1 (version on the Playstore)

**Additional notes**
Thanks for the effort in making the app, hope this issue gets resolved.

NOTE TO THE SUBMITTER
Reporting bugs is important for maintaining the app. Thank you for helping make the app a better experience for all!

**Comment by jameskokoska** [comment]
Hi there! As it states in the app, this is the current period. Budgets automatically reset the period and when the date changes, the new period will start. If you want a static non-automatic repeating budget, use a custom period.

**Comment by kaleluser564** [comment]
Ahh I see, thanks!

**Comment by jameskokoska** [comment]
No worries, I see how this can cause some confusion. Happy budgeting!
