### ISSUE TITLE
[Feature Request] Sorting option in "Categories" page

### ISSUE THREAD

**Issue by Aravind-Ram-321** [jameskokoska/Cashew#405]
**Is your feature request related to a problem? Please describe.**
It would be nice to add buttons to sort the categories alphabetically in that page. Right now, when I try to manually rearrange the categories, in the web app - when I click and drag a category card up or down, the screen is either not scrolling or it is very slow - so it is taking more time to bring it to the top or bottom of the list.

![image](https://github.com/user-attachments/assets/a99e4951-47f5-4013-97ee-a8bb424bd44d)

**Comment by jameskokoska** [comment]
From a usability perspective, sorting should be predictable. When a category is added and they are sorted alphabetically, the order changes abruptly especially the order for selecting a category for a transaction. Because of this, automatic sorting won't be implemented. 

To easily change the order, you can reorder categories in the select category popup instead. This also provides a true representation of the order of categories when adding a transaction.

**Comment by Aravind-Ram-321** [comment]
I'm not sure if I understood your comment properly but here is the issue:
1. It's not possible to reorder the categories in the 'select category' pop-up
2. When I try to manually reorder the category cards in the 'Edit Categories' page, as I click and drag it upwards/downwards, the screen is scrolling very slow and it makes it harder and longer in duration to manually reorder. This happens in the web app - checked in Edge and Firefox. This is not the case in Android, scrolling is smoother as I click and drag the cards there.
3. My concern is not about the select category pop-up or transactions at all. I understand that the select category pop-up reflects the same order of categories that is sorted in the 'Edit Categories' page. As I keep adding new categories and as the list grows, it becomes difficult for me to find the categories easily in the pop-up as they are jumbled (alphabetically) now. Hence, if there is a button to sort it alphabetically in the 'Edit categories' page, it would reflect the same order in the pop-up as well and it makes finding the category easier as I can just look for the first letter of the category I need and locate it quickly.
4. I'm not asking for automatic sorting of the categories when they are added. Let a new category append to the list just like now. But, a sorting button on the edit categories page will make life easier for users like me. I can just add a new category, then click the sorting button to make the new category to move to it's appropriate position. For users who don't want sorting, they don't have to bother clicking the sorting button if they prefer to have the list in the original order of how they added the categories.

I hope this provides much clarity on what I'm trying to explain.

**Comment by Aravind-Ram-321** [comment]
@jameskokoska ⬆

**Comment by jameskokoska** [comment]
This has been added in the beta. Categories can be sorted in place in the beta, the sorting will be applied and will become the new order of categories.
See https://github.com/jameskokoska/Cashew/issues/725 for Beta Testing instructions and information.

<img width="296" height="573" alt="Image" src="https://github.com/user-attachments/assets/6c8355cf-62f6-4d65-9c56-1668ecbd8eb1" />
