### ISSUE TITLE
[Bug] - Problems with Sign-In and Data Sync Between modified mobile apk and https://budget-track.web.app

### ISSUE THREAD

**Issue by gauravagarwal2704** [jameskokoska/Cashew#407]
# **Describe the bug**

I am new to Flutter and mobile development. Initially, I faced some issues running the app, but after upgrading a few packages and making some code changes, I managed to get it running.

I successfully forked the repo to make some UI and functionality changes. However, when trying to sign in, I encountered the following error: `I/flutter (7556): PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)`. After some debugging, I resolved this by creating a new app in Firebase and updating the `google_services.json` file.

The changes I made were for the mobile app only, but I still want to use the web version at https://budget-track.web.app/ to add transactions. The issue is that my release APK is signed with locally generated keys, which differ from those used by the web app, causing data sync problems.

I also tried running the web version locally but encountered multiple issues. Additionally, I do not intend to host the web app myself and prefer to rely on `https://budget-track.web.app`

Could you please help me resolve these issues?

# **Summary:**
- Sign-in errors resolved by adding Firebase configurations to personal account, but data sync issues persist due to different signing keys.
- Unable to use the web version seamlessly and prefer not to host it..

**Details**
 - Device:  Oneplus IN2011 (Oneplus 8)
 - App Version: 
<img width="356" alt="image" src="https://github.com/user-attachments/assets/9ceb8a4c-7640-4d4a-9294-0d7d163f8f3f">

**Comment by jameskokoska** [comment]
Unfortunately, I don't have time to provide support for source code issues or unsupported forked versions of the app.
