### ISSUE TITLE
[Question] Multiple assets in the same account

### ISSUE THREAD

**Issue by giovaborgogno** [jameskokoska/Cashew#412]
**Describe your question**
Is there a way to manage multiple assets in the same account? for example I want to create an account "Metamask" and manage transactions for different cryptocurrencies; or a "Bank" account and be able to add transactions in USD and EUR.
If it is not possible, do you have plans to add this functionality?

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating questions. Duplicates will not be addressed again.**
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jameskokoska** [comment]
Duplicate of https://github.com/jameskokoska/Cashew/issues/109

**Comment by giovaborgogno** [comment]
Please consider this as a feature that could be added in the future.
thanks, the project is amazing!
