### ISSUE TITLE
Edit budget dates

### ISSUE THREAD

**Issue by DavKiller** [jameskokoska/Cashew#413]
**Is your feature request related to a problem? Please describe.**
As a person who gets paid on different days, it is a bit annoying for me to balance the budget function, since I can't balance my income or I simply can't use the function correctly.

**Describe the solution you'd like**
What I would like to see is that in each budget month we can put a start day and an end day, this would help a lot to balance those expenses and to be able to see the graphs in a real way according to the income and expenses in an arc of dates.

**Describe alternatives you've considered**
The “easier” alternative is to offset the dates of income and expenses at the beginning of the budget, but over the months there will always be an offset if one day you collect on the 29th and another on the 31st.

**Additional context**
The way to do this could be to add an “advanced options” and leave a “separate budgets by month” bookmark and in each month allow you to add a start and end date.
![image](https://github.com/user-attachments/assets/a8b876b3-bbf2-43c2-9bd3-dbd333692754)

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating feature requests. Duplicates will not be addressed again.**
Not all feature requests will be considered. This budget app was created with careful thought given to each feature's usability and prevention of feature overload. As you use the app, you will discover possibly related useful features and that may not be obvious right away. 
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jameskokoska** [comment]
If your budget cycle follows an inconsistent period, you can create a budget with a custom time period . Custom time periods are already supported within Cashew.

However, you will need to add a budget outside that of the onboarding page.
