### ISSUE TITLE
Monochromatic Icons for Better Accessibility and Consistency

### ISSUE THREAD

**Issue by Michael152843** [jameskokoska/Cashew#416]
**Is your feature request related to a problem? Please describe.**
Since FreePik icons are designed by different people, they often use varied color swatches and shadings. This often creates accessibility and consistency issues in the app - some icons and background colors don't work together at all, some look fine in the dark mode but then they look weird in the light mode, and vice versa. Additionally, many subcategory icons on the transaction page lack clarity and are barely readable.

**Describe the solution you'd like**
It would be great to be able to use monochromatic, adaptive to themes icons for categories, budgets, loans and goals, since they better adhere to the accessibility, consistency and clarity guidelines of Material Design. Given that we can already select different background colors to distinguish categories, colored icons are not that necessary.

**Additional context**
Just as an example, I have attached some screenshots from a different money management app called TrackWallet. Note how even the tiny icons remain easily readable due to their consistency and how they improve the overall clarity of the app.
![Screenshot_20240911_000958_TrackWallet](https://github.com/user-attachments/assets/0b7d6052-665d-4b1f-8dae-cc9d9e5befa9)
![Screenshot_20240911_001018_TrackWallet](https://github.com/user-attachments/assets/29696d9e-9b9d-4205-9b54-92da2eb4b5ce)

**Comment by jameskokoska** [comment]
There are currently no plans to support other icons in Cashew. Currently the supported icons are the included FlatIcon and emojis. 

I've considered supporting another icon pack such as https://github.com/hugeicons/hugeicons-flutter/tree/main however in my opinion, adding many icon packs will create unnecessary clutter and inconsistencies across the UI.

**Comment by Michael152843** [comment]
I've just discovered that it's possible to enable simple outlined icons via `Debug Flags`, which in my opinion are much clearer and better looking👍

**Comment by jameskokoska** [comment]
Glad you like it :) Let me know any feedback, it’ll be officially supported soon!

**Comment by Michael152843** [comment]
I think they look great - much easier to read and to set colors. Also, for some of us who have to share screencaptures with business partners, the outlined icons give the app that formal and professional touch.

It would be great if we could also have some brand icons (Amazon, YouTube, Google, Spotify, Netflix, etc.). While it was tricky with Flat Icons, since they would have to follow some very specific brand guidelines, this is not the case with outlined icons, which are used in many other apps. This would allow users to neatly organize the subscription categories, etc.

**Comment by jameskokoska** [comment]
This has been added in the beta. You can now customize the Category Icon Pack, which includes monochromatic icons. 

See #725 for Beta Testing instructions and information

![image](https://github.com/user-attachments/assets/77dc1a28-7321-4e4b-a4a8-e7a60c0c504f)
