### ISSUE TITLE
how to add a refund transaction 

### ISSUE THREAD

**Issue by DataEnginr** [jameskokoska/Cashew#417]
How to add a refund transaction which cannot be categorised as an income.
Let's say I have spend 100 and there is a refund of 50 . How should I add this transaction? It should basically offset against the original transaction of 100

**Comment by jameskokoska** [comment]
If you made a return and don't want to add an income transaction, you can mark the original transaction as "Not included" in the total amount. You can do this by editing the transaction, tapping "More Options" at the bottom and removing the "Include Amount" option.

The best way is to add a transaction of opposite polarity (income, if refunding an expense) to add a record.

**Comment by DataEnginr** [comment]
Well we cannot mark the entire transaction as "Not included" , if partial transaction is deemed as an expense. and adding a new transaction as income seems to be not correct as its not an income in first place. Not able to offset the refund to the original expense transaction inflates overall expense budget. Can we have a feature of adding a -ve amount as an expense

**Comment by HappyBear-btc** [comment]
I agree it makes sense to be able to add negative amount.
