### ISSUE TITLE
[Bug] Loans counted twice towards net worth ?

### ISSUE THREAD

**Issue by eduardvercaemer** [jameskokoska/Cashew#418]
**Describe the bug**
Money that you record as borrowed is counted twice towards net worth calculation.

**How to reproduce**
1. Open cashew in new incognito window (new account).
2. Add new long term loan for 100K
3. Add net worth widget in home.
4. Should display zero 

**Screenshots/videos**
![image](https://github.com/user-attachments/assets/441f4d90-a767-4a71-9c3d-ae027ff27ba7)

**Details**
 - App Version: v5.4.0+413

**Additional notes**
Net worth calculation for this simple example should be +100K in assets (bank account) -100K in debt (loan) = 0.

If I go into the net worth section (all spending) and add filter "no loan" it actually works as expected. Ideally this is either configurable for the home widget or better yet the default.

**Comment by jameskokoska** [comment]
See https://github.com/jameskokoska/Cashew/issues/185

Edit: See the FAQ for more information regarding the logic behind the polarity for determining loan transactions (which directly effect the net worth) https://cashewapp.web.app/faq.html#lt-loans

**Comment by eduardvercaemer** [comment]
Sorry but I don't see how #185 is useful or related.

For starters, the net worth calculation is outright wrong like I mentioned.

Secondly, I have tons of accounts, I can't just add everything in my head to calculate my real net worth (accounts from multiple countries, investment accounts, etc etc).

I don't see what's the point of the net worth widget if the data it shows is just wrong. I know I can select which accounts to show in the widget, but that doesn't fix the fact that it also adds borrowed money (which is WRONG since that is already added in the respective transaction).

I know I can just enter the all spending section and enable the filter, I just don't understand the usefulness of the home widget.

**Comment by danielrincon-m** [comment]
+1 @jameskokoska 

Net worth calculation is just wrong, it is not taking into account the liability that the loan introduces. In the example given by @eduardvercaemer, the net worth should be zero. Please take a second look into this issue.

**Comment by ngocanhtve** [comment]
Yes, this issue needs to be addressed. When I lend some money, it disappears from my net worth. That is wrong because I did not lose that money, it is still mine and I will get it back. It should not be deducted from my net worth. Conversely, when I borrow some money, it is not mine and I have to pay it back someday, it should not be added to my net worth.
