### ISSUE TITLE
[Question] Where exactly is this synced in Google Drive?

### ISSUE THREAD

**Issue by FaridAhamat** [jameskokoska/Cashew#419]
I'm at this page:

![image](https://github.com/user-attachments/assets/79687386-9016-4473-b85d-a7a75ecc371d)

Clicking Backup seems successful, although I'm not quite sure what it does. It seems it creates a .sql file, but where does it create it? The word `backup` to me implies that my data is backed up to my GDrive, but I can't find exactly where the physical file is.

I am aware that I can download that .sql data to my machine. I was just under the assumption that backing up in this page means creating the .sql file and putting it into my GDrive, in which I can't find the location. 

Please forgive me if my assumption is wrong or if this question is dumb.

**Comment by jameskokoska** [comment]
Please see the FAQ
https://cashewapp.web.app/faq.html#delete-hidden-cashew-sync-data
