### ISSUE TITLE
When Duplicating Common Transactions the Displayed Currency is Sometimes Incorrect

### ISSUE THREAD

**Issue by Michael152843** [jameskokoska/Cashew#420]
**Describe the bug**
If you access the Most Frequent Transactions list (long pressing the + button) and try to duplicate a transaction with its amount updated (long pressing the transaction), the currency on the Enter Amount bottom sheet always shows your Primary currency, even if the currency of the original transaction was different. The currency of the newly created transaction is correct though, so it's merely a UI issue.

When duplicating transactions, the currency on the Enter Amount bottom sheet should be the same as the currency of the transaction that is being duplicated and not the Primary currency

**How to reproduce**
Long press the + button > long press a transaction made with a currency different from your Primary currency

**Details**
 - Device: Android
 - App Version: 5.4.1+414

**Comment by jameskokoska** [comment]
Fixed here: https://github.com/jameskokoska/Cashew/commit/126d1b610971a3b5b7957489273944758d92c172
