### ISSUE TITLE
[Feature Request] Copy/Paste the Amount of Transfer Transactions

### ISSUE THREAD

**Issue by Michael152843** [jameskokoska/Cashew#422]
**Is your feature request related to a problem? Please describe.**
Currently it's not possible to copy/paste the amount when creating Transfer transactions, though this function is avaliable with other transaction types. Also, the calculator doesn't seem to work with Transfer transactions either.

**Describe the solution you'd like**
It would be really useful to those of us who have to often exchange currency to be able to copy/paste the amount, as well as to use the calculator functions

**Comment by jameskokoska** [comment]
Added here: https://github.com/jameskokoska/Cashew/commit/91c0ad3b1abc628c515ffff14afad1fc1d9caf95

Calculations are already working as expected
