### ISSUE TITLE
[Feature Request] Possibility to Create a Cluster of Transactions

### ISSUE THREAD

**Issue by Michael152843** [jameskokoska/Cashew#423]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be a very nice addition to the app to be able to quickly create a group of transactions (something which can already be done with the App Urls but not within the app itself). This function can be added to a long press + button menu. Some really common examples of the transactions that almost always come in groups are: Purchase + Cashback, Money Transfer + Fee, Currency Exchange + Fee, Restaurant + Tip and so on. 

Of course one could try to copy this kind of transactions from the previous day but it takes time to navigate to a specific day when the transactions were made and also it's not currently possible to duplicate a group of transactions for current time by long pressing the Duplicate menu item.

**Comment by jameskokoska** [comment]
Related to https://github.com/jameskokoska/Cashew/issues/65
