### ISSUE TITLE
[Feature Request] Multiple Titles for a Transaction

### ISSUE THREAD

**Issue by Michael152843** [jameskokoska/Cashew#427]
**Is your feature request related to a problem? Please describe.**
Often we need to add some additional information to a transaction, such as the name of a person we're paying for, a place, etc. The quickest way to do that is by using Titles (E.g. you can create a Title "Dining • Person" for "Dining" category), but since each Title requires a category, you have to create every possible combination of the pieces of information (names/places, etc.) for every single Category that you might want to use this information with. Also, you have to constantly update all of those Titles in order to add new pieces of information.

**Describe the solution you'd like**
A possible solution to this issue is to allow multiple Titles for a transaction. For example, when creating a transaction you could add a categorised Title "Dining", just like we do now (or simply select a corresponding category), but then also add some uncategoriesed Titles, e.g. "Person" & "Birthday" to get a combined title "Dining • Person • Birthday". Next time, you could use those uncategorised Titles with other categories (e.g. "Gift"). This way you would need just a few Titles that you could quickly concatenate in order to add all the necessary information, without the need of creating lots of Titles or adding notes all the time.

**Comment by jameskokoska** [comment]
Only one title is supported per transaction. You can add notes and apply filters if you require more details.

**Comment by MohammadShabib** [comment]
Actually no, as explained here
https://github.com/jameskokoska/Cashew/issues/466#issuecomment-2408623453
