### ISSUE TITLE
[Feature Request] Stack Lines in Budget History Graph

### ISSUE THREAD

**Issue by tadejensen** [jameskokoska/Cashew#429]
**Is your feature request related to a problem? Please describe.**
The budget history line graph with a line for each category looks cluttered to me, with overlapping lines and the lines at the bottom being indistinguishable from one another. Furthermore, the vertical dashed line that appears when tapping is misleading, as its height from bottom shows the category's value, while the category's colour is only shown down to the next line. Also the upper Y limit of the graph seem to be given by Ymax of the category with the highest Y value, the total-line above is out of frame.

**Describe the solution you'd like**
Stack the category's lines on top of each other.

**Describe alternatives you've considered**
Leaving the graph as is, where every point has the "correct" value on the Y axis.

**Comment by jameskokoska** [comment]
Because each category's total is independent, stacking the total becomes misleading (i.e. the total amount of the category on top would be incorrect on the y-axis for that category)
