### ISSUE TITLE
[Bug] "Sign-in error" every time I open the app.

### ISSUE THREAD

**Issue by bagarwa** [jameskokoska/Cashew#431]
**Describe the bug**
Whenever I open the app on my phone, I get this error banner at the top - 

> Sign-in error
> Check your connection and try again.

So I go to settings and sign-in again. That works. I do my thing and switch to other app, or leave the phone etc. After a while, when I launch the app again, again "sign-in error".

I cleared the app cache, hoping that'll help. It didn't.

**How to reproduce**
As described above. 

**Screenshots/videos**
![Cashew](https://github.com/user-attachments/assets/f0e41907-5580-460c-9c42-ddd072e6be6e)

**Details**
 - Device: Pixel 7 Pro, running Android 15 QPR Beta 2.
 - App Version: 5.4.1

**Comment by jameskokoska** [comment]
Unfortunately, there is an issue with the beta of Google Play Services. Please remove the beta installation from your phone and install the stable release.  https://play.google.com/store/apps/details?id=com.google.android.gms

**Comment by jameskokoska** [comment]
Google has pushed these changes over to the main release of Google Play Services, however a discussion has popped up on GitHub about a fix. This has been applied here in Cashew: https://github.com/jameskokoska/Cashew/commit/f82ecc17b230ae2f60bcc0de17baba765f5409d1

Reference: https://github.com/flutter/flutter/issues/155490 and https://github.com/flutter/flutter/issues/155429
