### ISSUE TITLE
[Feature Request] Deploy 'Web App' via docker-compose

### ISSUE THREAD

**Issue by K-J-VV** [jameskokoska/Cashew#432]
**Is your feature request related to a problem? Please describe.**
Would really like to be able to deploy the Web App as a docker container

**Describe the solution you'd like**
Either publishing container image via dockerhub or github and including an example docker-compose file

**Comment by jameskokoska** [comment]
Cashew doesn't have a backend or any other components so there is no need for a docker container.

**Comment by K-J-VV** [comment]
The idea is to be able to serve the Web App version from a home server (e.g., raspberry pi) so that the budget can be accessed from the browser of any devices on the network without having to install the app on each device wanting to use it (data would be synced across devices via something else, like Syncthing)

**Comment by jameskokoska** [comment]
See https://github.com/jameskokoska/Cashew/issues/340 and https://github.com/jameskokoska/Cashew/issues/84

**Comment by K-J-VV** [comment]
Ahh did not see those; thank you for the info

Really like the design of Cashew but would need access via webpage/WebApp & not comfortable uploading personal data to https://cashewapp.web.app/ . Ideally would be able to just spin up a docker-compose file to host the WebApp at home, but seems thats not possible (i've been trying myself to create one but not able)

**Comment by jameskokoska** [comment]
All data is stored locally while using Cashew unless uploaded to cloud storage with Google Drive

**Comment by K-J-VV** [comment]
> All data is stored locally while using Cashew unless uploaded to cloud storage with Google Drive

Fair, but a problem with how things are set currently is what if someday you/the hoster of the current website decides to stop for whatever reason? 

Providing an option for users to self-host the WebApp (https://budget-track.web.app/) would eliminate any concern of that. Also from an self-hosting/open-source perspective I'm sure implementing a docker-container would only promote adoption/use of what you've made (which again, seems **really** good imo). 


Just providing perspective as someone who wants to use Cashew, but unfortunately will not unless (or until...) there is a way for me to use the WebApp without depending on external sources.
