### ISSUE TITLE
Start date of month

### ISSUE THREAD

**Issue by IamRezaMousavi** [jameskokoska/Cashew#433]
**Is your feature request related to a problem? Please describe.**
We need this option to use Cashew with another calendars (like work calendar or ...)

**Describe the solution you'd like**
Change start date of month

**Describe alternatives you've considered**
[A clear and concise description of any alternative solutions or features you've considered.]

**Additional context**

‌Main Page | Settings
--- | ---
![Screenshot_20240922_113700_com ivy wallet debug_edit_44917557416582](https://github.com/user-attachments/assets/f7cc28f8-c639-4e33-bc08-1522e179601c) | ![Screenshot_20240922_112959_com ivy wallet debug_edit_44901742978564](https://github.com/user-attachments/assets/b98ec766-5952-42d4-a02e-49c3901a1f15)

**Comment by Anu6is** [comment]
This is already possible by changing the start date of the `Period Cycle`. 
- Open the details page for an account
- Selecting the current date range will bring up a `Select Period` menu 
- Modify the `Cycle` option to match your intended range (every 1 month | beginning September 22)

**Comment by IamRezaMousavi** [comment]
> This is already possible by changing the start date of the `Period Cycle`.
> 
> * Open the details page for an account
> * Selecting the current date range will bring up a `Select Period` menu
> * Modify the `Cycle` option to match your intended range (every 1 month | beginning September 22)

Yes It's Ok
But it still uses the normal calendar in the transaction tab

**Comment by jameskokoska** [comment]
The transactions tab follows the months as indicated by the labels. Thanks for providing the solution @Anu6is
