### ISSUE TITLE
[Question] Which should I do if I want something like piggy bank

### ISSUE THREAD

**Issue by l2eused** [jameskokoska/Cashew#434]
**Describe your question**
I want to make piggy bank for my new bag so I assume to use expense goal. If I complete my goal, what should I do next?

In my question means if any of goal complete, where money will go to? If I want to buy new bag as I says, can I tranfer all money in goal to track my shopping expense? How?

P.S I ask this because I try to explore goal feature but when I mock-up I'm completed goal, I don't know how to do next... all expense transaction already created so I can't simply and new shopping transaction for my new bag because it will double expense amounts. In this time, I think I using wrong use case right? but I don't know tbh...

**Comment by jameskokoska** [comment]
I'm not quite sure I understand. See https://github.com/jameskokoska/Cashew/issues/185 for separating amounts.
After a goal is complete, you can archive the goal if you wish - but otherwise there is no need to do anything.
