### ISSUE TITLE
Copying a Monthly Budget

### ISSUE THREAD

**Issue by etgonehomie** [jameskokoska/Cashew#436]
**Describe your question**
Is there a way to copy this month's budget (and all it's spending allocations) to the next month?

For example, I created a September 2024 budget to spend $1,000. I allocated $400 to Food and $600 to Bills. Is there a way to copy this allocation to October 2024 budget?

**Comment by jameskokoska** [comment]
There is no way to copy a budget. However, budgets of a period auto cycle to the next time frame.

**Comment by etgonehomie** [comment]
> There is no way to copy a budget. However, budgets of a period auto cycle to the next time frame.

Could you elaborate one this? I'm not quiet understanding. So let's say I create a budget from 9/1 - 9/30 with the $1000 (split by $400 food, $600 bills). 

Would there be an automatic new period cycle from 10/1 - 10/31 with the same $1000 (split by $400 food, $600 bills)?

**Comment by jameskokoska** [comment]
Yes, budgets automatically reset after each cycle. See the FAQ for more information: https://cashewapp.web.app/faq.html#creating-a-budget-guide
