### ISSUE TITLE
[Feature Request] Option to add Number of Items and Price per Unit for Certain Entries

### ISSUE THREAD

**Issue by UMA1R-01** [jameskokoska/Cashew#439]
**Is your feature request related to a problem? Please describe.**
When I add a new item, there's no way to enter the number of units or items. I also can't enter a price per item and have it calculate the total cost for me. Yes, we can write all that in the "Description", but having the "Quantity" and "Price per unit" categories will make it more efficient, I think.

**Describe the solution you'd like**
I’d like an option to enter how many items I bought and their price per unit (for entries where these are applicable). The app should then multiply these together to show the total cost automatically.

**Describe alternatives you've considered**
I could keep doing the math myself and just enter the total, but it would be easier if the app did this.

**Additional context**
Including this feature would streamline expense entry, especially for users who frequently purchase items in bulk or with varying quantities. It would make the app more comprehensive and practical for everyday use.

**Comment by jameskokoska** [comment]
There are currently no plans to track quantity, I've thought about this before but from a statistical summary and tracking perspective, it is outside the scope of this application and complicates the user experience. You are free to use the notes section and respective filters to aid in more dynamic detailed tracking.
