### ISSUE TITLE
[Feature Request] Currency Acronyms to Distinguish Accounts with Identical Names

### ISSUE THREAD

**Issue by Michael152843** [jameskokoska/Cashew#442]
**Is your feature request related to a problem? Please describe.**
Often we might have multiple account with different currency open in the same bank. Right now if we create two accounts (even with identical names), they are easily distinguishable on the `Add Transaction` screen because of the currency acronyms included in parenthesis (e.g. `Bank (USD)`, `Bank (EUR)`). 

However, this is not the case in other parts of the app (e.g. Balance Correction notes and titles, account lables, etc.) and it becomes difficult to tell the difference between different currency accounts that share the same bank name.

The logical solution would be to simply include the acronyms in the account names themselves, but in this case it's the `Add Transaction` screen where they look weird (e.g. `Bank (USD) (USD)`, `Bank (EUR) (EUR)`)

**Describe the solution you'd like**
The solution might be to automatically add the currency acronyms to the accounts with identical names in those parts of the app where they are not distinguishable, just like it's done on the `Add Transaction` screen

**Comment by jameskokoska** [comment]
Added here: https://github.com/jameskokoska/Cashew/commit/56ebccbe5ba1014a5f99febf957be2bc0ca4f99e
A new setting allows users to toggle whether these labels should appear when multiple accounts exist with different currencies
