### ISSUE TITLE
[Question] How can I see Upcoming repetitive transactions for current and next month only

### ISSUE THREAD

**Issue by mannish-kumar** [jameskokoska/Cashew#445]
First of all Thank You for a great App. 

Can you please help me with the below?

I have two EMI for 3 months each. One starts in October and ends in December month.  And the other starts  in November month and ends in Jan 2025. 

I have created these as repetitive transactions and set the start date as 2nd Oct for the 1st and 2nd November for the 2nd EMI.

Let's say each EMI is for $10.  The upcoming transaction tile shows the total of both  i.e $20.
I just want to see the total of  any upcoming unpaid transactions for current month +  upcoming for next month.  So basically it should show September month unpaid upcoming  + October month upcoming and not November month. In my case it should should as $10 .

How can I achieve this?

![Screenshot_20240926-202229_Chrome](https://github.com/user-attachments/assets/8f58b3b9-ca4d-40cd-8053-58789d6cd4d9)
![Screenshot_20240926-203009_Chrome](https://github.com/user-attachments/assets/d3be683d-c1cd-44b5-9fa7-15a11c2d4ad8)

**Comment by jameskokoska** [comment]
On the Scheduled transactions page, it will show the total of all upcoming transactions. You can customize the filters for the homepage total to a cycle of your choice if you wish:

![image](https://github.com/user-attachments/assets/e747c1b7-fa5b-4edd-9cb2-7724b886aea4)

**Comment by mannish-kumar** [comment]
Thank You very much. 
I am able to achieve it by setting it to cycle every 2 months starting from September 1.
