### ISSUE TITLE
[Bug] Cannot sign in via Google on web app

### ISSUE THREAD

**Issue by Lorograch1** [jameskokoska/Cashew#446]
**Describe the bug**
While trying to sign-in via google on https://budget-track.web.app/, I'm getting an error saying "Check your connection and try again" but there is nothing wrong with my connection.

**How to reproduce**

1. Clicked on Sign In with Google
2. Clicked on the relevant google account via the pop-up
3. Received a banner saying `"Sign-in Error" "Check your connection and try again"`

**Screenshots/videos**
<img width="252" alt="{4D25BC3A-1A57-4ACA-93B9-55CD192D9466}" src="https://github.com/user-attachments/assets/7036153f-aa0d-4898-99ab-129ea73009af">

**Details**
 - Device: Windows Laptop | Firefox version 130.0.1 (64-bit)
 - App Version: Web App

**Additional notes**
N/A

NOTE TO THE SUBMITTER
Reporting bugs is important for maintaining the app. Thank you for helping make the app a better experience for all!

**Comment by jameskokoska** [comment]
I just tested it myself and I am able to login. Please make sure you allow the necessary permissions for your Google account

**Comment by eldrig0** [comment]
@Lorograch1  I am also having the same issue on Mac M1, running Firefox 134.0.2 (aarch64), I would assume it's a Firefox-specific issue.  Did it work for you?
