### ISSUE TITLE
[Bug] Weird Cumulative Graph Behavior

### ISSUE THREAD

**Issue by Radwan-Albahrani** [jameskokoska/Cashew#449]
**Describe the bug**
the value points on the graph do not match the list shown below the graph, and I am unsure where it’s getting its numbers. Filters seem to affect the graph but the calculations are still different for the graph and the list

**How to reproduce**
Have a good transaction history.
Go to spending page.
Check cumulative history graph.

**Screenshots/videos**
![image](https://github.com/user-attachments/assets/2f719ce4-f076-451f-a3f6-c312e421a425)

**Details**
 - Device: iOS 18.1 beta 5
 - App Version: [e.g. 5.4.2+415]

**Comment by jameskokoska** [comment]
I will need more information and a minimal reproducible example

This bug report is too vague.

**Comment by jameskokoska** [comment]
Fixed here: https://github.com/jameskokoska/Cashew/commit/76b042934b77a92fa88c488e19b91497d92da4f5
