### ISSUE TITLE
Duplicated associated titles in category if autoadding is enabled

### ISSUE THREAD

**Issue by bicolino34** [jameskokoska/Cashew#45]
Cashew version: 4.8.8+250, db-v44
There should be a check. If the title is already in the associated titles of the category, it shouldn't be added.
As you can see on the image, there are a lot of duplicates for "трамвай" since I often add expense with such name.
![Screenshot_20231123_131112.jpg](https://github.com/jameskokoska/Cashew/assets/58372007/a7e9b16c-57ef-46b5-90a0-7501706c6d2d)

**Comment by bicolino34** [comment]
I just tried adding two expenses with title "Тестова витрата". It got duplicated. When i tried the same thing with title "Test" it didn't duplicate.
Looks like the problem is in the Cyrillic titles. Also, autofilling of info (whether it expense or income and category) doesn't work properly because of this. It suggests autofill only for certain titles, but not for every one that is in the associated title list.
Steps to replicate:
1. Add new expense
2. Set title in Cyrillic script (e.g. "Тест")
3. Set any category and input any amount of money
4. Save the expense

**Comment by jameskokoska** [comment]
Thank you will look into it! "Тест" was able to recreate the issue but the original example "трамвай" was not for some reason, at least on my end. Now that I can recreate it, I can definitely look into a fix :)

**Comment by jameskokoska** [comment]
Fixed here: https://github.com/jameskokoska/Cashew/commit/dd29bb4bb9ee4a43e76708a793f2265f6eef678f#diff-31cbe1b5db0e98885b59434814b637c0d7234f50a6b288a531bcf2cc008eb21b

The database queries takes this type of text into account now
