### ISSUE TITLE
[Question] Borrowed from friend

### ISSUE THREAD

**Issue by l2eused** [jameskokoska/Cashew#450]
**Describe your question**
I want to know what option should I use in this case.
I have problem with my bank account, so I borrowed money from my friend and want to give him back later.
I suppose to use Borrowed option but it isn't fit my case. When use borrowed, it will temporary increase amount in account and back to normal when I set settle.

I want to mark amount and reduce my amount.

Example. using borrowed option
```
account net worth: x$
when set borrowed 15$
account net: x+15$ (temp)
when set settle, account net: x$

which should be
account: x$
set borrowed: 15$
account net: x
set settle, account net: x-15$
```

It might use upcoming to suitable my case, but I'm not sure then what's borrowed used to.

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating questions. Duplicates will not be addressed again.**
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jameskokoska** [comment]
You can use the long term loan feature to select which account deductions and repayments are taken from for each transaction entry. If you don't want the initial loan deduction to be apart of your main account, you can use a separate account as outlined by the FAQ: https://cashewapp.web.app/faq.html#set-budget-no-change-balance

Also see: https://github.com/jameskokoska/Cashew/issues/350
