### ISSUE TITLE
Failed to import multiple CSV files

### ISSUE THREAD

**Issue by pavelica-agile** [jameskokoska/Cashew#452]
I am new to CashEx
I was trying to import some data from an old accounting system.

I:
1. Created 2 bank accounts.
2. I created a CSV import file with transactions from my old system.
3. I imported the data.
4. It all looked good.
5. I created a CSV import file with transactions for the 2nd bank account.
6. I imported the file. 

It FAILED: 
1. There were NO transactions in the 2nd bank account.
2. CashEx imported AGAIN the 1st CSV file.
3. When listing the transactions of the 1st back account, there were DUPLICATES of all transactions.

Was there any memory of my previous import?

**Comment by jameskokoska** [comment]
I will need more information in order to replicate the issue. Just tested and CSV importing works as expected. Closing until more information is provided.
