### ISSUE TITLE
[Feature Request] Applink unable to post transaction with Biometric lock 

### ISSUE THREAD

**Issue by tiniwings** [jameskokoska/Cashew#455]
**Is your feature request related to a problem? Please describe.**
Applinks are unable to post transactions with Biometric lock enabled. 

Applink is able to open the app, but it gets stopped at the biometric screen page. 

**Describe the solution you'd like**
Is there any wag to get bypassed biometric lock for Applink transactions? 

**Describe alternatives you've considered**
[A clear and concise description of any alternative solutions or features you've considered.]

**Additional context**
[Add any other context or screenshots about the feature request here.]

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating feature requests. Duplicates will not be addressed again.**
Not all feature requests will be considered. This budget app was created with careful thought given to each feature's usability and prevention of feature overload. As you use the app, you will discover possibly related useful features and that may not be obvious right away. 
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jameskokoska** [comment]
If the application is locked, the integrity of the database should be maintained until unlocked.
