### ISSUE TITLE
[Bug] Excluded accounts' transactions being used in pie chart

### ISSUE THREAD

**Issue by ch3thanhs** [jameskokoska/Cashew#457]
**Describe the bug**

After long pressing and unchecking the account that I don't want to show up in the pie chart, the transactions of that account still show up.

**How to reproduce**

1. Add multiple accounts
2. Add transactions
3. Enable pie chart
4. Long press on the pie chart and exclude any one account
5. The transactions of the excluded account are still being used in the pie chart

**Details**
 - Device: Poco F4
 - App Version: 5.4.4

**Comment by jameskokoska** [comment]
Unable to replicate issue. Please provide more information. 

Closing until more information is provided.

**Comment by ch3thanhs** [comment]
Hi @jameskokoska, 

Apologies, I created this issue late at night and it looks like it's my fault.

Everything is working as expected!
