### ISSUE TITLE
[Bug] The main currency is showing up while correcting other currencies. 

### ISSUE THREAD

**Issue by navaneethnpk** [jameskokoska/Cashew#458]
![IMG_20241006_114252.jpg](https://github.com/user-attachments/assets/541af010-ff83-4dde-a289-9c2c0f99690a)

The main currency is showing up while correcting other currencies.

**Comment by Michael152843** [comment]
I think it makes perfect sense. All the calculations in the app seem to be displayed in the main currency (even when it comes to balance corrections). If you want to change that just select an account with the desired currency before you correct your balance.

**Comment by jameskokoska** [comment]
Fixed here https://github.com/jameskokoska/Cashew/commit/561247de23a34304db4fc5e0541e6975445cb584
