### ISSUE TITLE
[Question] Mobile and web app are not synced

### ISSUE THREAD

**Issue by dgm90** [jameskokoska/Cashew#459]
**Describe your question**
Hello. First of all, huge thanks for the app, it is truly amazing! What I love especially is how it manages different currencies. So, thanks a lot again!

I've recently discovered, that I have a slight discrepancy between my iOS app and the web app. I've managed to find a 'problematic' transaction, which was a repetitive one. I've removed it from both devices and created it manually and the totals become equal. However, I can still see that the number of transactions is different.
**Web app**
<img width="330" alt="image" src="https://github.com/user-attachments/assets/d0f2fb9b-170f-44d0-843f-88372a5975f6">

**iOS**
![IMG_3C1151209A63-1](https://github.com/user-attachments/assets/7db710fb-affc-41d7-adbe-2c7927b244d5)

The totals are the same, however the transaction count is different.
Would you be able to tell me please how I could sanitise that? 
Thanks.

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating questions. Duplicates will not be addressed again.**
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by Anu6is** [comment]
Does it not resolve itself if you manually sync each device in succession?

**Comment by jameskokoska** [comment]
To resync both clients, create a backup on one device that you want as the official "sync" and restore it on the other. This will ensure all data is exactly the same on both devices. Note: Restoring a backup will overwrite current data.
