### ISSUE TITLE
[Bug] Cursor forcefully jumps to end of line when entering a transaction's description in Enter Title modal

### ISSUE THREAD

**Issue by davristiadi** [jameskokoska/Cashew#46]
**Describe the bug**

After the latest update, when entering a multi-line description to Enter Title modal of a new transaction, the cursor would unexpectedly move to the end of the line, as you can see in the attached video. This bug seems to only occur in the Enter Title modal.

**How to reproduce**
1. Record a new transaction.
2. Write something on the first line of description.
3. Then enter a new line in the description and type something.
4. Go back to the previous line and write something, then the bug would occur.

**Screenshots/videos**

https://github.com/jameskokoska/Cashew/assets/24604237/bb465915-3d27-4df8-afc3-320fbe5a4d57

**Details**
 - Device: Macbook M1 Pro 2021, Mac OS Sonoma 14.1.1
 - App Version: 4.9.4+256

**Comment by jameskokoska** [comment]
Thank you for letting me know! Appreciate the details

Fixed here: https://github.com/jameskokoska/Cashew/commit/8cde48a7788a2b6ffa4bc48e2103213314c25ed2#diff-454a49e5837b7b852937584398d073d50b3dd37f08e362439b7534572e939818R2338
