### ISSUE TITLE
[Feature Request] Swipe to Quickly Change Date on Add Transaction Screen

### ISSUE THREAD

**Issue by Michael152843** [jameskokoska/Cashew#462]
**Is your feature request related to a problem? Please describe.**
Often, users may want to quickly adjust the date of a single transaction, typically by moving it one day forward or backward. Instead of opening the date picker each time, I suggest a quicker method:

**Describe the solution you'd like**
When a user swipes right over the date on the `Add / Edit Transaction` screen, it moves one day backward. When a user swipes left, it moves one day forward.

**Comment by jameskokoska** [comment]
Unfortunately, the UI for the date picker doesn't make sense to have swipe gestures associated with it. I don't see a common use case of users needing to adjust the date of a transaction by just one day either (there will usually be more adjustments needed when editing the date), and the calendar page can be used to add a transaction on any day if needed. It isn't a good idea to have swipe gestures in an unintuitive manner in the UI, as it can create a confused user experience. Swipes should be saved for scrolling on this page or navigation.
