### ISSUE TITLE
[Feature Request] Export/Create reports in PDF/CSV format.

### ISSUE THREAD

**Issue by i-DanialAhmed** [jameskokoska/Cashew#463]
**Is your feature request related to a problem? Please describe.**
Often, we need to create reports for specific accounts to share data externally. Currently, the only option is to take screenshots of transactions, which is not efficient.

**Describe the solution you'd like**
I would like to see an option to export account data to PDF or CSV formats, making it easier to generate and share reports.

**Comment by jameskokoska** [comment]
Duplicate of https://github.com/jameskokoska/Cashew/issues/400

**Comment by jameskokoska** [comment]
Duplicate of https://github.com/jameskokoska/Cashew/issues/400
