### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by ericmlowry** [jameskokoska/Cashew#470]
**Is your feature request related to a problem? Please describe.**
I update the value in investment accounts as transactions but it's awkward to find and use the account's balance corrections and then change the category so that the transaction is visible. It is not exactly a "correction" though it is fair to say it isn't a transaction either.

**Describe the solution you'd like**
Another field in the add transaction page where the total of the account selected is listed and editable.

**Describe alternatives you've considered**
Maybe a separate transaction type called Update with the same field?

**Comment by jameskokoska** [comment]
Hi there! I’m not quite sure I understand. The account balance correction is separated in the UI because it is different from adding a transaction. It is more related to an account itself rather than an actual transaction amount.
