### ISSUE TITLE
[Bug] Incorrect transaction account and recurring payment date after syncing or refreshing Cashew Web

### ISSUE THREAD

**Issue by 7HE-W0R1D** [jameskokoska/Cashew#472]
**Describe the bug**
I created a backup that I know contains all correct transactions and account total, and after I restored it manually, transactions were placed in wrong accounts and recurring payment was placed in wrong date.

**How to reproduce**
- Track budget normally on web
- Turn on sync on every change in settings
- Make sure everything is correct, especially the account total
- Close cashew and reopen it
- Pull the latest backup
- Check the account total again

**Screenshots/videos**

**Details**
 - Device: Linux Chrome 129 Flatpak
 - App Version: 5.4.0+413

**Additional notes**
I know this isn't a partial backup or a backup in the midway of my budget since I have 3 accounts, A, B, and C. 
I added my transactions in the order of A -> B -> C. But in my backup, the total in account A and B is wrong, but C is all correct.

I went through my transactions and discovered two errors causing this: one transaction was misplaced from account A into B, and one recurring payment disappeared for last month.

However, both these transactions occurred before my last backup, meaning that they were correct in previous backups, and somehow got messed up in the latest backup.

**Comment by jameskokoska** [comment]
Hi there! Thanks for letting me know about the issue. This is a common issue with Cashews syncing, and there is code that patches this issue already by ensuring a key is predictable for repetitive transactions so the original transaction is overwritten when syncing if duplicated or updated. I would need specific step by step instructions for recreation and a minimum reproducible example preferably with the logs and  transaction ids of the duplicated incorrect transactions. Closing for now, as a more detailed reproducible example is needed. 

If data becomes out of sync, it is recommended to restore a backup on all your devices from a device of truth to ensure data is identical. Keep in mind restoring a backup will replace all data currently saved on that device.
