### ISSUE TITLE
[Feature Request] Option for Donations

### ISSUE THREAD

**Issue by Michael152843** [jameskokoska/Cashew#476]
**Is your feature request related to a problem? Please describe.**
Since this app has really improved my financial habits (and I'm sure there are plenty of us) and it is being actively updated, I'm ok with donating some amount from time to time to support the development. However, since I've already bought a lifetime premium, there's no way for me to do so through the subscription and I found no donation option in the app.

**Describe the solution you'd like**
Consider including such an option somewhere on About page

**Comment by jameskokoska** [comment]
Glad that app helped you out :)
Google Play has limitations on linking outside donation sites, however I can consider adding an extra option to support on the Cashew Pro page once lifetime has been purchased through in app purchases with Google Play and the iOS App store. For now, my Ko-Fi page is active and accepting donations: https://ko-fi.com/dapperappdeveloper

**Comment by Anu6is** [comment]
Using GitHub sponsor may also be an option. Easily discoverable for those that find you on GitHub.
