### ISSUE TITLE
[Feature Request] Option to Go to a Specific Day from Transaction Search Page

### ISSUE THREAD

**Issue by Michael152843** [jameskokoska/Cashew#477]
**Is your feature request related to a problem? Please describe.**
I often search for a specific past transaction using different filters on the `Transaction Search` page. Once it's found, I almost always want to go to the actual day the transaction took place to get more context and to see what else was going on.

Right now, in order to do so we have two options:
1) Remember the date, clear the filters, go to `Select range`, select Start end End date, tap OK.
2) Remember the date, go to the `Calender Page`, scroll to a particular past month and find the day.

**Describe the solution you'd like**
It would be great if there was a way to go to a specific `Calendar Page` day right from the `Transaction Search` page, for example (but not necessarily) by pressing the date of interest:

![Screenshot_20241022_103841](https://github.com/user-attachments/assets/2f5001bd-014a-48b0-9e84-36761c45ac5c)

**Comment by jameskokoska** [comment]
That's an interesting idea, however, I don't think it is that intuitive. The date banner is small and created for informational purposes, not interactivity. Additionally, if the user taps a day in the past opening the Calendar page that is behind the Cashew Pro popup (i.e. a past month) it's not a pleasant user interaction.

If you want to see all transactions on a specific day, you can actually search that day and it will show you the transactions. For example: typing "September 25" will display all transactions on that day. No need to set a time range filter.

**Comment by Michael152843** [comment]
> If you want to see all transactions on a specific day, you can actually search that day and it will show you the transactions. For example: typing "September 25" will display all transactions on that day. No need to set a time range filter.

I didn't know about this method and it works best
