### ISSUE TITLE
[Question] Savings

### ISSUE THREAD

**Issue by dlastnoel** [jameskokoska/Cashew#481]
I just wonder, is savings still considered as income? When adding transactions, basically there are two choices, the expense and incoming. I kinda feel like savings is still different from income. What do you think? How do you add your savings as transaction, is it expense or incoming or do we need another type for savings separately? TIA. Thank you so much for this amazing app btw!

**Comment by jameskokoska** [comment]
Yes savings would be income if it’s a positive polarity transaction. If you want to track savings towards a goal, you can make use of Goals within the app.

**Comment by dlastnoel** [comment]
Thanks!

**Comment by dlastnoel** [comment]
Follow-up question, how about for investments, which more suitable between income and expense?

**Comment by jameskokoska** [comment]
Feel free to use whichever suits your needs better or makes the most sense to you. Cashew is designed so there is no correct way of doing something. It is just a tool that is used to track transactions.

**Comment by dlastnoel** [comment]
Thanks!

**Comment by fravel77** [comment]
@dlastnoel I create a dedicated account for "Savings". Savings for me is whatever I put aside in financial products that can increase the money I initially put on them. It can be stocks, bond or simple bank accounts who gives you interests if you keep the money there.
When I decide to "save" some money, aka investing in these kind of products, I just make a Transfer from my Cash account (it is just a name but it represents cash plus money on my daily needs bank account) to the Saving account.

The open point then is how to handle the increase or decrease of value of your saving pot. Currently I am thinking to just adjust periodically (monthly or quarterly) the Savings account but I am not a fan of having several Account Balance correction spread in my transactions.

Another can be to create 2 ad hoc categories for this purpose: Investment Gain, Investment Loss. And setup them in a way they are off the radar and do not pollute all my daily life expenses and income transactions, I mean the ones that are the main purpose of using an expenses tracking app.
