### ISSUE TITLE
[Feature Request] Instead of first asking title ask for transaction type(expense/income/transfer) like ivy

### ISSUE THREAD

**Issue by myounus96** [jameskokoska/Cashew#485]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Instead of first asking **title** ask for transaction type(expense/income/transfer) just like in **ivy** wallet, first ivy asked for transaction type then next things. It will be more convenient to add transactions.

**Describe alternatives you've considered**
None

**Additional context**
None

_BTW thank you for this amazing cross platform app. I was using ivy since last couple of years but recently switched to iphone from android and ivy is not cross platform, then found Cashew, this is super awesome. Thanks again._

**Comment by jameskokoska** [comment]
The transaction type (expense or income) is already tied to the category automatically. If you want to add a transfer you can tap out of the add transaction workflow and select transfer, or long press the plus button and add a transfer directly (or through the edit account page)
