### ISSUE TITLE
[Question] I am not getting suggestions when writing on title.

### ISSUE THREAD

**Issue by myounus96** [jameskokoska/Cashew#486]
**Describe your question**
I went through issues and found out similar threads but looks like for them its just setting issue, I tried multiple combinations of settings related to title we have in app but still not getting the suggestions.

**Comment by jameskokoska** [comment]
Sorry I’m not sure I understand the issue. It seems to be working in the latest release, just tested. 
![IMG_1109](https://github.com/user-attachments/assets/d00aaa4d-fe2e-4443-baaf-77280fa1494b)

**Comment by myounus96** [comment]
Kinda a similar thing, but I think this is the the real bug I tried multiple times. Issue is we are just getting 1 suggestion. 
Like I have 2 old transactions having word "bill abc" and "bill def" now when I start creating new transaction and type "bill" I will just get 1 transaction. @jameskokoska
