### ISSUE TITLE
[Feature Request] Feature to Delay Income Transactions to Next Month Based on User-Defined Cut-Off Date

### ISSUE THREAD

**Issue by mauryapari** [jameskokoska/Cashew#488]
**Is your feature request related to a problem? Please describe.**
I get my income on the last days of the month, and I'm always frustrated when these income transactions are counted in the current month. It misrepresents my monthly financial situation and makes it difficult to manage my budget accurately.

**Describe the solution you'd like**
I would like a feature that allows me to set a flag in the app settings, enabling an option to select a specific date. Any income transactions added after this selected date should be counted for the next month rather than the current month. This would help ensure my income is accurately reflected in the correct monthly budget.

**Describe alternatives you've considered**
I have considered manually adjusting the income transactions at the end of each month (i.e., adding the transaction on the 1st of each month). However, this is tedious, complicates my budgeting process and can lead to errors in tracking my finances.

**Comment by jameskokoska** [comment]
I'm not quite sure I understand. If you want a transaction to count towards the next month, you will need to log it with the date of the next month. Each transaction's date is the date it's counted, you can set the date of a transaction to any date in the future.

**Comment by Anu6is** [comment]
@mauryapari Another option could be to change your monthly reporting period to reflect your income. 
For example, you month could encompass October 25th to November 24th instead of November 1st to November 30th.
