### ISSUE TITLE
[Feature Request] More recurrence configurations

### ISSUE THREAD

**Issue by CalamandreiLorenzo** [jameskokoska/Cashew#493]
**Is your feature request related to a problem? Please describe.**
I don't know how much a widespread problem is, but I have some transactions that are recurring but not fixed, for example every month on the last day of the month.
In my case by setting the transaction on the 31st of the month, the month after it may not be shown but slipped to the following month on the first day, or on the contrary if set on February 28, the month after it would not be the last day of the month but a few days Before.

**Describe the solution you'd like**
The only solution that comes to mind is to add other recurrence options such as:
- Repeat every x y (ex: "repeat every 1 month" or "repeat every 2 week")
- Repeat every y on day x (ex: "Repeat every month on the 15th day of the month" or "repeat every month on 1 of the month" or "repeat every week on 1 day of the week")
- Repeat every y on the last day (ex: "Repeat every month on the last day" or "repeat every week on the last day" or "repeat every year on the last day")

**Describe alternatives you've considered**
For the moment I have no other ideas on how to implement a solution, in case I will comment on the ticket 👍 .

**Additional context**
NA at the moment.

NOTE TO THE SUBMITTER
I apologize in case there is already another ticket present, I checked and I don't seem to have seen them.

**Comment by jameskokoska** [comment]
This is similar to and already addressed in https://github.com/jameskokoska/Cashew/issues/242
Related: https://github.com/jameskokoska/Cashew/issues/474

**Comment by CalamandreiLorenzo** [comment]
Thanks for the clarification, yes I had reported various examples including those already current to highlight the difference with the last point.

So the behavior that a monthly transaction does not go to the following month in case it is scheduled for the last day of the current one is wanted?
For example, a recurring transaction per month scheduled for October 31 is not reported on November 30, but on December 1, from that moment on it would remain linked to the 1 of each month and no longer to the correct day.
