### ISSUE TITLE
[Question]: Is it possible to add a feature to put Categories and its Sub Categories under Groups.

### ISSUE THREAD

**Issue by mannish-kumar** [jameskokoska/Cashew#494]
I want to put my Categories and its sub categories into 3 Groups like Needs, Wants and Desires.
This will help me to understand how much I spend on my Needs, Wants and Desires and help me to cutdown my expenses from Wants and Desires.

Currently, I have created Needs, Wants and Desires as Categories. But this way I am not able to precisely categorize my expenses.

For example: I have Needs as Main Category and under that I have created a Sub category Insurance. Insurance can be Medical or Vehicle. 
With the current approach, I have to add the Medical and Vehicle Insurance under the Insurance sub category. 
Insurance is just one of the example it can be even used for Utilities and Debt payments etc. which fall under Needs Category.

**Comment by jameskokoska** [comment]
Hi there! There are no plans to add any more depth to categories and subcategories (i.e. subcategories of subcategories) however, I suggest not creating a category for every different transaction type (A title can be used to differentiate the different types of insurances for example). 

To track needs and wants, you can create a “Added only” budget and add the transaction to the corresponding budget to track your spending for each. 

The way Cashew is designed, it allows you to track your expenses in whichever way makes sense to you. There is no right or wrong way to track your spending ~ whatever makes sense to you!
