### ISSUE TITLE
[Feature Request] More efficient home screen Android widget to add transactions

### ISSUE THREAD

**Issue by m0byn** [jameskokoska/Cashew#497]
**Is your feature request related to a problem? Please describe.**
No, not really a problem but more of an existing inefficiency. One could save at least one click.

**Describe the solution you'd like**
IvyWallet has the best widget to add transactions I can imagine. It only takes the size of two apps, and one is able to add and specify the transaction type in one click. See the picture here
![widget](https://github.com/user-attachments/assets/8edff4be-b958-4a48-9cad-9aa345e4deaa)

The smallest widget to add transactions right now is the plus button. However, one has to specify the transaction type every time when adding a transaction. 

So, I would suggest to provide a similar widget in order to maximize the efficiency when adding a transaction.

**Comment by jameskokoska** [comment]
Cashew’s “type” is already linked to the category itself by default - so I’m not sure how this saves a click when adding a transaction in Cashew.
