### ISSUE TITLE
More than one suggestion while typing title

### ISSUE THREAD

**Issue by subhashay** [jameskokoska/Cashew#50]
**Is your feature request related to a problem? Please describe.**
Some times it so happens that I  have 2 or more similar titles (eg: milk, milk + bread). Not sure what logic the app uses but most of the time I have to rewrite the title. 

**Describe the solution you'd like**
I think the suggestion space can accommodate at least 3 options instead of one. 

**Describe alternatives you've considered**
I generally click and if editing is needed I change it then and there.

**Additional context**
NA

NOTE TO THE SUBMITTER
Not all feature requests will be considered. This budget app was created with careful thought given to each feature's usability and prevention of feature overload. As you use the app, you will discover possibly related useful features and that may not be obvious right away. 
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jameskokoska** [comment]
Appreciate the suggestion! 

Titles with higher priority are ones at the top of the list. If you head to [More] > [Titles] you can rearrange the order. 

If more titles were shown when the user is creating a transaction, it will be too cluttered, especially with the on-screen keyboard
