### ISSUE TITLE
[Feature Request] Undo Action

### ISSUE THREAD

**Issue by rasot71** [jameskokoska/Cashew#501]
**Describe the solution you'd like**
As far as I am concerned, the addition of an "undo" popup message would be great.

**Additional context**
More specifically, when I delete a transaction, category or budget I would like a toast notification (5 seconds) offering an "undo" action. I am talking about the web app as well.
 
Sorry if I failed to describe accurately what I mean.
Thank you in advance!

**Comment by jameskokoska** [comment]
The activity log allows you to see a record of all changes and undo a deletion of a transaction

**Comment by rasot71** [comment]
Oh, I realize that now. I am a new user... Sooo well built tracker! Congratulations, once again!
