### ISSUE TITLE
[Feature Request] select when to enter  the title when creating new transaction 

### ISSUE THREAD

**Issue by hexman1999** [jameskokoska/Cashew#502]
I suggest adding option to select when title should appear when creating new transaction after or before entering the transaction amount

I find it easier to input the amount first then select category, and lastly add title if i want, sometimes i can't type words when i am hurry, and something i get confused and enter the amount in the title, the go back to edit

**Comment by jameskokoska** [comment]
From a Cashew standpoint this doesn’t make sense. The title is used to autocomplete the category for quick input of transaction day this is addressed here: https://github.com/jameskokoska/Cashew/issues/96

**Comment by hexman1999** [comment]
> From a Cashew standpoint this doesn’t make sense. The title is used to autocomplete the category for quick input of transaction day this is addressed here: https://github.com/jameskokoska/Cashew/issues/96. If it were to ask for the title last, the title autocomplete of a category would be irrelevant, which is one of the main points of increasing the transaction logging process. 

I don't mean to be last after selecting category

The order I mean is: amount then title then category if not auto completed

**Comment by hexman1999** [comment]
@jameskokoska
 please can you respond to my last comment 


usually when I add transaction i type the amount in the title instead , specially when adding more than one transaction at a time

Usually I am thinking about the amount then the title ex. 5$ for restaurant, 20 for repairing pc and so on, so when I enter the title i type the amount on it mistakingly so i have to go back and edit again and sometimes i forget the next transaction i add at that moment 

And as I said in the previous comment, to maintain title auto complete the order can be amount then titel then category if not auto selected, I suggest it to be a toggle in settings whether to ask for the amount first or the title in fast adding transactions

I wish you respond for that

Thank you and I really appreciate your work

**Comment by jameskokoska** [comment]
This has been added in the beta. You can now customize, rearrange and enable/disable, the "Add Transaction Prompts".

See #725 for Beta Testing instructions and information

![image](https://github.com/user-attachments/assets/fc8ed6a5-c71c-49ec-a47e-2403a893c655)
