### ISSUE TITLE
[Feature Request] option to exclude a selected recurring transaction 

### ISSUE THREAD

**Issue by hexman1999** [jameskokoska/Cashew#503]
I wish if there is an option to exclude some recurring transactions from my total, either to exclude the whole transaction with all recurrences or only single one in one cycle

**Comment by jameskokoska** [comment]
Duplicate of https://github.com/jameskokoska/Cashew/issues/172 or you can mark as Skipped for reoccurring transactions

**Comment by hexman1999** [comment]
> Duplicate of https://github.com/jameskokoska/Cashew/issues/172 or you can mark as Skipped for reoccurring transactions

But that button is not there for recurring
