### ISSUE TITLE
[Feature Request] faster multi select method and new methods

### ISSUE THREAD

**Issue by hexman1999** [jameskokoska/Cashew#506]
Tap and hold is a little bit annoying when multi selecting lot of transactions i wish the actions to be swapped

Holding for opening the transaction, taping for adding to selection

Or even add some multiselection options like these in musicolet player app

Like select between last two selections, select under, select above the current selection, or invert selection

**Comment by jameskokoska** [comment]
There are no plans to change the behaviour of selecting. For an intuitive user interaction, long pressing to select is the correct interaction. To quickly select multiple transactions you can swipe your finger to select more than one at a time.

**Comment by hexman1999** [comment]
> There are no plans to change the behaviour of selecting. For an intuitive user interaction, long pressing to select is the correct interaction. To quickly select multiple transactions you can swipe your finger to select more than one at a time. 

I mean even adding checkboxes after first entry is selected, this behavior is there in web version of the app also
