### ISSUE TITLE
High CPU usage with PWA

### ISSUE THREAD

**Issue by awaixjvd** [jameskokoska/Cashew#509]
I see very high CPU usage when the PWA app is used on laptop in chrome browser. It appears as soon the app is launched in a tab (before and after are negligible) and keeps at 90% or above as long the cashew tab is in focus. When the tab is changed, the CPU usage again goes down.

**Comment by jameskokoska** [comment]
Unfortunately this is a limitation of how Flutter runs web apps. Related to https://github.com/jameskokoska/Cashew/issues/9 

You can open an issue on the Flutter repository by identifying the issue with a minimal reproducible example.
