### ISSUE TITLE
[Feature Request] Event support or tagging

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#51]
Expenses are tagged (to events) for a trip. Then you will know the total transactions of the trip. And can close that event. There is a separate view area for transactions that are part of ongoing or closed events. For references, Money Wallet app has it: https://github.com/AndreAle94/moneywallet

Thank you for your attention!

**Comment by jameskokoska** [comment]
You can create an 'Addable' budget. Expenses added to this budget will be tagged and count towards a common goal. 

Keep in mind, this application isn't meant to replicate or recreate existing features in other apps. If another app suits your needs better, it is probably a better fit for your needs.

**Comment by ngocanhtve** [comment]
@jameskokoska Tagging or tagging events is a common and useful feature of expense recording, just as recording expenses or setting up a budget is a common feature itself too. That doesn't mean I want one app to copy another. Sorry if my presentation misled you that way.

Let me be clear, tagging an event is not the same as setting up a budget for that event.Setting a budget limits your spending to a predetermined level. As for events, there is no limit. We can use events to split bills later, the spending transactions is really not the same as setting a budget as suggest.

I honestly hope you take a look, event or simply tagging, useful for anything in recording everything, not just recording expenses.

Thanks for your attention!
