### ISSUE TITLE
Add Toman (تومان) to your currencies.

### ISSUE THREAD

**Issue by eiliatmr** [jameskokoska/Cashew#510]
Hi. I recently installed cashew on my device and i noticed that you dont have toman as a currency.

In iran, people use toman as their daily currency.
It has one less zero compare to IRR(iranian rial):

100,000 Iranian rial = 10,000 toman's

It doesnt have a certain icon or style to it.
They usually show it with "IRT" or "TOMAN"

You can search or ask any question if you have on this currency.

And yea, i assure u that persians use this currency as their daily exchange.

Thx for your time and your amazing project!

**Comment by jameskokoska** [comment]
Hi there! The currency list comes from the currency API: https://github.com/fawazahmed0/exchange-api so it will need to be included there to be in Cashew. However, you can already add custom currencies into the app to account for extra currencies not included in that API. See: https://github.com/jameskokoska/Cashew/issues/79
