### ISSUE TITLE
[Bug] Budget does not count if I assign money to a subcategory

### ISSUE THREAD

**Issue by ibombonato** [jameskokoska/Cashew#511]
**Describe the bug**
When I designated some value to a subcategory, it does not count on the budget itself. It only account if I budget for the category.

**How to reproduce**
- Create a budget with a category that has subcategories.
- Assign money from the budget to a subcategory
- Money will not count as budgetted. It only counts if I assign money to the main category.

**Screenshots/videos**
The budgetted value should be 305, not 200. And probably the category "Carro and transporte" should be setted to 105 besides 0.
![image](https://github.com/user-attachments/assets/18ac3f96-0765-4802-b30a-1c48ef7ae001)

**Details**
 - Device: WebAPP
 - App Version: ![image](https://github.com/user-attachments/assets/1368a4ba-f9c6-4aad-a37d-4f6ec13eec90)

**Additional notes**
[Any additional information can go here]

NOTE TO THE SUBMITTER
Reporting bugs is important for maintaining the app. Thank you for helping make the app a better experience for all!

**Comment by jameskokoska** [comment]
Hi there! That is intended. Subcategories category budgets total to the main categories total. Since they are a category of a category, they total to the hierarchy one above.
