### ISSUE TITLE
[Feature Request] Budget Feature - Periodic Based Monthly Savings/Expense

### ISSUE THREAD

**Issue by AkimErnest** [jameskokoska/Cashew#512]
**Budget Feature Suggestion for Cashew**

Could we add a feature that allows setting an overall budget while still enabling adjustments to specific savings or spending goals for different periods (e.g., each month)?

Example:

October 1 - 31: Goal to save $600
November 1 - 30: Goal to save $450

This feature would allow users to establish a main budget as a baseline, while easily adapting the savings target for each period—without needing to create a new goal each time. This flexibility would help users account for changes in their financial situations while keeping savings plans organized.

Additionally, this feature could enhance the accuracy of historical data by reflecting users’ actual savings and spending patterns. For instance, if a fixed budget of $600 is set, a $450 target for November might currently show as only 75% achieved, even though it fully meets the intended goal for that month.

**"I would like to commend you on providing a great solution for modern-day personal finance tracking."**

![image](https://github.com/user-attachments/assets/6337abd8-5ab7-4bad-b02c-cba154f462da)
![image](https://github.com/user-attachments/assets/896cf210-f99d-4132-a460-3d7d0aa71cd9)

**Comment by jameskokoska** [comment]
Thank you for the feature request! Unfortunately, this workflow is pretty complicated. Given that this app wants to support an intuitive and easy budgeting experience, the current methods of setting category spending limits, adjusting the budget total, or even creating multiple different budgets for different time periods supports this dynamic use case already
