### ISSUE TITLE
[Question] Labels regarding long-term loans in "Add Transactions" page

### ISSUE THREAD

**Issue by Noirium** [jameskokoska/Cashew#516]
[Question]
#287 somewhat covers my question, but the labels within the Add Transactions page are still present regardless if the loan was archived or not. Here's a presentation:

![Transactions](https://github.com/user-attachments/assets/2f84eec2-2362-46ba-97da-683737e95d5b)
![Labels](https://github.com/user-attachments/assets/496d3762-0138-4d20-91ae-3d0e36be5a6f)

As seen in the pictures, the long term loan is archived. However, the labels for that particular loan is still present. Such labels get grayed out in contrast to their non-archived counterparts, which tells me this is an intended feature (note: grayed out labels can still be used). I was wondering if there's a way to get rid of the labels altogether once the loans are settled? Even more so for archived loans, as time goes on the labeling will get very cluttered.

**Comment by jameskokoska** [comment]
See https://github.com/jameskokoska/Cashew/issues/260
