### ISSUE TITLE
[Feature Request] Prevent Unsaved Changes from Being Lost on Page Reload or Back Navigation

### ISSUE THREAD

**Issue by rasot71** [jameskokoska/Cashew#519]
Hello dear developer. I recently added a transaction and I misclicked the back button on my mouse so I had to add it again and write the title and comment so I thought a nice feature but i don't know how hard would it be to be added. 

I thought the implementation of a mechanism that prevents users from accidentally losing unsaved content (when adding a transaction) when they:
Reload the page or 
Navigate away (e.g., using the back button).

Proposed Solution:

Introduce a warning dialog or prompt (e.g., "Are you sure you want to leave this page? Unsaved changes will be lost.") whenever a user attempts to reload the page or navigate away while they are actively editing or writing content.

Thank you in advance for your time!

**Comment by jameskokoska** [comment]
This feature already exists. 
![image](https://github.com/user-attachments/assets/14bc0bdd-3e6e-4767-90a0-8c7b4d96fe51)

**Comment by rasot71** [comment]
I forgot! I am talking about the web app (on pc)

**Comment by enrique-lozano** [comment]
Hi @jameskokoska, don't know if this is the right place to put this but this is failing on web or basically in any device with a left navigation bar. I attach a video if useful:

https://github.com/user-attachments/assets/5fe9ae2f-3dd9-45b8-9b7b-3a1fbd7f737d


Basically you could click in the left navigator and go to any page without showing the modal. The modal is displayed instead if you click in the top left back button. I assume this is cause in the `main.dart` file you have the sidebar outside of the `Navigator` widget that you use for the rest of the app
