### ISSUE TITLE
[Feature Request] Partial loan repayment

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#52]
..

**Comment by jameskokoska** [comment]
Hi there, thank you for the suggestion!

If you need to track payments overtime, especially towards a common goal, create a goal and add transactions to it. Installment breakdowns are coming. See: https://github.com/jameskokoska/Cashew/issues/47

Collecting money from transfers is out of the scope of this app. Feel free to manually create balance correction transactions set as borrowed or lent money. I feel like it's not something that would be useful for the majority and just complicate the user interface and interaction. 

Closing for now, feel free to continue the conversation

**Comment by ngocanhtve** [comment]
@jameskokoska 
This is the reality of life, between two people there will be many transactions of borrowing money, repetitive, mixed. 

The previous loan collection transaction should be viewed as an equivalent transaction to the loan transaction, to be able to choose the right incoming or outgoing money flow. 

That's basic case, when you transfer money from an ATM account to lend some money to a friend, but when he repays it, he can meet you in person to give the cash.

Therefore, there needs to be a formal option for the transaction to collect money back into a cash account.

Actually I just want to make suggestions so that the application better meets actual usage requirements. But I don't say anything to make the application cumbersome, an application that I want to use for a long time.

**Comment by jameskokoska** [comment]
Hi again,

I'm going to reiterate that if you need to track payments towards a goal/set amount, the goals feature is the best fit. For your use case: if you need to collect money in amounts, creating an income (positive cashflow) goal is the best option. You can add cashflow as you gain it back (paid back from others) over a period of time. 

I am looking into renaming income/expense to positive and negative cashflow, especially for goals.

Goals will be and is the only way to track accumulated money over multiple transactions. In my opinion, adding different ways of tracking essentially the same thing will create unnecessary clutter

**Comment by ngocanhtve** [comment]
You North Americans' thinking is so different. It makes it difficult for Asians to use North American products. Goodbye to your app because I can't actually use it.

**Comment by jameskokoska** [comment]
I'm sorry to hear that, it does seem like this app isn't for you and there probably is another app that suits your needs better then! However, I'm open to discussing how you would like the implementation of a loans/borrowed feature implemented, but the way you are currently describing from my understanding - you can use goals to track your progress. I don't understand how another tracking feature would be of use.

**Comment by ngocanhtve** [comment]
I no longer have the patience to try to request features that so many apps out there have. I really want to bring those features into a beautiful open source application like Cashew. But it seems I was too hasty.

**Comment by jameskokoska** [comment]
No worries. I would appreciate it if you could let me know why the current goals implementation doesn't work for you and try to create a dedicated loans feature if I understand the shortcomings.

**Comment by ngocanhtve** [comment]
It's very simple because if you set a positive cash flow goal, it doesn't have a dedicated feature to link that positive cash flow to a specific individual who has to pay back the money they borrowed from you.

The goal feature also cannot manage as well as have a report and a detailed list of people who have a borrowing relationship with you.

Nor is it directly linked to the money lending transactions you have previously made. Positive cash flow in a given goal will not automatically end lending transactions, cannot show that person A or person B have fully repaid the amount they borrowed (after x repayments).

**Comment by ngocanhtve** [comment]
Right now, your Lent feature, when choosing to collect all the Lent amount, it also does not show whether the Lent transaction has been completed or not, there is no indicator to recognize that a transaction has collected all the Lent money. It's also not as if they paid you the money into ATM account (for example), if they paid you in ATM, but the application cannot have the option to enter that positive cash flow into the ATM account, then the actual balance of the accounts will not be correct.

**Comment by jameskokoska** [comment]
Thank you, appreciate the explanation! I can definitely look into an implementation that suits this need, I think I have a general idea. When I get the chance, I can debrief you with my thoughts of its implementation.

**Comment by jameskokoska** [comment]
For sure, that would be great - the more research the better!

**Comment by jameskokoska** [comment]
Added here: https://github.com/jameskokoska/Cashew/commit/2436cb99577330948621f5c9249313e1476613d5!

**Comment by ngocanhtve** [comment]
@jameskokoska I have somewhat gotten used to the long-term loan feature. It is working smoothly. Thanks again.
