### ISSUE TITLE
[Feature Request] Merge accounts and delete transfer balance transactions

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#522]
**Is your feature request related to a problem? Please describe.**
I have two cash accounts in the same currency. At some point I need to merge them into one. Cashew is now supporting account merging, good job. The problem is that there have been times in the past when I have transferred some cash between the two cash accounts (those are balance transfer transactions), but when merged into one account, these balancing transactions become redundant. At this time, the two outgoing and incoming transaction lines belong to the same account and do not cause balance fluctuations for anyone.

**Describe the solution you'd like**
Automatically eliminate balance transfers between two accounts when merging them into one.

**Describe alternatives you've considered**
There is an option to ask if the user wants to delete the balance transfer transactions, don't forget to list those transactions out for the user to check to avoid mistakes before performing the removal those transactions.

**Additional context**

**Comment by jameskokoska** [comment]
I understand the use case, however transfers can happen between any number of accounts and Cashew is unaware of the accounts a transfer was made between - it only understands the transactions as line items. Adding the ability to delete transfers between the merge accounts is quite complicated and describing the process to the user in an intuitive way doesn't make much sense. The merge also shouldn't modify any transactions - as it creates unpredictable behavior to the user.

If you want to delete specific transactions before merging - apply the necessary filters and select all transactions and delete them manually.
