### ISSUE TITLE
[Feature Request] Ability to add past transactions by tapping on the date

### ISSUE THREAD

**Issue by awwRoar** [jameskokoska/Cashew#525]
**Is your feature request related to a problem? Please describe.**
Hi. Just started getting used to Cashew after moving over from an app called 'Monito' (used that for 4 years). I would like to request a feature wrt adding transactions for past dates.

**Describe the solution you'd like**
In Monito, tapping on a date on the Homescreen brings up the flow for adding transaction for that date. For example if I missed adding a transaction from 2 days, I would directly click on the date there and it would bring up the add transaction workflow with that date pre-filled. In Cashew, I need to click plus and then change the date everytime while adding a missed transaction. 

**Additional context**
Cashew also has the dates listed on the homescreen but they are not interactive, they are just there. It would be easier for me to add transactions this way for older dates. 

Thank you 😊

**Comment by jameskokoska** [comment]
Hi there! In Cashew, you can use the Calendar page to add a transaction on a specific day automatically. Long press the day on the calendar to do this. The date banner in Cashew is not an intractable UI element as it is too small to support proper user interactivity.

**Comment by awwRoar** [comment]
That's great. I wouldn't have noticed it otherwise. Thank you.
