### ISSUE TITLE
[Bug] Emoji corrupted in CSV export

### ISSUE THREAD

**Issue by awwRoar** [jameskokoska/Cashew#526]
**Describe the bug**
Hi. The emojis in CSV export appear as Chinese characters (sometimes Greek). Does not happen with all of them, some emojis are rarely spared.

**How to reproduce**
Create transaction titles with emoji -> Export CSV
I'm attaching a sample CSV I just exported and corresponding screenshots of what it looked like in the app.

**Screenshots/videos**
![Screenshot_2024-11-21-02-22-29-461_com budget tracker_app](https://github.com/user-attachments/assets/5fec5809-8391-4cf9-b4b6-ee7f49f96379)
![Screenshot_2024-11-21-02-22-34-401_com budget tracker_app](https://github.com/user-attachments/assets/3fc9ca86-dca3-449c-abdb-eaa1bc3ed741)

CSV here:
[cashew-2024-11-21-02-20-28-479900.csv](https://github.com/user-attachments/files/17836706/cashew-2024-11-21-02-20-28-479900.csv)

**Details**
 - Device: Xiaomi Pad 5
 - App Version: 5.4.4+420

**Comment by jameskokoska** [comment]
I am able to view each entry correctly (with the sample CSV attached to this issue). Make sure your CSV viewer supports UTF-8 encoding.
![image](https://github.com/user-attachments/assets/ca757d08-ec4c-4f33-b2ca-9979ea4f97da)
