### ISSUE TITLE
[Feature Request] In the Transactions tab, please add account selector to filter transactions, and see them grouped by month.

### ISSUE THREAD

**Issue by bagarwa** [jameskokoska/Cashew#53]
**Is your feature request related to a problem? Please describe.**
In my current money tracker app (MoneyLover), I have 4 bank account, 4 credit cards, CDs etc. In that app's transactions tab, I can select any one of those accounts, and I can see the transactions of just that one account, grouped by month. For example - 
<img width="400" alt="MoneyLover" src="https://github.com/jameskokoska/Cashew/assets/4424058/72d972b0-3ae3-4fae-aafa-f6210af5e1c9">

This helps me manage each account individually and easily. 

Cashew's Transaction view currently doesn't allow selecting just one account. It combines transactions from all accounts. For example - 
![Cashew](https://github.com/jameskokoska/Cashew/assets/4424058/776a0d8a-228c-4f4b-b0cc-6f13b817d474)

This one is a very less manageable. And the more number of accounts I have, more overwhelming this gets. 

**Describe the solution you'd like**
In the main transactions view itself, please provide an account selector. Selecting one account will show transactions from just that one account, in the main view's month grouped way. Selecting two accounts will show transactions from just those two accounts, in the main view's month grouped way. etc.

I made a quick dirty mockup in Paint - 
![Cashew Moc](https://github.com/jameskokoska/Cashew/assets/4424058/b6b6d9b4-9392-4050-aa67-5d2a0cc272f3)

**Describe alternatives you've considered**
Cashew does have a search option here, and I can select one account as filter. But the result is a single list of all transactions of that account, not grouped by months, like the main transactions view. 
![Cashew2](https://github.com/jameskokoska/Cashew/assets/4424058/748b8b9e-6588-4f96-ab09-8546c7d6a67f)

**Comment by jameskokoska** [comment]
You can now set filters on the monthly transactions page, this includes setting which accounts you would like to show :)
Added here: https://github.com/jameskokoska/Cashew/commit/dc36a6c8bf38e899186f1cab418a571fe3af7c58
![image](https://github.com/jameskokoska/Cashew/assets/50821962/3aab60d2-a105-499f-af32-9cdc88e946a1)

**Comment by bagarwa** [comment]
Fastest feature request fulfillment ever!! 🥳
