### ISSUE TITLE
[Bug] The webapp is using too much memory！

### ISSUE THREAD

**Issue by lilinfangrelax** [jameskokoska/Cashew#530]
**Describe the bug**

The webapp is using too much memory！

**How to reproduce**
click the PWA Web APP link: https://budget-track.web.app/ 

**Screenshots/videos**
![image](https://github.com/user-attachments/assets/626a1076-4fd3-4674-a10f-34eece7472f6)

**Details**
 - Device:  32G RAM
 - App Version:  Win11, Chrome( 131.0.6778.86)

**Additional notes**
normal usage of chrome
<img width="672" alt="{1D48432C-F9CA-4B07-9FDF-CA92064EC43B}" src="https://github.com/user-attachments/assets/69343ded-ef1b-4e78-8d9d-bf0045aaa6cd">

**Comment by jameskokoska** [comment]
Unfortunately this is a limitation of how Flutter runs web apps. Related to https://github.com/jameskokoska/Cashew/issues/9

You can open an issue on the Flutter repository by identifying the issue with a minimal reproducible example.
