### ISSUE TITLE
[Feature Request] default translations of subcategory icons for non-English languages

### ISSUE THREAD

**Issue by OuOu2021** [jameskokoska/Cashew#534]
**Is your feature request related to a problem? Please describe.**
Subcategories don't seem to have translations for non-English languages. When I try to add a subcategory by selecting an icon in Chinese or Japanese, the name field remains blank, while it will have a default English name if displayed language is English. 

**Describe the solution you'd like**
It would be more user-friendly if the subcategory icons were translated into all languages and used as the default name.

**Describe alternatives you've considered**
As an alternative, filling in the English name as a fallback would be better than leaving the name field blank.

**Additional context**
None.

**Comment by jameskokoska** [comment]
There are no plans to provide translations for icon names. They aren’t an important aspect of the UI. Can you provide an example where this is inconsistent between categories and subcategories? Closing for now.
