### ISSUE TITLE
[Bug] App link transactions are sometimes duplicated

### ISSUE THREAD

**Issue by Anu6is** [jameskokoska/Cashew#536]
**Describe the bug**. 
When using app links to create a transaction, sometimes reopening the app a few minutes later triggers the previously processed app link transactions add event. This causes a duplication of the transaction in question.

**How to reproduce**
- Add a transaction using app links
- Minimise Cashew
- Reopen Cashew 

Note: it's not always consistent

**Details**
 - Device: Pixel 6
 - App Version: 5.4.4

**Comment by jameskokoska** [comment]
Please provide a minimal reproducible example. Closing for now.
