### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by rahimalee1** [jameskokoska/Cashew#544]
Hello Sir hope you are doing great
I have a question regarding using your app I am currently running on my side and I am stuck on somethings..will you please guide me about the firebase stuff?

**Comment by jameskokoska** [comment]
Unfortunately I don’t have time to provide any development or debugging support.

**Comment by rahimalee1** [comment]
Sir please, I really need help if you can please give me your 5 minutes?

**Comment by rahimalee1** [comment]
Sir I wanted to say go and fuck your self
