### ISSUE TITLE
[Feature Request] Ability to duplicate budgets for more intuitive experience

### ISSUE THREAD

**Issue by Marwanello** [jameskokoska/Cashew#546]
**Is your feature request related to a problem? Please describe.**
I'm used to overflowing budgets each month, so any available or overspent money from past period budgets I add or subtract from the new one. I have seen another issue discussing that overflowing is not planned or won't be done, and it's okay for my workflow as I always calculate it externally. So, creating a new budget each month is a nice workaround. What I find frustrating is that I can't duplicate current budgets with their settings, making it easier to create new custom budgets each month.

**Describe the solution you'd like**
it would be great if a duplicate button is found in the budget summery so that it's much easier to create new budgets each month.

**Comment by dapperappdeveloper** [comment]
Duplicating budgets has already been added here: https://github.com/jameskokoska/Cashew/commit/88b96e8352b373ca0d25171d4ac8c0a07c9335de

**Comment by jameskokoska** [comment]
Duplicating budgets has already been added here: https://github.com/jameskokoska/Cashew/commit/88b96e8352b373ca0d25171d4ac8c0a07c9335de

**Comment by Marwanello** [comment]
When will it be released on the Google play store?
