### ISSUE TITLE
[Feature Request] View pie chart based on selected categories

### ISSUE THREAD

**Issue by blankexistence** [jameskokoska/Cashew#547]
**Is your feature request related to a problem? Please describe.**
I do a lot of transfers between different accounts and I like to track the flow of my cash. The issue here is that when I'm doing a lot of transfers, it unnecessarily takes up a lot of info space on the pie charts.

**Describe the solution you'd like**
I would like to see a way to apply filters to account pie charts so that I only see specific categories on the pie chart.
- If I want to see shopping and travel costs, then I only want to select those categories to be seen on the pie chart in an account.
- If I want to see all expenses except transfers, I want to uncheck transfers and see how much all other activities take up.

![screenshot](https://github.com/user-attachments/assets/22aab3a1-acc4-478e-802e-49538c512cb3)

Hope you see the issue here. Would greatly appreciate any thoughts!

**Comment by jameskokoska** [comment]
Balance corrections (transfers) are already not included in account spending summaries. Also if needed, you can apply filters in the All Spending page.
