### ISSUE TITLE
[Feature Request] Search by transaction amount

### ISSUE THREAD

**Issue by rasot71** [jameskokoska/Cashew#548]
I was considering about searching for a transaction by amount.

Again, I am not a developer so I do not know how hard might that be as far as coding is concerned, but it would be useful to type 1.59 or 24.99 in the search box and to find the transactions of that amount.
This would be useful when you remember the amount you spent but not on what or when you receive a bank statement of a transaction you do not remember. So, you type the amount and the results will guide you.

Thank you!

**Comment by jameskokoska** [comment]
This has already been added in or around commit https://github.com/jameskokoska/Cashew/commit/fa12f56382a192b7cb4c39a3c49541d3c13017a5
