### ISSUE TITLE
Synchronization with google error on ios

### ISSUE THREAD

**Issue by OrkidFashion** [jameskokoska/Cashew#55]
**Describe the bug**
Synchronization does not occur on the Google account. After the registration process is complete and the browser closes, I get an error message

**Screenshots/videos**
![WhatsApp Image 2023-11-29 at 14 07 53_a99ccbba](https://github.com/jameskokoska/Cashew/assets/39951935/be3aff13-23f1-41c1-b2ba-cfb8b6fce295)

**Details**
 - Device: iphone 7 ios 15.8
 - App Version: [ 4.9.4+256]

NOTE TO THE SUBMITTER
Reporting bugs is important for maintaining the app. Thank you for helping make the app a better experience for all!

**Comment by jameskokoska** [comment]
Unfortunately, I am unable to recreate this issue. More information will be needed
