### ISSUE TITLE
[Feature Request]Please add way to add reminder to any transaction

### ISSUE THREAD

**Issue by yooyoyo** [jameskokoska/Cashew#557]
**Is your feature request related to a problem? Please describe.**
Please add a way to add reminder to any transcation. Like for some transaction if i am suppose to get some cashback say after 15 days or 90 days, i can be easily be reminded about it Or if i lend someone money for x days, i can get a reminder.

**Describe the solution you'd like**
a radio button to enable reminder and a dropdown to set the number of days to get reminded about it say after 10,20, 30, 90 days.

**Describe alternatives you've considered**
Now i achive this using apple reminder, sometimes i just forget this step

**Comment by jameskokoska** [comment]
Only upcoming transactions support reminders on the day and time they are due. This application isn’t meant to become a reminders app.
