### ISSUE TITLE
[Feature Request] I would like to being able to put an different exchange rate of each transaction, especially for transfer between accounts

### ISSUE THREAD

**Issue by mvortizr** [jameskokoska/Cashew#558]
**Is your feature request related to a problem? Please describe.**
Currently i live in a country with hyperinflation and it's frustrating because no app suits properly because all have a global exchange rate that just isn't valid days after the transaction. Especially when you exchange one currency to another, the exchange rate tends to change and not be exactly the official for the day 

**Describe the solution you'd like**
When a currency is not your main one, I would like to be able to set a exchange rate for each transaction

**Describe alternatives you've considered**
Currently doing the transfers as "income" and "expense" but it just ruins my stats

**Additional context**
I am a dev, so I will probably made this change myself but I want to confirm if you think this is an user case that's valid to other people so I can maybe send a PR here

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating feature requests. Duplicates will not be addressed again.**
Not all feature requests will be considered. This budget app was created with careful thought given to each feature's usability and prevention of feature overload. As you use the app, you will discover possibly related useful features and that may not be obvious right away. 
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jameskokoska** [comment]
This is very closely related to https://github.com/jameskokoska/Cashew/issues/230

> Currently i live in a country with hyperinflation and it's frustrating because no app suits properly because all have a global exchange rate that just isn't valid days after the transaction.

If this is the case, transaction amounts can be converted in-place (to a stable currency you wish to represent your assets) as outlined by the FAQ: https://cashewapp.web.app/faq.html#multiple-currencies and https://github.com/jameskokoska/Cashew/issues/109

Cashew also allows you to add custom currencies, and therefore you can add a copy of your currency with a stable conversion constant and convert amounts in place to that currency.
