### ISSUE TITLE
[Question] Transaction deduplication and transaction volume

### ISSUE THREAD

**Issue by kubitre** [jameskokoska/Cashew#56]
Hi, i have same questions.

1. I decided to test your application, I have downloaded all my transactions from the bank for 5 years, I wanted to try to load everything into the application, but only 2000 transactions were chewed, if I try to load more, an error occurs, I provided a screenshot of the error. Most likely it crashes from memory (during import) <img width="1108" alt="Screenshot 2023-11-30 at 00 36 50" src="https://github.com/jameskokoska/Cashew/assets/32496864/7c300197-c331-4465-b739-89ae5bd4c5a2">

2. Can you tell me how many maximum transactions the application supports? (I currently have about 15k transactions

3. Is there an option to deduplicate transactions using some custom id?

**Comment by kubitre** [comment]
Hi, what I mean by deduplication is that roughly speaking, inserting the same transaction will not create an extra copy. For example, for all my transactions I generate a uniqueId based on UUID. Which I collect from bytes (payment purpose + amount + date). In my csv, this guarantees deduplication, but if I repeat the import by mistake, I will have to manually sort out this problem or drop it and start all over again. Perhaps I would add an optional feature to your application, within which I would track duplication.

What is it for? As I wrote above, I have about 15k transactions, in order to safely import everything into your application, and so that not a single thing is duplicated, I want to somehow limit this insertion. + I wrote a small script for myself that extracts from data bank statements (I have about 5 banks), which I planned to turn on once a month and load new transactions into this application. I wouldn’t want to accidentally duplicate it

**Comment by kubitre** [comment]
Roughly speaking, I'm talking about the idempotency key

**Comment by jameskokoska** [comment]
Oh I see, that makes sense!
When transactions are imported a unique key is generated for every transaction, this includes when it is created when importing a CSV

**Comment by kubitre** [comment]
strange, I didn’t see this key when I imported it, ok, I’ll try to check it on the new release

**Comment by jameskokoska** [comment]
Just to follow up: the key is hidden for the user and can only be viewed in an exported database for example. Relational databases require a key for entries
