### ISSUE TITLE
[Feature Request] Monthly All Spending Summary Notifications

### ISSUE THREAD

**Issue by Michael152843** [jameskokoska/Cashew#560]
**Is your feature request related to a problem? Please describe.**
Currently, the only types of notifications available in the app are `Add Transaction` and `Upcoming Transaction` reminders. Since it's important to keep track of one's financial situation over longer time periods, I suggest adding a third type of notification:

**Describe the solution you'd like**
As we approach the end of a month, it would be great to receive a notification from the app such as: `Check your Spending Summary for {{name of the month}}`

This notification would lead the user to the `All Spending Summary` page, where they could view their financial information for the concluding month.

This small addition would help users develop a healthy financial habit of reviewing their monthly transactions and making plans as they enter a new month.

**Comment by jameskokoska** [comment]
Cashew is meant for manual addition of transactions and therefore the app will be opened automatically many times a month. This app is not trying to grab the attention of users/bother users with unnecessary reminder notifications. A reminder notification to check the All Spending Summary every month is better to be achieved through the use of a dedicated reminder app.
