### ISSUE TITLE
[Bug] Import Data From Money Manager 10.3.5 to Cashew v5.4.4+420,db-v46

### ISSUE THREAD

**Issue by mfaisalshahzad** [jameskokoska/Cashew#561]
**Describe the bug**
i wanted to import Data from my existing money manager Application as subjected on Android but the balances don't tally and new unwanted accounts are created for transactions that are transferred. 

[CSV_2024_12_22_07_46_20 for Cashew Bug report.csv](https://github.com/user-attachments/files/18246791/CSV_2024_12_22_07_46_20.for.Cashew.Bug.report.csv)

**How to reproduce**
Import the attached csv.

**Screenshots/videos**
[Screenshots/videos are always helpful]

**Details**
 - Device: android 11
 - App Version: Money Manager 10.3.5 to Cashew v5.4.4+420,db-v46

**Additional notes**
Either the import template of cashew is not correct or there is something wrong with the wizard. in previous Application there was provison of creating multiple accounts/login in which i was able to manage in one account unlimited personal financial accounts and in another account/login without logging off the current login i used to maintain office accounts. so that was good feature. 

The web version of Cashew is not stable. its popup screens open not properly in the laptop. and even scroll bars don't help. so that need to be fixed.

NOTE TO THE SUBMITTER
Reporting bugs is important for maintaining the app. Thank you for helping make the app a better experience for all!

**Comment by jameskokoska** [comment]
The import is working as intended. Since you have separate account names for transfers, they will be imported as such. Please read the FAQ on importing transactions - it outlines the process of importing transfers: https://cashewapp.web.app/faq.html#import-csv-data
