### ISSUE TITLE
[Question] Import from google spreadsheet

### ISSUE THREAD

**Issue by Fridgeir-9** [jameskokoska/Cashew#565]
I've been trying to import my data for a few hours, but even when I copy the template and use it, I get an XMLHttpRequest Error message. I have now tested different devices and browsers, whether private session or normal session, I always get this message.

I don't know what to do, do you have any tips for me?
![image](https://github.com/user-attachments/assets/a6a42ee0-f23a-417a-b8ec-9bf881ecb50f)

![image](https://github.com/user-attachments/assets/a9b6bc95-18d0-464a-9dda-14b431e1fa49)

**Comment by jameskokoska** [comment]
Given a lack of information it’s difficult to understand the issue. Make sure you have enabled sharing permissions on the Google Sheet and have copied the correct link. Additionally, you can import a CSV file directly as an alternative.
