### ISSUE TITLE
[Feature Request] Show account balance at the end of the day and UI improvements

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#58]
First of all, thank you for applying the translation to the latest release on Google Play Store.

Next I would like to suggest adding a feature to display each account's balance at the end of the day, meaning after each last transaction of the day. This helps to know the exact balance of accounts when reviewing past transactions. (Highlighted above to the current "total cash flow" number. *Where I marked red circle number **1***.)

Then I would like to suggest a small change about UI. In the transactions tab, I have drawn a line that separates transactions between days. And highlight the day number to make it easier to locate the time of the month. _Where I marked red circle number **2**_.

![UI](https://github.com/jameskokoska/Cashew/assets/125894401/a94d4f1f-e69c-4b0f-830c-5a8fd55f276f)

**Comment by ngocanhtve** [comment]
Now, number 1, as you said, may need to consider availability.

But number 2, I think at least it helps me to immediately distinguish transactions from different days at a glance. As for it taking up more lines on the screen, I don't think it's important. Phone screens are now very long, and we have to swipe up endlessly anyway. The content is spread down according to our swiping gestures so I think it's fine. 

Besides, if implemented, they can be made a little smaller to take up less space, as long as they are arranged properly and bold enough to stand out.

But the decision is up to you. Any reasonable reason given will convince me. Have a good day! 🙂

**Comment by jameskokoska** [comment]
Appreciate the clarification! I think I'll add it into the all spending page for now - I'll add a toggle that allows users to see the total net spending at that point in time. You can also pin the all spending page to your tab bar for easy access :)

I'll work on the feature in the coming days!

**Comment by jameskokoska** [comment]
Added here: https://github.com/jameskokoska/Cashew/commit/a237b11f5afb0e0cbf321fd9136f6742a2a50a9b

In the all spending page you can select cumulative totals. The graph and the ranges listed will show the net total amounts for each period
![image](https://github.com/jameskokoska/Cashew/assets/50821962/a560b11c-b5ae-4b92-8542-ed607a6cc1a2)
