### ISSUE TITLE
Keep getting signed out on webapp every time tab is closed

### ISSUE THREAD

**Issue by dillfrescott** [jameskokoska/Cashew#62]
**Describe the bug**
Keep getting signed out on webapp every time tab is closed

**How to reproduce**
n/a

**Screenshots/videos**
n/a

**Details**
 - Device: Archlinux - Brave browser

**Additional notes**
Not sure!

**Comment by dillfrescott** [comment]
Oh, I understand. Makes me mad at Google because this is a pain in the butt to have to keep signing back in...

**Comment by nescafenori** [comment]
Hello, can you implement a new login system that's not reliant on Google?  @jameskokoska
