### ISSUE TITLE
[Feature Request] Transfer fees (or tax)

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#64]
I just went to the ATM to withdraw some cash. And I intend to record this transaction in Cashew. I discovered there was no place to record the fee that every ATM deducts from our account every time we withdraw cash.

The alternative is to create a fee category specifically for this case. Then create a separate transaction.

So. The 2 transactions will not be linked together. While it is actually just a single withdrawal transaction. It's just that the amount of cash received is less than the amount the bank will deduct from our ATM account.

So I hope there will be an official feature for this case. An official feature for all transfers transaction. Because even bank transfers between two bank accounts are still subject to fees or taxes, more or less depending on the bank or country, but are rarely free.

**Comment by jameskokoska** [comment]
If you want to track a fee for transfers, I would create an expense and deduct it from the origin transfer account.

**Comment by webpixeldesign** [comment]
This will also be useful for foreign transactions, in India we have to pay forex for each transactions made in foreign currency. For now, I also just create another category with the name bank, to track atm fees, forex markup and surcharge on fuel...
