### ISSUE TITLE
[Feature Request] Choose first day of the heat map

### ISSUE THREAD

**Issue by Ansem93** [jameskokoska/Cashew#67]
[A clear and concise description of what the problem is. Ex. I'm always frustrated when...]
Currently the first line of the heat map is Sunday. 
I find it kind annoying since the week start on Monday. 
**Describe the solution you'd like**
I would like to be able to choose Monday as first line. Maybe you could let choose the user any day?

**Comment by jameskokoska** [comment]
Thanks for letting me know! It should now follow your devices locale.

Fixed here: https://github.com/jameskokoska/Cashew/commit/a5b6b739267afd34b918e7ac238b144bdeeb428e#diff-47c088599667b6be88e42d1e6ff8cd126e1442ab8b0a5a881eb153ac6c725b01R202-R205
