### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Darchiver** [jameskokoska/Cashew#68]
1. need to split bills by amount wise also (only percentage wise splitting is available right now as sometime percentage should be calculated externally for splitting amount to be split unevenly)

2.when entering the collected prompt in lent amount you can add option to mention the amount collected also( since sometime amount may be wavied off (or) collected amount may vary based on a concession/overpaid in which collected amount could be higher or lower than the amount paid )

3.[i dont know that i have explained my suggestion properly to you , but If you can understand this it would be awesome]When a bill is splitted and loaded in transaction page all split amount is shown as individual transaction for collecting right now ; which can be shown as a single transaction of whole bill amount splitted, and when we enter that transaction page you can show those individuals separate split amount where it can be collected collect.

 LOVE YOUR WORK❤️

**Comment by Darchiver** [comment]
-**This is an app called "splitwise" and this is the idea of my feature request. This represent my Feature Request for 1. And 3.
**
https://github.com/jameskokoska/Cashew/assets/121549490/907dab30-61dc-4e75-8ca3-e1790288490c

- **This is the interface which I requested for your bill splitter tool 
**
Screen_Recording_20231205_204620_Splitwise_1.mp4 …

**Comment by jameskokoska** [comment]
Hi there! Keep in mind that this application is not a replacement for Splitwise. Cashew is not a bill splitting application, it is a budget tracker. The bill splitting feature is just for added convenience, however it is not meant to replace Splitwise. Splitwise has many features Cashew will never have.

I would recommend to use Splitwise over Cashew if it suits you needs better.
