### ISSUE TITLE
Equal chart in spite of different percent of income [Bug]

### ISSUE THREAD

**Issue by krzemyczek** [jameskokoska/Cashew#70]
**Describe the bug**
No matter of percent difference, chart is divided equality. (In all spending)

**How to reproduce**
Add two diffrent source of income with different amount like 1£ & 100£
**Screenshots/videos**
![Screenshot_2023-12-06-08-41-20-47_e6824bb696bab290a098ced1b814527d](https://github.com/jameskokoska/Cashew/assets/81762967/c3fd38b8-14a5-4ae3-bf07-85865c6b1b52)

**Details**
 - Device: oppo reno 7 5g
 - App Version: v5.0.0+266, db-v45

**Comment by jameskokoska** [comment]
Appreciate the bug report!

Has been fixed here: https://github.com/jameskokoska/Cashew/commit/02ab50f5869431d7d1c6b8d305dc9d07d0c2ff01#diff-bbfa9c39f2ba4fbafb9998f419e9d14d7bbf769f3bbffcc9368dd42255cf43afR299-R305
