### ISSUE TITLE
[Question] how do I change the table so that income is on the left and expenses are on the right??

### ISSUE THREAD

**Issue by Azis-Kun** [jameskokoska/Cashew#72]
![image](https://github.com/jameskokoska/Cashew/assets/127124629/f862e8b7-1902-4862-a1f6-ef60f562996d)

**Comment by jameskokoska** [comment]
There is no way to change the order

**Comment by Azis-Kun** [comment]
> There is no way to change the order

I can change it, but now I want to remove the budget from the navbar??, I tried deleting it from the navbar button but it still doesn't disappear

**Comment by jameskokoska** [comment]
Sorry, I misinterpreted the photo
Yes you can change the navbar buttons by long pressing
