### ISSUE TITLE
[Feature Request] Multi profile support

### ISSUE THREAD

**Issue by dagema1** [jameskokoska/Cashew#73]
**Is your feature request related to a problem? Please describe.**
I operate two tiny businesses and aim to monitor the revenue and expenditures for each one independently, distinct from my personal financial transactions.

**Describe the solution you'd like**
maybe having a profile switcher similar to Google apps, allowing for distinct instances for each of my businesses to effectively manage and separate their financial activities. and If possible and applicable, the ability to transfer from one profile to another.

**Describe alternatives you've considered**
I tried using a different account for each business, but it didn't work well because each business has different amounts of money coming in and going out.

**Comment by jameskokoska** [comment]
Cashew supports multiple accounts/wallets. You can create a wallet for your separate business if you wish to track transactions just for that. There are no plans for entirely different instances of the app within. If you really need separation, you can create a clone of the app on your device.
