### ISSUE TITLE
delete "update both balance transfers" when adding goal to transfer [bug]

### ISSUE THREAD

**Issue by krzemyczek** [jameskokoska/Cashew#76]
**Describe the bug**
Hi, when I add goal in income transfer (let it be "savings") the pop up comes out. But in goals it is unnecessary because it has no sense of adding goals in both: transfer in and out because summary it would be 0 
-100$ from saving, +100$ to saving make it 0
I hope i make it clears

**Screenshots/videos**
![Screenshot_2023-12-11-17-23-09-23_e6824bb696bab290a098ced1b814527d](https://github.com/jameskokoska/Cashew/assets/81762967/28c3120c-15f6-4408-a669-de8a244b58c7)

**Comment by jameskokoska** [comment]
When a paired balance correction is just added to a goal, it no longer prompts to update both
Fixed here: https://github.com/jameskokoska/Cashew/commit/a2901558c93735e9ff3522af428bdb3b87a8c3e5
