### ISSUE TITLE
[Feature Request] Supports bank logo as a display icon account

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#77]
I realized that banking or e-wallet applications on my phone have very recognizable icon logos.

Most Cashew accounts are corresponding bank accounts. And I think it would be great if the icons of supported banks were displayed as identifiers of accounts in Cashew.

**Comment by jameskokoska** [comment]
Unfortunately there are no plans to support icons for other banks. Most bank logos require specific marketing requirements and Cashew does not hold the rights to other bank logos.

Custom icons (uploaded by the user) have been considered, however, the main issue with this is that it will be very difficult to store images and support syncing across platforms.

**Comment by ngocanhtve** [comment]
Isn't cross-platform synchronization what the image of attached bill are doing?

**Comment by jameskokoska** [comment]
Yes but it relies on Google Drive. If users were to add custom icons, it would be using their own Google Drive, which I find is not intuitive. Especially if they delete the icon on their Drive.

**Comment by deers** [comment]
how if you just store the image url instead the image, let the user choose where the image will be taken / stored. For visual person like me, looking the image to see the account is much faster then reading the text. Hope this can be implemented. :)
