### ISSUE TITLE
[Question] How to import debt transactions

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#78]
What is the correct template for importing debt transactions? I tried creating debt transactions in Cashew and then exporting them to csv to see how it was formatted. But I didn't get a useful thing.

The csv and Google sheet templates provided do not show debt transactions.

**Comment by jameskokoska** [comment]
Debt transactions cannot be imported. Usually CSV exports from other apps do not contain debt columns. There is also no universal way to specify which debt to add transactions to when importing a CSV (e.g. they would all need to be tagged with the same name of sorts to identify which 'loan' to add it to)

**Comment by jameskokoska** [comment]
To add on, as the warning says when the CSV is exported from Cashew, whatever is exported from Cashew does not mean it can be imported in the same way. To backup your data properly, use the Export Data File

**Comment by ngocanhtve** [comment]
@jameskokoska Backup from Cashew is not the issue of this question. The issue is how Cashew can import debt transactions from other apps.

The other issue is that Cashew can't export Gsheet files so it is forced to export Csv to see how debt transactions show. If Cashew can properly import debt transactions using Gsheet, please provide the correct format.

I have so many debt transactions, manual processing would kill me.

**Comment by jameskokoska** [comment]
Yes, sorry for the misunderstanding. What I am trying to say is: Just because it is exported from Cashew does not mean it can be imported (as stated by the warning popup when a CSV is exported)

Cashew cannot import debt transactions 
> Usually CSV exports from other apps do not contain debt columns. There is also no universal way to specify which debt to add transactions to when importing a CSV (e.g. they would all need to be tagged with the same name of sorts to identify which 'loan' to add it to)

**Comment by ngocanhtve** [comment]
What if I could prepare data with a "debt column" for import? And I'm going to come from the Gsheet file.
