### ISSUE TITLE
[Feature Request] Allow Adding Custom Currencies

### ISSUE THREAD

**Issue by Synaptic149** [jameskokoska/Cashew#79]
**Is your feature request related to a problem? Please describe.**
One problem I have is I can't log transactions on accounts that use points instead of typical currency (such as loyalty points).

**Describe the solution you'd like**
The ability to add a custom currency with its own exchange rate. Not only can it allow people who don't have their currency listed, but it can also allow points to be added.

**Comment by jameskokoska** [comment]
You can add custom currencies now.
Added here: https://github.com/jameskokoska/Cashew/commit/972ca8c34811c5d445e0f37865f08260d8d0c5cc
