### ISSUE TITLE
Sample CSV does not include wallet field

### ISSUE THREAD

**Issue by Clon1998** [jameskokoska/Cashew#8]
I just noticed that the generated sample CSV does not include the `wallet` column that is available by looking at the code.

Import [code section](https://github.com/jameskokoska/Cashew/blob/8fade87687b61001e601bc3475734f0f0dae9571/budget/lib/widgets/importCSV.dart#L120-L172) (I assume)

Sample file generation [code section](https://github.com/jameskokoska/Cashew/blob/8fade87687b61001e601bc3475734f0f0dae9571/budget/lib/widgets/importCSV.dart#L731-L759) (I assume)

**Comment by jameskokoska** [comment]
Thanks for letting me know! Appreciate the code locations, you nailed them

Fixed in https://github.com/jameskokoska/Cashew/commit/4e1e415b0ac06aa90848314f6f9e6bab6b0e64b0

**Comment by Clon1998** [comment]
Awesome thanks!

Still need to migrate my data from my old app to cashew to see how your app works for me :).
I actually was so upset with the currently available apps for IOS that I was about to build my own app. But now I'd rather contribute to cashew 🚀
