### ISSUE TITLE
[Feature Request]Linking of transactions to a individual 

### ISSUE THREAD

**Issue by Frostedfox** [jameskokoska/Cashew#81]
**Is your feature request related to a problem? Please describe.**
In a Group you pay for your friend and your friend Pays for you
To keep Track of all the borrowed and lent money from a single person 
To calculate the final amount whether to receive or payback

Need an option to link all the lent and borrowed transactions to a person

**Comment by jameskokoska** [comment]
You can create a long term loan for a single person. When you borrow money, add a Borrowed transaction, when you lend money, create a Lent transaction under that loan. Lending and borrowing, depending on the loan type, will decrease/increase the total accordingly and keep track of the difference.

**Comment by tidianeb5** [comment]
Thanks
