### ISSUE TITLE
[Bug] Sync with other than Gdrive

### ISSUE THREAD

**Issue by acress1** [jameskokoska/Cashew#84]
**Describe the bug**
I don't use Google Drive, but Nextcloud. So I tried to find a way to "sync" my database with Nextcloud. I used the "import/export sql" feature. But I cannot import a file which is in my Nextcloud folder (all the files are in gray, certainly because the app doesn't have access to it). How could I proceed to make a pseudo sync without using GDrive ? Thanks !

**How to reproduce**
- Export the SQL file in a Nextcloud database
- Try to import the SQL file (in the Nextcloud database) in the app

**Details**
 - Devices: both on iPad Pro and OnePlus 5T

**Comment by jameskokoska** [comment]
Hi there! Unfortunately, only Google Drive is supported as the cloud service. There aren't any plans to support other services as of now. You can export the database backup locally and import a local file.

**Comment by acress1** [comment]
Forgot : 
Hi !

And thanks 😀

**Comment by acress1** [comment]
> Hi there! Unfortunately, only Google Drive is supported as the cloud service. There aren't any plans to support other services as of now. You can export the database backup locally and import a local file.

Ok in this case it is quite complicated to use it inter-devices, because I would have to export it in the cloud, then download it locally and import it.
Not complicated but longer.

But thanks anyway! The app seems awesome. :) and you're quite reactive, thank you!
