### ISSUE TITLE
[Question] Help needed regarding bill splitter

### ISSUE THREAD

**Issue by Chiggy-Playz** [jameskokoska/Cashew#86]
**Describe your question**
Hey. This might be a stupid question but maybe I am doing or understanding this wrong. I need some help regarding how the bill splitter works. Say I have the following scenario:
Me and my friend goes out, and we both pay for some stuff.
I pay for drinks (split 50% between both of us)
I order a pizza (I'll pay 100% for the pizza)
He orders a burger (He'll pay 100% for the burger)
He pays for the train ride back on the way (split 50% between both of us)

Now I want to know how I should be putting it in the app. Especially, the first one. Like, say the drinks were for $100. So I paid $100 from my account, and now my friend owes me $50. I have already paid for the $50. And same for the case where he paid full and i owe him 50%. Can you please show me an example for this? 😅

Also I've got a suggestion: Bringing out the bill splitter into the more tab on home instead of having it nested in the settings 😁

**Comment by jameskokoska** [comment]
Hey thanks for reaching out!

In the bill splitter information (i) it states that it assumes only one person paid for the bill. This is the most support the bill splitter will get.

If you want more insights into why the bill splitter doesn't support more features (and why it is tucked away in Settings), it is addressed in these issues: https://github.com/jameskokoska/Cashew/issues/47#issuecomment-1826621550
https://github.com/jameskokoska/Cashew/issues/68#issuecomment-1841078113

![Screenshot_20231217_141841.png](https://github.com/jameskokoska/Cashew/assets/50821962/7e8b3ff8-5451-4c85-934f-bc37459aa30b)

**Comment by Chiggy-Playz** [comment]
Ah that explains it. Thank you so much for the quick response! Love the app ♥
