### ISSUE TITLE
[Question] importing transactions into sub categories

### ISSUE THREAD

**Issue by lerio** [jameskokoska/Cashew#87]
**Describe your question**
I'm trying to import transactions into a sub-category, but the sample import CSV (or import Google Sheet) doesn't have a sub-category field. Is it possible to do so, and how? Thanks!

**Comment by jameskokoska** [comment]
Subcategory support isn't supported for CSV imports as of now. You can merge categories to convert a main category into a subcategory after the import happens.

So import transactions as a main category using the CSV template and after the import occurs, change the main category into a subcatgeory of your corresponding main category.

**Comment by jameskokoska** [comment]
Adding this change here from https://github.com/jameskokoska/Cashew/issues/202

If a subcategory exists with the same name of the attempted import transaction, it will properly be added to the subcategory. Added here: https://github.com/jameskokoska/Cashew/commit/324dbac653acde43014c8e39ed6e131f7b1e4ead.
For example, if we have a subcategory called `Groceries` already created in Cashew, and a transaction in the CSV has the category name set to `Groceries`, the subcategory will properly be applied when importing (only if it exists beforehand!)

**Comment by djubreposlednje-prog** [comment]
I would say this is the biggest app problem. Peopl can't do a migration from other apps
