### ISSUE TITLE
[Feature Request] About button and the Open Source button

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#91]
![Screenshot_20231220-213040_Trebuchet~2](https://github.com/jameskokoska/Cashew/assets/125894401/e38b56c4-031d-4635-9256-11b449c582f6)

The **About button** contains more information inside, including the **Cashew is Open Source** button, to go to the github page is exactly the same as the **Open Source** button at **More** page.

I think that wastes a good location just to open a github link, while a lot of information in About is in a more secluded location.

![Screenshot_20231220-222741_Trebuchet~2](https://github.com/jameskokoska/Cashew/assets/125894401/90a41e64-90bd-4138-a5f1-0408e24165b3)

So I suggest moving the About button ⓘ down to the position of the current Open Source button. Or at least a more prominent place than the current lonely corner.

**Comment by jameskokoska** [comment]
Yea you're right, has been tweaked here:
https://github.com/jameskokoska/Cashew/commit/8b4f72cf9c2f586b7043550b14acbdac027a9140#diff-27a7fed91d5f4006ca1b85536ea889607103d7fbfaedb114577f4ab45dc5f8bbL102-L195
