### ISSUE TITLE
[Feature Request] Option to exclude the amount in the "Accounts" from the overall "Expense/Income"

### ISSUE THREAD

**Issue by Umairuem** [jameskokoska/Cashew#92]
**Is your feature request related to a problem? Please describe.**
There are some accounts that I want to keep track of with all the accounts in Cashew, let's say the amount of USDs in my Crypto Exchanges. But I don't want them to add to my other Expense/Income amounts as they are different from my actual amount. But I still want to keep their track within Cashew to keep all my amount in one place.

**Describe the solution you'd like**
A really simple feature that would allow the "Account" to exclude their amount from the overall "Expense/Income" calculated in Cashew.

**Comment by jameskokoska** [comment]
This has already been added in v5.0.7+

**Comment by Umairuem** [comment]
Got it. Can you please provide me with some guidance on how to do that? 
As in the "Account", I'm still seeing the same 3 options:
- _Correct Total Balance_
- _Transfer Balance_
- _Merge Account_

Or are you referring to that now we can use filters in our "Expense" and "Income" sections?
Is there any way that we can get these "Expense/Income/Net Worth" amounts on our homepage without the amount we want to be excluded from certain Account(s)? 
This is the feature I was requesting. My app version is v5.0.9

Thanks in advance!

**Comment by jameskokoska** [comment]
You can select which accounts are included in the Income/Expense total by long pressing the total home page widget or by editing it in the Edit Home page

**Comment by Umairuem** [comment]
Oh, got it. Thanks a lot, James! 
For this amazing app, and especially for your quick responses 💯
