### ISSUE TITLE
[Bug] The percentage overlay is hidden below

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#95]
When viewing the pie chart and clicking on a specific category you will see the percentage obscured below.
![Screenshot_20231225-222935_Trebuchet~2](https://github.com/jameskokoska/Cashew/assets/125894401/532f880f-f276-43d7-9722-71c1170c8d05)

As far as I know Android works based on overlays. Just put this percentage overlay above all when clicking on it.

**Comment by jameskokoska** [comment]
Duplicate of https://github.com/jameskokoska/Cashew/issues/7

**Comment by jameskokoska** [comment]
Fixed here: https://github.com/jameskokoska/Cashew/commit/5feefd7a605643ac26f63e9359e0dff56a83d27a#diff-bbfa9c39f2ba4fbafb9998f419e9d14d7bbf769f3bbffcc9368dd42255cf43afR381-R385

**Comment by ngocanhtve** [comment]
> Fixed here: 5feefd7#diff-bbfa9c39f2ba4fbafb9998f419e9d14d7bbf769f3bbffcc9368dd42255cf43afR381-R385
Amazing!
