### ISSUE TITLE
[Bug] No title auto complete if "ask title" is disabled

### ISSUE THREAD

**Issue by Ansem93** [jameskokoska/Cashew#96]
**Describe the bug**
I have "ask for transaction title" disabled 
When I add a title it doesn't auto complete it 

**How to reproduce**
When enabled:
![SmartSelect_20231226_000820](https://github.com/jameskokoska/Cashew/assets/6626218/b7a8131a-9156-4d3b-b366-17b1dd4a5e69)
![SmartSelect_20231226_000859](https://github.com/jameskokoska/Cashew/assets/6626218/6219e036-2d42-42ca-a5ef-3d9882afcc9f)

When disabled:
![SmartSelect_20231226_000949](https://github.com/jameskokoska/Cashew/assets/6626218/f123b4af-a6bd-4ddc-b12a-78f0cf1141f3)
![SmartSelect_20231226_001008](https://github.com/jameskokoska/Cashew/assets/6626218/65f737c2-d497-4100-82a6-0e6591dac34b)

As you can see: when I disable it it doesn't suggest any title. 
I think it's a bug and it should suggest already created titles regardless 

**Details**
 - Device: samsung s21
 - App Version: 5.1.0+293

**Comment by jameskokoska** [comment]
Title recommendations only appear when adding a transaction. This is because when adding a transaction the category is most likely not set, titles are used to increase the speed that transactions are added - filling in the category quickly.
