### ISSUE TITLE
[Feature Request] Add an option "always suggest titles"

### ISSUE THREAD

**Issue by Ansem93** [jameskokoska/Cashew#97]
**Is your feature request related to a problem? Please describe.**
Regarding issue #96 , I like to instert import first and eventually title second. That's why I keep "ask for transaction title".
I don't insert title anymore because it takes longer without a suggestion of already created titles.
Also having the suggestions avoid insert a title twice like "Audible" and "Audible " with a space.

**Describe the solution you'd like**
I would love to have an option to enable auto suggest always, regardless if I insert the title or the import first.
I would also suggest if, it's not more complicated, to restrict the search to the titles of the selected category. Otherwise just keep the already implemented auto suggest.

**Additional context**
Thanks again for this great app :D

**Comment by jameskokoska** [comment]
Added here: https://github.com/jameskokoska/Cashew/commit/5faa0a92dce920def9fbbab962ec6a711a7d57ad

The search for titles isn't restricted by the selected category, just to be consistent with other searches
