### ISSUE TITLE
[Question] Programmatic access / API for the data?

### ISSUE THREAD

**Issue by knthmn** [jameskokoska/Cashew#99]
Hello,

Is it possible to programmatically edit / export transactions?  I want to build some scripts that can add transactions or use the data to generate a custom report. 

Cheers

**Comment by jameskokoska** [comment]
You can export the data as a CSV or SQL file from the app. There is no external API as all data is stored on device.

**Comment by jameskokoska** [comment]
Adding information about the newly added App Links API

App Links allow for the automation of the addition of transactions. One such use case would be to link it to your bank or notifications to generate an app link, write a custom script, or create a custom GPT (AI chat) to generate a link based on given params. You can check out the documentation in the README here: https://github.com/jameskokoska/Cashew?tab=readme-ov-file#app-links App Links are supported by Cashew.
